
const TRIBES = [
  { id: "earth", name: "땅", en: "Earth", icon: "🪨", open: true, color: "#8b5a2b" },
  { id: "fire", name: "불", en: "Fire", icon: "🔥", open: true, color: "#d44512" },
  { id: "wind", name: "바람", en: "Wind", icon: "🌬️", open: true, color: "#7ec8c8" },
  { id: "water", name: "물", en: "Water", icon: "💧", open: true, color: "#2a7ad4" },
  { id: "dark", name: "암흑", en: "Dark", icon: "🌑", open: true, color: "#5a2a7a" },
  { id: "light", name: "빛", en: "Light", icon: "✨", open: true, color: "#f0e0a0" },
];

const TRIBE_ICONS = {
  earth:"assets/img/icons/earth.png",
  fire:"assets/img/icons/fire.png",
  wind:"assets/img/icons/wind.png",
  water:"assets/img/icons/water.png",
  light:"assets/img/icons/light.png",
  dark:"assets/img/icons/dark.png",
  metal:"assets/img/icons/earth.png"  /* no metal tribe frames; reuse earth */
};
const HUD_UI = {
  board:"assets/img/hud/board.jpg",
  hp:"assets/img/hud/hp.jpg",
  mana:"assets/img/hud/mana.jpg",
  deck:"assets/img/hud/deck.jpg"
};
const COIN_PLUS = "assets/img/coins/plus.png";
const COIN_MINUS = "assets/img/coins/minus.png";

const CARDS = [
// === UNITS (source of truth: 판타지아레나_유닛목록.xlsx + art {id}.jpg; never add orphan e29+ units here) ===
// 유닛 단일 소스 — 유닛목록.xlsx + art/{id}.jpg 가 정본. e29+ 고아 유닛 추가 금지.
  { id:"e1", tribe:"earth", name:"놀", cost:1, type:"minion", atk:1, def:0, hp:3, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e2", tribe:"earth", name:"대지술사", cost:4, type:"minion", atk:3, def:0, hp:6, atkC:0, defC:0, hpC:2, text:"" },
  { id:"e3", tribe:"earth", name:"그린드래곤", cost:9, type:"minion", atk:5, def:1, hp:12, atkC:-2, defC:0, hpC:2, rarity:"rare", ability:"면역", text:"면역" },
  { id:"e4", tribe:"earth", name:"드라이어드", cost:2, type:"minion", atk:0, def:0, hp:5, atkC:1, defC:0, hpC:1, text:"" },
  { id:"e5", tribe:"earth", name:"드워프병사", cost:2, type:"minion", atk:2, def:0, hp:4, atkC:-2, defC:0, hpC:2, text:"" },
  { id:"e6", tribe:"earth", name:"만드라고라", cost:2, type:"minion", atk:1, def:0, hp:3, atkC:0, defC:0, hpC:3, atkSkill:7, text:"약화공격" },
  { id:"e7", tribe:"earth", name:"샌드맨", cost:2, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:1, text:"" },
  { id:"e8", tribe:"earth", name:"나무궁수", cost:2, type:"minion", atk:1, def:1, hp:2, atkC:0, defC:0, hpC:1, atkSkill:2, text:"관통공격" },
  { id:"e9", tribe:"earth", name:"오크", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:-1, defC:0, hpC:0, atkSkill:4, text:"연속공격" },
  { id:"e10", tribe:"earth", name:"드워프대장", cost:3, type:"minion", atk:2, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e12", tribe:"earth", name:"스톤골렘", cost:3, type:"minion", atk:2, def:0, hp:6, atkC:-1, defC:0, hpC:1, text:"" },
  { id:"e13", tribe:"earth", name:"마운록", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:0, defC:0, hpC:1, rarity:"rare", ability:"복수", text:"복수" },
  { id:"e14", tribe:"earth", name:"마초", cost:10, type:"minion", atk:7, def:2, hp:11, atkC:-1, defC:-1, hpC:1, rarity:"legendary", atkSkill:10, ability:"복수", text:"돌파공격 · 복수" },
  { id:"e15", tribe:"earth", name:"암석창병", cost:1, type:"minion", atk:3, def:0, hp:1, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e16", tribe:"earth", name:"켄타우로스", cost:3, type:"minion", atk:2, def:1, hp:3, atkC:-1, defC:-1, hpC:1, atkSkill:3, text:"돌진공격" },
  { id:"e17", tribe:"earth", name:"고르곤", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:0, defC:0, hpC:2, atkSkill:8, text:"석화공격" },
  { id:"e18", tribe:"earth", name:"대지의 정령", cost:4, type:"minion", atk:2, def:0, hp:6, atkC:-2, defC:0, hpC:2, ability:"유언", text:"유언" },
  { id:"e19", tribe:"earth", name:"곽가", cost:8, type:"minion", atk:3, def:1, hp:10, atkC:-1, defC:-1, hpC:1, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"e20", tribe:"earth", name:"베헤모스", cost:6, type:"minion", atk:3, def:2, hp:8, atkC:-2, defC:-2, hpC:2, rarity:"uncommon", atkSkill:3, text:"돌진공격" },
  { id:"e21", tribe:"earth", name:"록마운틴킹", cost:5, type:"minion", atk:3, def:0, hp:8, atkC:-1, defC:0, hpC:1, rarity:"uncommon", ability:"복수", text:"복수" },
  { id:"e22", tribe:"earth", name:"스핑크스", cost:5, type:"minion", atk:3, def:0, hp:8, atkC:0, defC:0, hpC:1, rarity:"uncommon", atkSkill:11, text:"혼란공격" },
  { id:"e23", tribe:"earth", name:"조조", cost:5, type:"minion", atk:3, def:1, hp:6, atkC:-1, defC:0, hpC:1, rarity:"rare", ability:"강탈", text:"강탈" },
  { id:"e24", tribe:"earth", name:"티라노", cost:4, type:"minion", atk:2, def:1, hp:6, atkC:-1, defC:-1, hpC:1, atkSkill:10, text:"돌파공격" },
  { id:"e25", tribe:"earth", name:"대지자이언트", cost:6, type:"minion", atk:3, def:0, hp:10, atkC:-3, defC:0, hpC:3, rarity:"uncommon", ability:"보호", text:"보호" },
  { id:"e26", tribe:"earth", name:"사이클롭스", cost:6, type:"minion", atk:3, def:0, hp:8, atkC:-2, defC:0, hpC:2, rarity:"uncommon", atkSkill:5, text:"치명공격" },
  { id:"e27", tribe:"earth", name:"샌드웜", cost:5, type:"minion", atk:2, def:0, hp:6, atkC:2, defC:2, hpC:2, rarity:"uncommon", atkSkill:2, text:"관통공격" },
  { id:"e28", tribe:"earth", name:"이끼방패병", cost:1, type:"minion", atk:2, def:1, hp:1, atkC:0, defC:-1, hpC:1, text:"" },
  { id:"f1", tribe:"fire", name:"레드드래곤", cost:9, type:"minion", atk:10, def:1, hp:11, atkC:-4, defC:0, hpC:-4, rarity:"rare", ability:"면역", text:"면역" },
  { id:"f2", tribe:"fire", name:"불꽃궁수", cost:2, type:"minion", atk:5, def:0, hp:2, atkC:-3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"f3", tribe:"fire", name:"임프", cost:1, type:"minion", atk:1, def:0, hp:4, atkC:-1, defC:0, hpC:0, text:"" },
  { id:"f4", tribe:"fire", name:"고블린", cost:2, type:"minion", atk:1, def:2, hp:3, atkC:-1, defC:-1, hpC:-1, text:"" },
  { id:"f5", tribe:"fire", name:"불꽃여우", cost:2, type:"minion", atk:3, def:1, hp:2, atkC:-1, defC:-1, hpC:0, rarity:"uncommon", atkSkill:10, text:"돌파공격" },
  { id:"f6", tribe:"fire", name:"가후", cost:8, type:"minion", atk:7, def:0, hp:9, atkC:-4, defC:0, hpC:0, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"f7", tribe:"fire", name:"샐러맨더", cost:2, type:"minion", atk:4, def:0, hp:3, atkC:-4, defC:0, hpC:0, atkSkill:6, text:"흡혈공격" },
  { id:"f8", tribe:"fire", name:"용암술사", cost:4, type:"minion", atk:6, def:1, hp:5, atkC:-4, defC:0, hpC:-4, ability:"유언", text:"유언" },
  { id:"f9", tribe:"fire", name:"용암늑대", cost:2, type:"minion", atk:2, def:1, hp:2, atkC:-1, defC:-1, hpC:-1, atkSkill:3, text:"돌진공격" },
  { id:"f10", tribe:"fire", name:"헬하운드", cost:3, type:"minion", atk:4, def:0, hp:5, atkC:-4, defC:0, hpC:-4, atkSkill:4, text:"연속공격" },
  { id:"f11", tribe:"fire", name:"바바리안", cost:3, type:"minion", atk:3, def:1, hp:3, atkC:-2, defC:0, hpC:-2, atkSkill:3, text:"돌진공격" },
  { id:"f12", tribe:"fire", name:"여령기", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:-2, defC:0, hpC:0, rarity:"rare", atkSkill:5, text:"치명공격" },
  { id:"f13", tribe:"fire", name:"파이어골렘", cost:3, type:"minion", atk:4, def:2, hp:3, atkC:-2, defC:-2, hpC:0, text:"" },
  { id:"f14", tribe:"fire", name:"폭염방패병", cost:1, type:"minion", atk:1, def:0, hp:1, atkC:-1, defC:1, hpC:0, ability:"보호", text:"보호" },
  { id:"f15", tribe:"fire", name:"장비", cost:10, type:"minion", atk:10, def:2, hp:9, atkC:-5, defC:0, hpC:-5, rarity:"legendary", atkSkill:4, ability:"면역", text:"연속공격 · 면역" },
  { id:"f16", tribe:"fire", name:"미노타우로스", cost:4, type:"minion", atk:5, def:0, hp:5, atkC:-5, defC:0, hpC:0, atkSkill:4, text:"연속공격" },
  { id:"f17", tribe:"fire", name:"불의 정령", cost:4, type:"minion", atk:5, def:2, hp:5, atkC:-2, defC:-2, hpC:0, text:"" },
  { id:"f18", tribe:"fire", name:"이프리트", cost:4, type:"minion", atk:4, def:0, hp:6, atkC:-3, defC:0, hpC:-3, atkSkill:5, text:"치명공격" },
  { id:"f19", tribe:"fire", name:"케르베로스", cost:5, type:"minion", atk:6, def:0, hp:6, atkC:-4, defC:0, hpC:0, rarity:"uncommon", atkSkill:4, text:"연속공격" },
  { id:"f20", tribe:"fire", name:"데빌", cost:3, type:"minion", atk:6, def:0, hp:5, atkC:-4, defC:0, hpC:-4, atkSkill:11, text:"혼란공격" },
  { id:"f21", tribe:"fire", name:"화염창병", cost:1, type:"minion", atk:4, def:0, hp:1, atkC:-3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"f22", tribe:"fire", name:"하후돈", cost:7, type:"minion", atk:9, def:0, hp:10, atkC:-5, defC:0, hpC:0, rarity:"rare", atkSkill:6, text:"흡혈공격" },
  { id:"f23", tribe:"fire", name:"발록", cost:5, type:"minion", atk:7, def:1, hp:7, atkC:-4, defC:0, hpC:-4, rarity:"uncommon", atkSkill:6, text:"흡혈공격" },
  { id:"f24", tribe:"fire", name:"키메라", cost:6, type:"minion", atk:7, def:2, hp:7, atkC:-2, defC:-2, hpC:-2, rarity:"uncommon", atkSkill:10, text:"돌파공격" },
  { id:"f25", tribe:"fire", name:"타이폰", cost:6, type:"minion", atk:8, def:0, hp:8, atkC:-5, defC:0, hpC:0, rarity:"uncommon", atkSkill:11, text:"혼란공격" },
  { id:"f26", tribe:"fire", name:"피닉스", cost:5, type:"minion", atk:7, def:1, hp:5, atkC:-3, defC:0, hpC:-3, rarity:"uncommon", ability:"환생", text:"환생" },
  { id:"f27", tribe:"fire", name:"화염자이언트", cost:6, type:"minion", atk:7, def:2, hp:7, atkC:-5, defC:0, hpC:-5, rarity:"uncommon", atkSkill:3, text:"돌진공격" },
  { id:"n1", tribe:"wind", name:"깃털도마뱀", cost:2, type:"minion", atk:2, def:0, hp:5, atkC:-2, defC:0, hpC:0, text:"" },
  { id:"n2", tribe:"wind", name:"조운", cost:10, type:"minion", atk:8, def:2, hp:8, atkC:-1, defC:-1, hpC:-1, rarity:"legendary", atkSkill:4, ability:"면역", text:"연속공격 · 면역" },
  { id:"n3", tribe:"wind", name:"질풍술사", cost:4, type:"minion", atk:5, def:1, hp:5, atkC:-1, defC:-1, hpC:0, text:"" },
  { id:"n4", tribe:"wind", name:"픽시", cost:1, type:"minion", atk:1, def:0, hp:4, atkC:0, defC:0, hpC:-1, text:"" },
  { id:"n5", tribe:"wind", name:"구름사슴", cost:2, type:"minion", atk:3, def:1, hp:3, atkC:-1, defC:-1, hpC:0, text:"" },
  { id:"n6", tribe:"wind", name:"매사냥꾼", cost:3, type:"minion", atk:4, def:0, hp:4, atkC:-1, defC:1, hpC:0, text:"" },
  { id:"n7", tribe:"wind", name:"바람늑대", cost:2, type:"minion", atk:3, def:0, hp:3, atkC:-1, defC:0, hpC:-1, atkSkill:10, text:"돌파공격" },
  { id:"n8", tribe:"wind", name:"선풍무사", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:0, defC:0, hpC:-1, atkSkill:4, text:"연속공격" },
  { id:"n9", tribe:"wind", name:"손상향", cost:3, type:"minion", atk:3, def:0, hp:5, atkC:1, defC:0, hpC:0, rarity:"rare", atkSkill:2, text:"관통공격" },
  { id:"n10", tribe:"wind", name:"하피", cost:2, type:"minion", atk:2, def:0, hp:4, atkC:0, defC:0, hpC:-1, atkSkill:7, text:"약화공격" },
  { id:"n11", tribe:"wind", name:"그리핀", cost:3, type:"minion", atk:3, def:1, hp:3, atkC:0, defC:-1, hpC:-1, atkSkill:3, text:"돌진공격" },
  { id:"n12", tribe:"wind", name:"윈드골렘", cost:3, type:"minion", atk:4, def:0, hp:3, atkC:0, defC:0, hpC:-2, rarity:"uncommon", ability:"면역", text:"면역" },
  { id:"n13", tribe:"wind", name:"폭풍드래곤", cost:9, type:"minion", atk:9, def:1, hp:9, atkC:-1, defC:0, hpC:-1, rarity:"rare", ability:"면역", text:"면역" },
  { id:"n14", tribe:"wind", name:"폭풍창병", cost:1, type:"minion", atk:3, def:0, hp:1, atkC:-1, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"n15", tribe:"wind", name:"회오리무희", cost:5, type:"minion", atk:6, def:0, hp:7, atkC:-1, defC:0, hpC:-1, rarity:"uncommon", atkSkill:11, text:"혼란공격" },
  { id:"n16", tribe:"wind", name:"가루다", cost:4, type:"minion", atk:4, def:0, hp:4, atkC:-1, defC:0, hpC:-1, atkSkill:5, text:"치명공격" },
  { id:"n17", tribe:"wind", name:"바람의 정령", cost:4, type:"minion", atk:5, def:0, hp:5, atkC:-1, defC:0, hpC:-1, ability:"유언", text:"유언" },
  { id:"n18", tribe:"wind", name:"회오리궁수", cost:2, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:-1, atkSkill:2, text:"관통공격" },
  { id:"n19", tribe:"wind", name:"페가수스", cost:4, type:"minion", atk:4, def:2, hp:4, atkC:-2, defC:-2, hpC:-2, atkSkill:3, text:"돌진공격" },
  { id:"n20", tribe:"wind", name:"호크라이더", cost:5, type:"minion", atk:6, def:0, hp:7, atkC:-1, defC:0, hpC:-1, rarity:"uncommon", atkSkill:10, text:"돌파공격" },
  { id:"n21", tribe:"wind", name:"구름방패병", cost:1, type:"minion", atk:2, def:1, hp:1, atkC:-1, defC:0, hpC:0, text:"" },
  { id:"n23", tribe:"wind", name:"템페스트", cost:5, type:"minion", atk:4, def:1, hp:6, atkC:-1, defC:0, hpC:0, rarity:"uncommon", atkSkill:11, text:"혼란공격" },
  { id:"n24", tribe:"wind", name:"폭풍자이언트", cost:6, type:"minion", atk:7, def:0, hp:6, atkC:-1, defC:0, hpC:-1, rarity:"uncommon", atkSkill:4, text:"연속공격" },
  { id:"n25", tribe:"wind", name:"썬더버드", cost:6, type:"minion", atk:4, def:0, hp:7, atkC:-1, defC:1, hpC:-1, rarity:"uncommon", atkSkill:5, text:"치명공격" },
  { id:"n26", tribe:"wind", name:"와이번", cost:6, type:"minion", atk:8, def:0, hp:7, atkC:-1, defC:0, hpC:-1, rarity:"uncommon", atkSkill:2, text:"관통공격" },
  { id:"n27", tribe:"wind", name:"태사자", cost:7, type:"minion", atk:7, def:1, hp:7, atkC:1, defC:-1, hpC:-1, rarity:"rare", atkSkill:4, text:"연속공격" },
  { id:"n28", tribe:"wind", name:"육손", cost:8, type:"minion", atk:6, def:1, hp:8, atkC:0, defC:-1, hpC:-1, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"a1", tribe:"water", name:"관우", cost:10, type:"minion", atk:4, def:3, hp:7, atkC:-1, defC:1, hpC:-1, rarity:"legendary", atkSkill:3, ability:"강탈", text:"돌진공격 · 강탈" },
  { id:"a2", tribe:"water", name:"슬라임", cost:1, type:"minion", atk:1, def:1, hp:1, atkC:-1, defC:1, hpC:0, text:"" },
  { id:"a3", tribe:"water", name:"연못거북", cost:2, type:"minion", atk:2, def:1, hp:2, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"a4", tribe:"water", name:"피라냐", cost:2, type:"minion", atk:2, def:1, hp:2, atkC:-1, defC:1, hpC:0, text:"" },
  { id:"a5", tribe:"water", name:"나가", cost:2, type:"minion", atk:3, def:0, hp:1, atkC:-3, defC:3, hpC:0, atkSkill:7, text:"약화공격" },
  { id:"a6", tribe:"water", name:"독두꺼비", cost:2, type:"minion", atk:1, def:1, hp:3, atkC:-1, defC:1, hpC:-1, text:"" },
  { id:"a7", tribe:"water", name:"리자드맨", cost:3, type:"minion", atk:2, def:1, hp:2, atkC:0, defC:1, hpC:-1, atkSkill:3, text:"돌진공격" },
  { id:"a8", tribe:"water", name:"빙결술사", cost:4, type:"minion", atk:2, def:2, hp:1, atkC:-1, defC:1, hpC:0, atkSkill:8, text:"석화공격" },
  { id:"a9", tribe:"water", name:"전기해파리", cost:3, type:"minion", atk:2, def:1, hp:2, atkC:1, defC:1, hpC:-1, atkSkill:11, text:"혼란공격" },
  { id:"a10", tribe:"water", name:"파도창병", cost:1, type:"minion", atk:2, def:0, hp:1, atkC:-1, defC:1, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"a11", tribe:"water", name:"심해방패병", cost:1, type:"minion", atk:0, def:0, hp:1, atkC:1, defC:1, hpC:0, ability:"보호", text:"보호" },
  { id:"a12", tribe:"water", name:"머메이드", cost:3, type:"minion", atk:1, def:2, hp:1, atkC:-1, defC:1, hpC:0, atkSkill:6, text:"흡혈공격" },
  { id:"a13", tribe:"water", name:"대교", cost:3, type:"minion", atk:1, def:2, hp:2, atkC:-1, defC:1, hpC:-1, rarity:"rare", atkSkill:7, text:"약화공격" },
  { id:"a14", tribe:"water", name:"아이스드래곤", cost:9, type:"minion", atk:4, def:3, hp:7, atkC:-1, defC:1, hpC:-1, rarity:"rare", ability:"면역", text:"면역" },
  { id:"a15", tribe:"water", name:"손권", cost:4, type:"minion", atk:1, def:2, hp:2, atkC:-1, defC:1, hpC:0, rarity:"rare", ability:"강탈", text:"강탈" },
  { id:"a16", tribe:"water", name:"아이스골렘", cost:3, type:"minion", atk:3, def:1, hp:3, atkC:-2, defC:2, hpC:-2, text:"" },
  { id:"a17", tribe:"water", name:"물의 정령", cost:4, type:"minion", atk:2, def:2, hp:1, atkC:0, defC:1, hpC:0, ability:"유언", text:"유언" },
  { id:"a18", tribe:"water", name:"세이렌", cost:4, type:"minion", atk:2, def:1, hp:4, atkC:0, defC:2, hpC:-2, atkSkill:11, text:"혼란공격" },
  { id:"a19", tribe:"water", name:"켈피", cost:4, type:"minion", atk:3, def:2, hp:1, atkC:0, defC:1, hpC:0, atkSkill:10, text:"돌파공격" },
  { id:"a20", tribe:"water", name:"시서펜트", cost:6, type:"minion", atk:4, def:2, hp:4, atkC:-1, defC:1, hpC:-1, rarity:"uncommon", atkSkill:3, text:"돌진공격" },
  { id:"a22", tribe:"water", name:"강가무녀", cost:5, type:"minion", atk:4, def:2, hp:4, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"a23", tribe:"water", name:"주유", cost:8, type:"minion", atk:3, def:3, hp:3, atkC:-1, defC:1, hpC:0, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"a24", tribe:"water", name:"심해상어", cost:5, type:"minion", atk:4, def:2, hp:2, atkC:-2, defC:2, hpC:0, rarity:"uncommon", atkSkill:2, text:"관통공격" },
  { id:"a25", tribe:"water", name:"얼음궁수", cost:2, type:"minion", atk:1, def:0, hp:3, atkC:1, defC:1, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"a26", tribe:"water", name:"바다자이언트", cost:6, type:"minion", atk:5, def:2, hp:5, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"a27", tribe:"water", name:"크라켄", cost:6, type:"minion", atk:2, def:2, hp:6, atkC:-1, defC:1, hpC:0, rarity:"uncommon", atkSkill:3, text:"돌진공격" },
  { id:"a28", tribe:"water", name:"히드라", cost:5, type:"minion", atk:3, def:2, hp:2, atkC:-1, defC:1, hpC:-1, rarity:"uncommon", atkSkill:4, text:"연속공격" },
  { id:"l1", tribe:"light", name:"태양궁수", cost:2, type:"minion", atk:2, def:0, hp:2, atkC:3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"l2", tribe:"light", name:"빛나방", cost:1, type:"minion", atk:0, def:0, hp:3, atkC:1, defC:1, hpC:0, text:"" },
  { id:"l3", tribe:"light", name:"치유술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:1, hpC:1, ability:"유언", text:"유언" },
  { id:"l4", tribe:"light", name:"제갈량", cost:10, type:"minion", atk:4, def:1, hp:9, atkC:1, defC:1, hpC:1, rarity:"legendary", atkSkill:9, ability:"보호", text:"광역공격 · 보호" },
  { id:"l5", tribe:"light", name:"축복방패병", cost:1, type:"minion", atk:2, def:0, hp:1, atkC:1, defC:1, hpC:0, text:"" },
  { id:"l6", tribe:"light", name:"빛늑대", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:1, hpC:0, text:"" },
  { id:"l7", tribe:"light", name:"성녀", cost:2, type:"minion", atk:2, def:1, hp:1, atkC:0, defC:0, hpC:3, text:"" },
  { id:"l8", tribe:"light", name:"신관", cost:2, type:"minion", atk:1, def:0, hp:2, atkC:0, defC:3, hpC:0, text:"" },
  { id:"l9", tribe:"light", name:"예언자", cost:2, type:"minion", atk:3, def:0, hp:2, atkC:0, defC:1, hpC:1, text:"" },
  { id:"l10", tribe:"light", name:"황충", cost:8, type:"minion", atk:1, def:0, hp:9, atkC:3, defC:3, hpC:3, rarity:"rare", atkSkill:5, text:"치명공격" },
  { id:"l11", tribe:"light", name:"골드골렘", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:1, defC:1, hpC:1, text:"" },
  { id:"l12", tribe:"light", name:"성기사", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:0, defC:1, hpC:0, ability:"보호", text:"보호" },
  { id:"l13", tribe:"light", name:"광명창병", cost:1, type:"minion", atk:3, def:0, hp:1, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l14", tribe:"light", name:"수도사", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:0, defC:0, hpC:5, text:"" },
  { id:"l15", tribe:"light", name:"인챈터", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:2, defC:0, hpC:0, text:"" },
  { id:"l16", tribe:"light", name:"금빛사자", cost:4, type:"minion", atk:4, def:0, hp:3, atkC:1, defC:1, hpC:1, ability:"보호", text:"보호" },
  { id:"l18", tribe:"light", name:"십자군", cost:3, type:"minion", atk:2, def:1, hp:2, atkC:1, defC:0, hpC:0, atkSkill:3, text:"돌진공격" },
  { id:"l19", tribe:"light", name:"유비", cost:4, type:"minion", atk:1, def:1, hp:4, atkC:1, defC:1, hpC:1, rarity:"rare", ability:"보호", text:"보호" },
  { id:"l20", tribe:"light", name:"타이탄", cost:6, type:"minion", atk:5, def:0, hp:6, atkC:1, defC:1, hpC:1, rarity:"uncommon", ability:"보호", text:"보호" },
  { id:"l21", tribe:"light", name:"발키리", cost:5, type:"minion", atk:4, def:0, hp:4, atkC:1, defC:0, hpC:1, rarity:"uncommon", atkSkill:5, text:"치명공격" },
  { id:"l22", tribe:"light", name:"빛의 정령", cost:4, type:"minion", atk:4, def:0, hp:3, atkC:2, defC:2, hpC:2, text:"" },
  { id:"l23", tribe:"light", name:"신전기사", cost:5, type:"minion", atk:4, def:0, hp:5, atkC:1, defC:1, hpC:1, rarity:"uncommon", ability:"보호", text:"보호" },
  { id:"l24", tribe:"light", name:"유니콘", cost:5, type:"minion", atk:5, def:0, hp:6, atkC:0, defC:1, hpC:1, text:"" },
  { id:"l26", tribe:"light", name:"골드드래곤", cost:9, type:"minion", atk:7, def:1, hp:8, atkC:1, defC:1, hpC:1, rarity:"rare", ability:"면역", text:"면역" },
  { id:"l27", tribe:"light", name:"엔젤", cost:5, type:"minion", atk:4, def:0, hp:4, atkC:1, defC:1, hpC:1, rarity:"uncommon", ability:"면역", text:"면역" },
  { id:"l28", tribe:"light", name:"태양자이언트", cost:6, type:"minion", atk:5, def:0, hp:5, atkC:1, defC:1, hpC:1, rarity:"uncommon", atkSkill:4, text:"연속공격" },
  { id:"d1", tribe:"dark", name:"로그", cost:2, type:"minion", atk:4, def:0, hp:1, atkC:-4, defC:0, hpC:4, atkSkill:10, text:"돌파공격" },
  { id:"d2", tribe:"dark", name:"사마의", cost:8, type:"minion", atk:6, def:0, hp:8, atkC:-5, defC:0, hpC:5, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"d3", tribe:"dark", name:"그림자궁수", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:0, defC:1, hpC:-1, atkSkill:2, text:"관통공격" },
  { id:"d4", tribe:"dark", name:"해골나방", cost:1, type:"minion", atk:1, def:0, hp:3, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"d5", tribe:"dark", name:"고스트", cost:2, type:"minion", atk:3, def:0, hp:2, atkC:-3, defC:0, hpC:3, atkSkill:11, text:"혼란공격" },
  { id:"d6", tribe:"dark", name:"구울", cost:4, type:"minion", atk:2, def:0, hp:2, atkC:4, defC:0, hpC:4, ability:"환생", text:"환생" },
  { id:"d7", tribe:"dark", name:"여포", cost:10, type:"minion", atk:11, def:2, hp:11, atkC:-5, defC:0, hpC:-5, rarity:"legendary", atkSkill:11, ability:"환생", text:"혼란공격 · 환생" },
  { id:"d8", tribe:"dark", name:"암흑창병", cost:1, type:"minion", atk:2, def:0, hp:1, atkC:1, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"d9", tribe:"dark", name:"스켈레톤", cost:2, type:"minion", atk:3, def:0, hp:3, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"d10", tribe:"dark", name:"심연술사", cost:4, type:"minion", atk:3, def:0, hp:3, atkC:5, defC:0, hpC:5, text:"" },
  { id:"d11", tribe:"dark", name:"초선", cost:3, type:"minion", atk:2, def:0, hp:5, atkC:3, defC:0, hpC:-3, rarity:"rare", ability:"환생", text:"환생" },
  { id:"d12", tribe:"dark", name:"다크골렘", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:0, defC:3, hpC:-3, text:"" },
  { id:"d13", tribe:"dark", name:"미라", cost:3, type:"minion", atk:5, def:0, hp:5, atkC:-4, defC:0, hpC:-4, ability:"환생", text:"환생" },
  { id:"d14", tribe:"dark", name:"서큐버스", cost:6, type:"minion", atk:5, def:0, hp:6, atkC:3, defC:0, hpC:3, rarity:"uncommon", atkSkill:6, text:"흡혈공격" },
  { id:"d15", tribe:"dark", name:"나이트메어", cost:3, type:"minion", atk:6, def:0, hp:6, atkC:-5, defC:0, hpC:-5, atkSkill:11, text:"혼란공격" },
  { id:"d16", tribe:"dark", name:"듀라한", cost:3, type:"minion", atk:3, def:0, hp:2, atkC:-3, defC:0, hpC:3, atkSkill:4, text:"연속공격" },
  { id:"d17", tribe:"dark", name:"저주방패병", cost:1, type:"minion", atk:1, def:1, hp:1, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d18", tribe:"dark", name:"장료", cost:6, type:"minion", atk:6, def:1, hp:7, atkC:5, defC:0, hpC:-5, rarity:"rare", atkSkill:10, text:"돌파공격" },
  { id:"d20", tribe:"dark", name:"가고일", cost:5, type:"minion", atk:6, def:0, hp:5, atkC:-3, defC:3, hpC:-3, rarity:"uncommon", ability:"보호", text:"보호" },
  { id:"d21", tribe:"dark", name:"네크로맨서", cost:5, type:"minion", atk:4, def:0, hp:4, atkC:3, defC:0, hpC:3, rarity:"uncommon", ability:"유언", text:"유언" },
  { id:"d22", tribe:"dark", name:"만티코어", cost:5, type:"minion", atk:6, def:0, hp:5, atkC:-3, defC:3, hpC:0, rarity:"uncommon", atkSkill:2, text:"관통공격" },
  { id:"d23", tribe:"dark", name:"리치", cost:7, type:"minion", atk:6, def:1, hp:7, atkC:-5, defC:0, hpC:5, rarity:"uncommon", ability:"환생", text:"환생" },
  { id:"d24", tribe:"dark", name:"암흑의 정령", cost:4, type:"minion", atk:5, def:0, hp:4, atkC:-3, defC:3, hpC:0, text:"" },
  { id:"d25", tribe:"dark", name:"뱀파이어", cost:5, type:"minion", atk:5, def:0, hp:5, atkC:0, defC:3, hpC:-3, rarity:"uncommon", atkSkill:6, text:"흡혈공격" },
  { id:"d26", tribe:"dark", name:"본맘모스", cost:6, type:"minion", atk:4, def:2, hp:5, atkC:3, defC:0, hpC:-3, rarity:"uncommon", atkSkill:3, text:"돌진공격" },
  { id:"d27", tribe:"dark", name:"블랙드래곤", cost:9, type:"minion", atk:4, def:0, hp:11, atkC:0, defC:4, hpC:-4, rarity:"rare", atkSkill:5, text:"치명공격" },
  { id:"d28", tribe:"dark", name:"암흑자이언트", cost:6, type:"minion", atk:6, def:0, hp:7, atkC:5, defC:0, hpC:-5, rarity:"uncommon", ability:"강탈", text:"강탈" },
  { id:"e11", tribe:"earth", name:"숲요정", cost:3, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:1, ability:"출전", text:"출전" },
  { id:"f28", tribe:"fire", name:"불꽃요정", cost:3, type:"minion", atk:4, def:0, hp:4, atkC:-2, defC:2, hpC:-2, text:"" },
  { id:"n22", tribe:"wind", name:"바람요정", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:-1, defC:0, hpC:-1, ability:"출전", text:"출전" },
  { id:"a21", tribe:"water", name:"물의요정", cost:3, type:"minion", atk:2, def:1, hp:1, atkC:-2, defC:2, hpC:0, ability:"출전", text:"출전" },
  { id:"l25", tribe:"light", name:"광휘요정", cost:3, type:"minion", atk:3, def:0, hp:2, atkC:1, defC:0, hpC:1, ability:"출전", text:"출전" },
  { id:"d19", tribe:"dark", name:"그림자요정", cost:3, type:"minion", atk:4, def:0, hp:2, atkC:-4, defC:0, hpC:4, ability:"출전", text:"출전" },
  { id:"l17", tribe:"light", name:"황월영", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:1, hpC:1, rarity:"rare", ability:"보호", text:"보호" },
  // --- tokens ---
  { id:"e40", tribe:"earth", name:"섬의파편", cost:1, type:"minion", token:true, atk:1, def:0, hp:2, atkC:0, defC:0, hpC:0, rarity:"common", text:"토큰" },
  // --- spells / items ---
{ id:"fs1", tribe:"fire", name:"화염화살", cost:2, type:"spell", rarity:"common", text:"유닛 하나 체-3", spell:{ type:"dmg", value:3, target:"any_minion" } },
  { id:"fs2", tribe:"fire", name:"화염폭풍", cost:4, type:"spell", rarity:"common", text:"적 전체 체-2, 코인-1", spell:{ type:"aoe_pack", enemy:2, coin:-1 } },
  { id:"fs3", tribe:"fire", name:"화염구", cost:3, type:"spell", rarity:"common", text:"유닛 하나 체-5, 코인-1", spell:{ type:"dmg", value:5, target:"any_minion", coin:-1 } },
  { id:"fs4", tribe:"fire", name:"화염탄", cost:4, type:"spell", rarity:"uncommon", text:"적 하나 파괴", spell:{ type:"kill", target:"enemy_minion" } },
  { id:"fs5", tribe:"fire", name:"폭염", cost:2, type:"spell", rarity:"common", text:"아군 전체 체-2, 드로우2", spell:{ type:"draw_ex", ownAllHp:2, draw:2 } },
  { id:"ns1", tribe:"wind", name:"바람망토", cost:2, type:"spell", rarity:"common", text:"손패 유닛 전체 보호 부여", spell:{ type:"grant_kw", where:"hand", ability:"보호", kw:"shield" } },
  { id:"ns2", tribe:"wind", name:"진공베기", cost:3, type:"spell", rarity:"common", text:"코인 있는 적 하나 파괴", spell:{ type:"kill_if", anyCoin:true } },
  { id:"ns3", tribe:"wind", name:"상승기류", cost:5, type:"spell", rarity:"rare", text:"드로우4", spell:{ type:"draw", value:4 } },
  { id:"as1", tribe:"water", name:"냉기화살", cost:1, type:"spell", rarity:"common", text:"적 하나 체-2, 다음 턴 공격 불가", spell:{ type:"dmg", value:2, target:"enemy_minion", skipAttack:true } },
  { id:"as2", tribe:"water", name:"물거울", cost:6, type:"spell", rarity:"rare", text:"아군 하나 복사, 보호 부여", spell:{ type:"copy_own", ability:"보호", kw:"shield" } },
  { id:"as3", tribe:"water", name:"익사", cost:3, type:"spell", rarity:"common", text:"5코 이하 적 하나 파괴", spell:{ type:"kill_if", maxCost:5 } },
  { id:"es1", tribe:"earth", name:"거인의봉인", cost:3, type:"spell", rarity:"uncommon", text:"공7 이상 적 하나 파괴", spell:{ type:"kill_if", minAtk:7 } },
  { id:"ns4", tribe:"wind", name:"떠오르는섬", cost:3, type:"spell", rarity:"uncommon", text:"내 전장 빈칸 수만큼 섬의파편(1/0/2) 소환", spell:{ type:"summon_islands" } },
  { id:"es2", tribe:"earth", name:"어스퀘이크", cost:6, type:"spell", rarity:"rare", text:"적 전체 체력을 내 최대마나 절반만큼 깎음", spell:{ type:"earthquake" } },
  { id:"es3", tribe:"earth", name:"샌드트랩", cost:4, type:"spell", rarity:"uncommon", text:"내 전장 빈칸 수만큼 적 체-3", spell:{ type:"sandtrap" } },
  { id:"es4", tribe:"earth", name:"미로생성", cost:3, type:"spell", rarity:"common", text:"아군 전체 복수 부여", spell:{ type:"grant_kw", ability:"복수", kw:"revenge" } },
  { id:"es5", tribe:"earth", name:"땅굴숨기", cost:2, type:"spell", rarity:"common", text:"내 유닛 수만큼 드로우", spell:{ type:"draw_ex", drawBoard:true } },
  { id:"ns5", tribe:"wind", name:"토네이도", cost:4, type:"spell", rarity:"uncommon", text:"2코 이하 유닛 전체 파괴", spell:{ type:"tornado" } },
  { id:"es6", tribe:"earth", name:"낙석", cost:2, type:"spell", rarity:"common", text:"유닛 전체 체-2", spell:{ type:"aoe_pack", all:2 } },
  { id:"es7", tribe:"earth", name:"모래지옥", cost:4, type:"spell", rarity:"common", text:"적 전체 공·방·체-2", spell:{ type:"sandhell", value:2 } },
  { id:"ls1", tribe:"light", name:"치유의빛", cost:2, type:"spell", rarity:"common", text:"아군 전체 체+3", spell:{ type:"buff_all", hp:3 } },
  { id:"ls2", tribe:"light", name:"축복", cost:7, type:"spell", rarity:"rare", text:"아군 하나 공·체+8, 연속공격 부여", spell:{ type:"grant_extra", atk:8, hp:8 } },
  { id:"ls3", tribe:"light", name:"정화", cost:3, type:"spell", rarity:"common", text:"유닛 하나 공=0 방=0 체=7", spell:{ type:"set_one", atk:0, def:0, hp:7, target:"any_minion" } },
  { id:"ds1", tribe:"dark", name:"파멸", cost:3, type:"spell", rarity:"common", text:"공4 이상 적 하나 파괴", spell:{ type:"kill_if", minAtk:4 } },
  { id:"coin", name:"동전", cost:0, type:"spell", text:"이번 턴 마나 +1", spell:{ type:"mana", value:1 }, token:true },
  { id:"ei1", tribe:"earth", name:"골렘의심장", cost:1, type:"item", rarity:"common", atk:0, def:0, hp:2, ability:"보호", text:"보호 부여" },
  { id:"ei2", tribe:"earth", name:"돌도끼", cost:2, type:"item", rarity:"common", atk:3, def:-1, hp:0, atkSkill:2, text:"관통공격 부여" },
  { id:"ei3", tribe:"earth", name:"바실리스크눈", cost:3, type:"item", rarity:"common", ability:"면역", atk:2, def:0, hp:2, text:"면역 부여" },
  { id:"ei4", tribe:"earth", name:"노름바위", cost:4, type:"item", rarity:"common", atk:2, def:0, hp:2, text:"이 유닛 코인 수만큼 공·체+" },
  { id:"ei5", tribe:"earth", name:"모래시계", cost:5, type:"item", rarity:"uncommon", atk:2, def:1, hp:2, ability:"환생", text:"환생 부여" },
  { id:"ei6", tribe:"earth", name:"대지의팔찌", cost:7, type:"item", rarity:"uncommon", atk:3, def:2, hp:2, atkSkill:3, text:"돌진공격 부여" },
  { id:"fi1", tribe:"fire", name:"불꽃검", cost:1, type:"item", rarity:"common", atk:2, def:0, hp:0, text:"" },
  { id:"fi2", tribe:"fire", name:"불꽃도끼", cost:2, type:"item", rarity:"common", atk:3, def:0, hp:0, text:"" },
  { id:"fi3", tribe:"fire", name:"불붙은건틀렛", cost:3, type:"item", rarity:"common", atk:4, def:0, hp:1, text:"" },
  { id:"fi4", tribe:"fire", name:"피닉스깃털", cost:5, type:"item", rarity:"common", atk:2, def:0, hp:3, ability:"환생", text:"환생 부여" },
  { id:"fi5", tribe:"fire", name:"도박불꽃반지", cost:6, type:"item", rarity:"uncommon", atk:5, def:1, hp:5, atkSkill:4, text:"연속공격 부여. 코인=5" },
  { id:"fi6", tribe:"fire", name:"분노의해머", cost:7, type:"item", rarity:"uncommon", atk:6, def:0, hp:2, atkSkill:9, text:"광역공격 부여" },
  { id:"ni1", tribe:"wind", name:"요정의부츠", cost:1, type:"item", rarity:"common", atk:0, def:1, hp:1, text:"" },
  { id:"ni2", tribe:"wind", name:"올빼미의눈", cost:2, type:"item", rarity:"common", atk:2, def:1, hp:1, text:"" },
  { id:"ni3", tribe:"wind", name:"페어리소드", cost:3, type:"item", rarity:"common", atk:3, def:0, hp:2, text:"" },
  { id:"ni4", tribe:"wind", name:"도둑바람", cost:2, type:"item", rarity:"uncommon", atk:0, def:0, hp:0, text:"코인=0" },
  { id:"ni5", tribe:"wind", name:"하피의손톱", cost:5, type:"item", rarity:"common", atk:3, def:0, hp:3, atkSkill:5, text:"치명공격 부여" },
  { id:"ni6", tribe:"wind", name:"폭풍의구슬", cost:7, type:"item", rarity:"uncommon", atk:5, def:0, hp:2, atkSkill:9, text:"광역공격 부여" },
  { id:"ai1", tribe:"water", name:"조개방패", cost:2, type:"item", rarity:"common", atk:0, def:2, hp:0, text:"" },
  { id:"ai2", tribe:"water", name:"얼음창", cost:2, type:"item", rarity:"common", atk:2, def:1, hp:0, text:"" },
  { id:"ai3", tribe:"water", name:"상어의턱뼈", cost:3, type:"item", rarity:"common", atk:2, def:0, hp:1, atkSkill:6, text:"흡혈공격 부여" },
  { id:"ai4", tribe:"water", name:"진주방패", cost:3, type:"item", rarity:"common", atk:0, def:2, hp:0, text:"이 유닛 코인 수만큼 방+" },
  { id:"ai5", tribe:"water", name:"산호검", cost:5, type:"item", rarity:"uncommon", atk:3, def:2, hp:2, text:"" },
  { id:"ai6", tribe:"water", name:"인어의하프", cost:7, type:"item", rarity:"uncommon", atk:4, def:1, hp:4, atkSkill:11, text:"혼란공격 부여" },
  { id:"li1", tribe:"light", name:"소생초", cost:1, type:"item", rarity:"common", atk:0, def:0, hp:2, text:"" },
  { id:"li2", tribe:"light", name:"별목걸이", cost:2, type:"item", rarity:"common", atk:0, def:0, hp:2, ability:"보호", text:"보호 부여" },
  { id:"li3", tribe:"light", name:"성스러운주화", cost:2, type:"item", rarity:"uncommon", atk:0, def:0, hp:0, text:"코인확률+20%" },
  { id:"li4", tribe:"light", name:"환상의거울", cost:3, type:"item", rarity:"common", atk:0, def:1, hp:1, ability:"보호", text:"보호 부여" },
  { id:"li5", tribe:"light", name:"아이언실드", cost:5, type:"item", rarity:"common", atk:0, def:3, hp:1, ability:"보호", text:"보호 부여" },
  { id:"li6", tribe:"light", name:"블레스트아머", cost:7, type:"item", rarity:"uncommon", atk:1, def:3, hp:3, ability:"환생", text:"환생 부여" },
  { id:"di1", tribe:"dark", name:"저주의인형", cost:1, type:"item", rarity:"common", atk:1, def:0, hp:0, atkSkill:7, text:"약화공격 부여" },
  { id:"di2", tribe:"dark", name:"피의망토", cost:2, type:"item", rarity:"common", atk:2, def:0, hp:0, atkSkill:6, text:"흡혈공격 부여" },
  { id:"di3", tribe:"dark", name:"흑마법서", cost:3, type:"item", rarity:"common", atk:2, def:0, hp:2, ability:"강탈", text:"강탈 부여" },
  { id:"di4", tribe:"dark", name:"조작된주화", cost:3, type:"item", rarity:"uncommon", atk:0, def:0, hp:0, text:"코인을 골드코인으로 변경" },
  { id:"di5", tribe:"dark", name:"사신의낫", cost:5, type:"item", rarity:"common", atk:5, def:0, hp:2, text:"" },
  { id:"di6", tribe:"dark", name:"다크아머", cost:7, type:"item", rarity:"uncommon", atk:1, def:3, hp:2, ability:"보호", text:"보호 부여" },
  { id:"ns6", tribe:"wind", name:"바람방패", cost:2, type:"spell", rarity:"common", text:"아군 하나 공·방·체+1", spell:{ type:"buff", target:"own_minion", atk:1, def:1, hp:1 } },
  { id:"ds2", tribe:"dark", name:"굶주림", cost:2, type:"spell", rarity:"common", text:"아군 하나 파괴, 드로우2", spell:{ type:"draw_ex", sacOwn:true, draw:2 } },
  { id:"as4", tribe:"water", name:"수정호수", cost:4, type:"spell", rarity:"common", text:"드로우2, 적 전체 방-1", spell:{ type:"draw_ex", draw:2, enemyDef:-1 } },
  { id:"as5", tribe:"water", name:"얼음방패", cost:2, type:"spell", rarity:"common", text:"아군 하나 방+2", spell:{ type:"buff", target:"own_minion", def:2 } },
  { id:"ls4", tribe:"light", name:"성역축복", cost:1, type:"spell", rarity:"common", text:"이번 턴 코인확률+50%", spell:{ type:"coin_luck", value:0.75 } },
  { id:"ls5", tribe:"light", name:"수호의빛", cost:4, type:"spell", rarity:"uncommon", text:"아군 전체 보호 부여", spell:{ type:"grant_kw", ability:"보호", kw:"shield" } },
  { id:"es8", tribe:"earth", name:"거대화", cost:1, type:"spell", rarity:"common", text:"유닛 하나 체+4", spell:{ type:"buff", target:"any_minion", hp:4 } },
  { id:"ls6", tribe:"light", name:"성벽가호", cost:5, type:"spell", rarity:"uncommon", text:"유닛 하나 방+2 체+8", spell:{ type:"buff", target:"any_minion", def:2, hp:8 } },
  { id:"as6", tribe:"water", name:"눈보라", cost:5, type:"spell", rarity:"uncommon", text:"적 전체 체-2, 다음 턴 공격 불가", spell:{ type:"aoe_pack", enemy:2, skipAttack:true } },
  { id:"ns7", tribe:"wind", name:"한줄기바람", cost:1, type:"spell", rarity:"common", text:"적 하나 체-1, 드로우1", spell:{ type:"draw_ex", enemyDmg:1, draw:1 } },
  { id:"as7", tribe:"water", name:"인어의노래", cost:2, type:"spell", rarity:"common", text:"유닛 하나 공=1, 코인=0", spell:{ type:"set_one", atk:1, coinZero:true, target:"any_minion" } },
  { id:"ls7", tribe:"light", name:"빛의환영", cost:2, type:"spell", rarity:"common", text:"적 전체 체-1, 아군 전체 체+1", spell:{ type:"aoe_pack", enemy:1, ownHp:1 } },
  { id:"as8", tribe:"water", name:"개구리변신", cost:4, type:"spell", rarity:"uncommon", text:"적 하나 공=1 체=1", spell:{ type:"set_one", atk:1, hp:1, target:"enemy_minion" } },
  { id:"ns8", tribe:"wind", name:"폭풍우", cost:4, type:"spell", rarity:"common", text:"적 전체 체-2, 코인-1", spell:{ type:"aoe_pack", enemy:2, coin:-1 } },
  { id:"fs6", tribe:"fire", name:"광분", cost:1, type:"spell", rarity:"common", text:"다음 턴 내 마나+3", spell:{ type:"mana_next", value:3 } },
  { id:"fs7", tribe:"fire", name:"화염방패", cost:6, type:"spell", rarity:"uncommon", text:"아군 하나 방+3, 보호 부여", spell:{ type:"buff", target:"own_minion", def:3, kws:["shield"], ability:"보호" } },
  { id:"ls8", tribe:"light", name:"헌금", cost:3, type:"spell", rarity:"common", text:"드로우2. 이번 턴 유닛을 낼 수 없음", spell:{ type:"draw_ex", draw:2, noPlayMinion:true } },
  { id:"ds3", tribe:"dark", name:"헬게이트", cost:4, type:"spell", rarity:"common", text:"유닛 전체 체-3", spell:{ type:"aoe_pack", all:3 } },
  { id:"ds4", tribe:"dark", name:"불길한예감", cost:2, type:"spell", rarity:"uncommon", text:"유닛 하나 코인 블랙. 공·방·체+3", spell:{ type:"own_black_buff", target:"any_minion", atk:3, def:3, hp:3 } },
  { id:"ds5", tribe:"dark", name:"블랙홀", cost:7, type:"spell", rarity:"rare", text:"유닛 전체 파괴, 아군 최대마나-3", spell:{ type:"wipe_all", maxMana:-3 } },
  { id:"ds6", tribe:"dark", name:"해골던지기", cost:3, type:"spell", rarity:"common", text:"공4 이하 적 하나 파괴", spell:{ type:"kill_if", maxAtk:4 } },
  { id:"ds7", tribe:"dark", name:"전염병", cost:4, type:"spell", rarity:"common", text:"4코 이상 유닛 전체 공=1 체=1", spell:{ type:"plague", minCost:4 } },
  { id:"ds8", tribe:"dark", name:"13시의저주", cost:1, type:"spell", rarity:"uncommon", text:"유닛 하나 코인=0", spell:{ type:"set_one", coinZero:true, target:"any_minion" } },
  { id:"fs8", tribe:"fire", name:"메테오", cost:7, type:"spell", rarity:"rare", text:"적 전체 체-4, 코인-1", spell:{ type:"aoe_pack", enemy:4, coin:-1 } }
];
const SPELL_SCHOOL = { fire:"염술", wind:"풍술", water:"물술", light:"성술", dark:"암술", earth:"지술" };
const CARD_RACE = {
  "a1":"무장",
  "a2":"정령",
  "a3":"짐승",
  "a4":"짐승",
  "a5":"짐승",
  "a6":"짐승",
  "a7":"용족",
  "a8":"인간",
  "a9":"정령",
  "a10":"정령",
  "a11":"정령",
  "a12":"짐승",
  "a13":"무장",
  "a14":"용족",
  "a15":"무장",
  "a16":"골렘",
  "a17":"정령",
  "a18":"짐승",
  "a19":"정령",
  "a20":"용족",
  "a21":"정령",
  "a22":"인간",
  "a23":"무장",
  "a24":"골렘",
  "a25":"정령",
  "a26":"거인",
  "a27":"짐승",
  "a28":"짐승",
  "d1":"인간",
  "d2":"무장",
  "d3":"언데드",
  "d4":"언데드",
  "d5":"언데드",
  "d6":"언데드",
  "d7":"무장",
  "d8":"정령",
  "d9":"언데드",
  "d10":"인간",
  "d11":"무장",
  "d12":"골렘",
  "d13":"언데드",
  "d14":"악마",
  "d15":"악마",
  "d16":"언데드",
  "d17":"골렘",
  "d18":"무장",
  "d19":"정령",
  "d20":"골렘",
  "d21":"언데드",
  "d22":"짐승",
  "d23":"언데드",
  "d24":"정령",
  "d25":"언데드",
  "d26":"언데드",
  "d27":"용족",
  "d28":"거인",
  "e1":"짐승",
  "e2":"인간",
  "e3":"용족",
  "e4":"정령",
  "e5":"인간",
  "e6":"정령",
  "e7":"골렘",
  "e8":"정령",
  "e9":"짐승",
  "e10":"인간",
  "e11":"정령",
  "e12":"골렘",
  "e13":"무장",
  "e14":"무장",
  "e15":"골렘",
  "e16":"짐승",
  "e17":"골렘",
  "e18":"정령",
  "e19":"무장",
  "e20":"골렘",
  "e21":"골렘",
  "e22":"골렘",
  "e23":"무장",
  "e24":"짐승",
  "e25":"거인",
  "e26":"골렘",
  "e27":"짐승",
  "e28":"정령",
  "e40":"토큰",
  "f1":"용족",
  "f2":"정령",
  "f3":"악마",
  "f4":"짐승",
  "f5":"정령",
  "f6":"무장",
  "f7":"짐승",
  "f8":"인간",
  "f9":"짐승",
  "f10":"악마",
  "f11":"인간",
  "f12":"무장",
  "f13":"골렘",
  "f14":"골렘",
  "f15":"무장",
  "f16":"짐승",
  "f17":"정령",
  "f18":"정령",
  "f19":"짐승",
  "f20":"악마",
  "f21":"골렘",
  "f22":"무장",
  "f23":"악마",
  "f24":"짐승",
  "f25":"악마",
  "f26":"정령",
  "f27":"거인",
  "f28":"정령",
  "l1":"정령",
  "l2":"짐승",
  "l3":"인간",
  "l4":"무장",
  "l5":"정령",
  "l6":"정령",
  "l7":"인간",
  "l8":"인간",
  "l9":"인간",
  "l10":"무장",
  "l11":"골렘",
  "l12":"인간",
  "l13":"정령",
  "l14":"인간",
  "l15":"인간",
  "l16":"짐승",
  "l17":"무장",
  "l18":"인간",
  "l19":"무장",
  "l20":"거인",
  "l21":"인간",
  "l22":"정령",
  "l23":"정령",
  "l24":"짐승",
  "l25":"정령",
  "l26":"용족",
  "l27":"정령",
  "l28":"거인",
  "n1":"용족",
  "n2":"무장",
  "n3":"정령",
  "n4":"정령",
  "n5":"정령",
  "n6":"인간",
  "n7":"정령",
  "n8":"인간",
  "n9":"무장",
  "n10":"짐승",
  "n11":"짐승",
  "n12":"골렘",
  "n13":"용족",
  "n14":"정령",
  "n15":"정령",
  "n16":"짐승",
  "n17":"정령",
  "n18":"정령",
  "n19":"짐승",
  "n20":"인간",
  "n21":"정령",
  "n22":"정령",
  "n23":"정령",
  "n24":"거인",
  "n25":"짐승",
  "n26":"용족",
  "n27":"무장",
  "n28":"무장",
};;
function parseCoin(v) {
  if (v == null || v === "") return 0;
  if (typeof v === "number" && isFinite(v)) return Math.max(-5, Math.min(5, v | 0));
  const s = String(v).trim();
  const neg = /^-/.test(s) || /−/.test(s) || /-\s*c/i.test(s);
  const nums = s.replace(/[xX×*]/g, " ").match(/-?\d+/g);
  if (!nums) return 0;
  let n = parseInt(nums[nums.length - 1], 10);
  if (/^-\d+$/.test(s)) n = parseInt(s, 10);
  if (neg && n > 0) n = -n;
  if (!isFinite(n)) return 0;
  return Math.max(-5, Math.min(5, n));
}
const FOCUS_X = {
  e2:0.58, e11:0.78, e15:0.70, e16:0.72, e5:0.42, e12:0.38,
  e3:0.40, e20:0.35, f2:0.70, f4:0.45, f10:0.55, f17:0.40,
  n2:0.55, n11:0.45, a1:0.62, a2:0.68, a6:0.55, a10:0.50, a17:0.60
};
const DECK_FRAMES = {
  earth: "assets/img/frames/unit/deck_earth_unit_common_frame.png",
  fire: "assets/img/frames/unit/deck_fire_unit_common_frame.png",
  wind: "assets/img/frames/unit/deck_wind_unit_common_frame.png",
  water: "assets/img/frames/unit/deck_water_unit_common_frame.png",
  light: "assets/img/frames/unit/deck_light_unit_common_frame.png",
  dark: "assets/img/frames/unit/deck_dark_unit_common_frame.png",
  metal: "assets/img/frames/unit/deck_earth_unit_common_frame.png"
};
const SPELL_FRAMES = {
  earth: "assets/img/frames/unit/deck_earth_unit_common_frame.png",
  fire: "assets/img/frames/unit/deck_fire_unit_common_frame.png",
  wind: "assets/img/frames/unit/deck_wind_unit_common_frame.png",
  water: "assets/img/frames/unit/deck_water_unit_common_frame.png",
  light: "assets/img/frames/unit/deck_light_unit_common_frame.png",
  dark: "assets/img/frames/unit/deck_dark_unit_common_frame.png",
  metal: "assets/img/frames/unit/deck_earth_unit_common_frame.png"
};
const BADGES = {
  'mana': "assets/img/badges/mana.svg",
  'atk': "assets/img/badges/atk.svg",
  'def': "assets/img/badges/def.svg",
  'hp': "assets/img/badges/hp.svg",
};
const CARD_FACE = {"e1": "assets/img/faces/e1.jpg", "e2": "assets/img/faces/e2.jpg", "e3": "assets/img/faces/e3.jpg", "e4": "assets/img/faces/e4.jpg", "e5": "assets/img/faces/e5.jpg", "e6": "assets/img/faces/e6.jpg", "e7": "assets/img/faces/e7.jpg", "e8": "assets/img/faces/e8.jpg", "e9": "assets/img/faces/e9.jpg", "e10": "assets/img/faces/e10.jpg", "e11": "assets/img/faces/e11.jpg", "e12": "assets/img/faces/e12.jpg", "e13": "assets/img/faces/e13.jpg", "e14": "assets/img/faces/e14.jpg", "e15": "assets/img/faces/e15.jpg", "e16": "assets/img/faces/e16.jpg", "e17": "assets/img/faces/e17.jpg", "e18": "assets/img/faces/e18.jpg", "e19": "assets/img/faces/e19.jpg", "e20": "assets/img/faces/e20.jpg", "f1": "assets/img/faces/f1.jpg", "f2": "assets/img/faces/f2.jpg", "f3": "assets/img/faces/f3.jpg", "f4": "assets/img/faces/f4.jpg", "f5": "assets/img/faces/f5.jpg", "f6": "assets/img/faces/f6.jpg", "f7": "assets/img/faces/f7.jpg", "f8": "assets/img/faces/f8.jpg", "f9": "assets/img/faces/f9.jpg", "f10": "assets/img/faces/f10.jpg", "f11": "assets/img/faces/f11.jpg", "f12": "assets/img/faces/f12.jpg", "f13": "assets/img/faces/f13.jpg", "f14": "assets/img/faces/f14.jpg", "f15": "assets/img/faces/f15.jpg", "f16": "assets/img/faces/f16.jpg", "f17": "assets/img/faces/f17.jpg", "f18": "assets/img/faces/f18.jpg", "f19": "assets/img/faces/f19.jpg", "f20": "assets/img/faces/f20.jpg", "n1": "assets/img/faces/n1.jpg", "n2": "assets/img/faces/n2.jpg", "n3": "assets/img/faces/n3.jpg", "n4": "assets/img/faces/n4.jpg", "n5": "assets/img/faces/n5.jpg", "n6": "assets/img/faces/n6.jpg", "n7": "assets/img/faces/n7.jpg", "n8": "assets/img/faces/n8.jpg", "n9": "assets/img/faces/n9.jpg", "n10": "assets/img/faces/n10.jpg", "n11": "assets/img/faces/n11.jpg", "n12": "assets/img/faces/n12.jpg", "n13": "assets/img/faces/n13.jpg", "n14": "assets/img/faces/n14.jpg", "n15": "assets/img/faces/n15.jpg", "n16": "assets/img/faces/n16.jpg", "n17": "assets/img/faces/n17.jpg", "n18": "assets/img/faces/n18.jpg", "n19": "assets/img/faces/n19.jpg", "n20": "assets/img/faces/n20.jpg", "a1": "assets/img/faces/a1.jpg", "a2": "assets/img/faces/a2.jpg", "a3": "assets/img/faces/a3.jpg", "a4": "assets/img/faces/a4.jpg", "a5": "assets/img/faces/a5.jpg", "a6": "assets/img/faces/a6.jpg", "a7": "assets/img/faces/a7.jpg", "a8": "assets/img/faces/a8.jpg", "a9": "assets/img/faces/a9.jpg", "a10": "assets/img/faces/a10.jpg", "a11": "assets/img/faces/a11.jpg", "a12": "assets/img/faces/a12.jpg", "a13": "assets/img/faces/a13.jpg", "a14": "assets/img/faces/a14.jpg", "a15": "assets/img/faces/a15.jpg", "a16": "assets/img/faces/a16.jpg", "a17": "assets/img/faces/a17.jpg", "a18": "assets/img/faces/a18.jpg", "a19": "assets/img/faces/a19.jpg", "a20": "assets/img/faces/a20.jpg", "coin": "assets/img/faces/coin.jpg", "e40": "assets/img/faces/e40.jpg"};
const RARITY_FRAMES = {
  "earth|minion|common": "assets/img/frames/unit/deck_earth_unit_common_frame.png",
  "earth|spell|common": "assets/img/frames/unit/deck_earth_unit_common_frame.png",
  "earth|item|common": "assets/img/frames/item/deck_earth_item_common_frame.png",
  "earth|minion|uncommon": "assets/img/frames/unit/deck_earth_unit_uncommon_frame.png",
  "earth|spell|uncommon": "assets/img/frames/unit/deck_earth_unit_uncommon_frame.png",
  "earth|item|uncommon": "assets/img/frames/item/deck_earth_item_uncommon_frame.png",
  "earth|minion|rare": "assets/img/frames/unit/deck_earth_unit_rare_frame.png",
  "earth|spell|rare": "assets/img/frames/unit/deck_earth_unit_rare_frame.png",
  "earth|item|rare": "assets/img/frames/item/deck_earth_item_rare_frame.png",
  "earth|minion|legendary": "assets/img/frames/unit/deck_earth_unit_legendary_frame.png",
  "earth|spell|legendary": "assets/img/frames/unit/deck_earth_unit_legendary_frame.png",
  "earth|item|legendary": "assets/img/frames/item/deck_earth_item_legendary_frame.png",
  "fire|minion|common": "assets/img/frames/unit/deck_fire_unit_common_frame.png",
  "fire|spell|common": "assets/img/frames/unit/deck_fire_unit_common_frame.png",
  "fire|item|common": "assets/img/frames/item/deck_fire_item_common_frame.png",
  "fire|minion|uncommon": "assets/img/frames/unit/deck_fire_unit_uncommon_frame.png",
  "fire|spell|uncommon": "assets/img/frames/unit/deck_fire_unit_uncommon_frame.png",
  "fire|item|uncommon": "assets/img/frames/item/deck_fire_item_uncommon_frame.png",
  "fire|minion|rare": "assets/img/frames/unit/deck_fire_unit_rare_frame.png",
  "fire|spell|rare": "assets/img/frames/unit/deck_fire_unit_rare_frame.png",
  "fire|item|rare": "assets/img/frames/item/deck_fire_item_rare_frame.png",
  "fire|minion|legendary": "assets/img/frames/unit/deck_fire_unit_legendary_frame.png",
  "fire|spell|legendary": "assets/img/frames/unit/deck_fire_unit_legendary_frame.png",
  "fire|item|legendary": "assets/img/frames/item/deck_fire_item_legendary_frame.png",
  "wind|minion|common": "assets/img/frames/unit/deck_wind_unit_common_frame.png",
  "wind|spell|common": "assets/img/frames/unit/deck_wind_unit_common_frame.png",
  "wind|item|common": "assets/img/frames/item/deck_wind_item_common_frame.png",
  "wind|minion|uncommon": "assets/img/frames/unit/deck_wind_unit_uncommon_frame.png",
  "wind|spell|uncommon": "assets/img/frames/unit/deck_wind_unit_uncommon_frame.png",
  "wind|item|uncommon": "assets/img/frames/item/deck_wind_item_uncommon_frame.png",
  "wind|minion|rare": "assets/img/frames/unit/deck_wind_unit_rare_frame.png",
  "wind|spell|rare": "assets/img/frames/unit/deck_wind_unit_rare_frame.png",
  "wind|item|rare": "assets/img/frames/item/deck_wind_item_rare_frame.png",
  "wind|minion|legendary": "assets/img/frames/unit/deck_wind_unit_legendary_frame.png",
  "wind|spell|legendary": "assets/img/frames/unit/deck_wind_unit_legendary_frame.png",
  "wind|item|legendary": "assets/img/frames/item/deck_wind_item_legendary_frame.png",
  "water|minion|common": "assets/img/frames/unit/deck_water_unit_common_frame.png",
  "water|spell|common": "assets/img/frames/unit/deck_water_unit_common_frame.png",
  "water|item|common": "assets/img/frames/item/deck_water_item_common_frame.png",
  "water|minion|uncommon": "assets/img/frames/unit/deck_water_unit_uncommon_frame.png",
  "water|spell|uncommon": "assets/img/frames/unit/deck_water_unit_uncommon_frame.png",
  "water|item|uncommon": "assets/img/frames/item/deck_water_item_uncommon_frame.png",
  "water|minion|rare": "assets/img/frames/unit/deck_water_unit_rare_frame.png",
  "water|spell|rare": "assets/img/frames/unit/deck_water_unit_rare_frame.png",
  "water|item|rare": "assets/img/frames/item/deck_water_item_rare_frame.png",
  "water|minion|legendary": "assets/img/frames/unit/deck_water_unit_legendary_frame.png",
  "water|spell|legendary": "assets/img/frames/unit/deck_water_unit_legendary_frame.png",
  "water|item|legendary": "assets/img/frames/item/deck_water_item_legendary_frame.png",
  "light|minion|common": "assets/img/frames/unit/deck_light_unit_common_frame.png",
  "light|spell|common": "assets/img/frames/unit/deck_light_unit_common_frame.png",
  "light|item|common": "assets/img/frames/item/deck_light_item_common_frame.png",
  "light|minion|uncommon": "assets/img/frames/unit/deck_light_unit_uncommon_frame.png",
  "light|spell|uncommon": "assets/img/frames/unit/deck_light_unit_uncommon_frame.png",
  "light|item|uncommon": "assets/img/frames/item/deck_light_item_uncommon_frame.png",
  "light|minion|rare": "assets/img/frames/unit/deck_light_unit_rare_frame.png",
  "light|spell|rare": "assets/img/frames/unit/deck_light_unit_rare_frame.png",
  "light|item|rare": "assets/img/frames/item/deck_light_item_rare_frame.png",
  "light|minion|legendary": "assets/img/frames/unit/deck_light_unit_legendary_frame.png",
  "light|spell|legendary": "assets/img/frames/unit/deck_light_unit_legendary_frame.png",
  "light|item|legendary": "assets/img/frames/item/deck_light_item_legendary_frame.png",
  "dark|minion|common": "assets/img/frames/unit/deck_dark_unit_common_frame.png",
  "dark|spell|common": "assets/img/frames/unit/deck_dark_unit_common_frame.png",
  "dark|item|common": "assets/img/frames/item/deck_dark_item_common_frame.png",
  "dark|minion|uncommon": "assets/img/frames/unit/deck_dark_unit_uncommon_frame.png",
  "dark|spell|uncommon": "assets/img/frames/unit/deck_dark_unit_uncommon_frame.png",
  "dark|item|uncommon": "assets/img/frames/item/deck_dark_item_uncommon_frame.png",
  "dark|minion|rare": "assets/img/frames/unit/deck_dark_unit_rare_frame.png",
  "dark|spell|rare": "assets/img/frames/unit/deck_dark_unit_rare_frame.png",
  "dark|item|rare": "assets/img/frames/item/deck_dark_item_rare_frame.png",
  "dark|minion|legendary": "assets/img/frames/unit/deck_dark_unit_legendary_frame.png",
  "dark|spell|legendary": "assets/img/frames/unit/deck_dark_unit_legendary_frame.png",
  "dark|item|legendary": "assets/img/frames/item/deck_dark_item_legendary_frame.png",
  "metal|minion|common": "assets/img/frames/unit/deck_earth_unit_common_frame.png",
  "metal|spell|common": "assets/img/frames/unit/deck_earth_unit_common_frame.png",
  "metal|item|common": "assets/img/frames/item/deck_earth_item_common_frame.png",
  "metal|minion|uncommon": "assets/img/frames/unit/deck_earth_unit_uncommon_frame.png",
  "metal|spell|uncommon": "assets/img/frames/unit/deck_earth_unit_uncommon_frame.png",
  "metal|item|uncommon": "assets/img/frames/item/deck_earth_item_uncommon_frame.png",
  "metal|minion|rare": "assets/img/frames/unit/deck_earth_unit_rare_frame.png",
  "metal|spell|rare": "assets/img/frames/unit/deck_earth_unit_rare_frame.png",
  "metal|item|rare": "assets/img/frames/item/deck_earth_item_rare_frame.png",
  "metal|minion|legendary": "assets/img/frames/unit/deck_earth_unit_legendary_frame.png",
  "metal|spell|legendary": "assets/img/frames/unit/deck_earth_unit_legendary_frame.png",
  "metal|item|legendary": "assets/img/frames/item/deck_earth_item_legendary_frame.png"
};
function frameOf(c) {
  const tribe = (typeof TRIBES !== "undefined" && TRIBES.find(x => x.id === (c && c.tribe))) || { id: "earth" };
  let tid = (tribe && tribe.id) || "earth";
  if (tid === "metal") tid = "earth";
  // Fallback: unit deck frames by tribe (items use pickFrameUrl item keys)
  return (typeof DECK_FRAMES !== "undefined" && (DECK_FRAMES[tid] || DECK_FRAMES.earth)) || "";
}
function pickFrameUrl(c, tribe) {
  const t = tribe || (typeof TRIBES !== "undefined" && TRIBES.find(x => x.id === (c && c.tribe))) || { id: "earth" };
  let tid = (t && t.id) || "earth";
  if (tid === "metal") tid = "earth";
  // Items: dedicated deck_*_item_* frames. Spells: still temporary unit frames until spell set lands.
  const kind = (c && c.type === "item") ? "item" : "minion";
  const rarity = (c && c.rarity) || "common";
  const key = tid + "|" + kind + "|" + rarity;
  if (typeof RARITY_FRAMES !== "undefined" && RARITY_FRAMES[key]) return RARITY_FRAMES[key];
  if (typeof RARITY_FRAMES !== "undefined") {
    const alt = ["common","uncommon","rare","legendary"].map(r => tid + "|" + kind + "|" + r).find(k => RARITY_FRAMES[k]);
    if (alt) return RARITY_FRAMES[alt];
  }
  return frameOf(c);
}
const CARD_ART = {"a1":"assets/img/art/a1.jpg","a2":"assets/img/art/a2.jpg","a3":"assets/img/art/a3.jpg","a4":"assets/img/art/a4.jpg","a5":"assets/img/art/a5.jpg","a6":"assets/img/art/a6.jpg","a7":"assets/img/art/a7.jpg","a8":"assets/img/art/a8.jpg","a9":"assets/img/art/a9.jpg","a10":"assets/img/art/a10.jpg","a11":"assets/img/art/a11.jpg","a12":"assets/img/art/a12.jpg","a13":"assets/img/art/a13.jpg","a14":"assets/img/art/a14.jpg","a15":"assets/img/art/a15.jpg","a16":"assets/img/art/a16.jpg","a17":"assets/img/art/a17.jpg","a18":"assets/img/art/a18.jpg","a19":"assets/img/art/a19.jpg","a20":"assets/img/art/a20.jpg","a21":"assets/img/art/a21.jpg","a22":"assets/img/art/a22.jpg","a23":"assets/img/art/a23.jpg","a24":"assets/img/art/a24.jpg","a25":"assets/img/art/a25.jpg","a26":"assets/img/art/a26.jpg","a27":"assets/img/art/a27.jpg","a28":"assets/img/art/a28.jpg","as1":"assets/img/art/as1.jpg","as2":"assets/img/art/as2.jpg","as3":"assets/img/art/as3.jpg","as4":"assets/img/art/as4.jpg","as5":"assets/img/art/as5.jpg","as6":"assets/img/art/as6.jpg","as7":"assets/img/art/as7.jpg","as8":"assets/img/art/as8.jpg","d1":"assets/img/art/d1.jpg","d2":"assets/img/art/d2.jpg","d3":"assets/img/art/d3.jpg","d4":"assets/img/art/d4.jpg","d5":"assets/img/art/d5.jpg","d6":"assets/img/art/d6.jpg","d7":"assets/img/art/d7.jpg","d8":"assets/img/art/d8.jpg","d9":"assets/img/art/d9.jpg","d10":"assets/img/art/d10.jpg","d11":"assets/img/art/d11.jpg","d12":"assets/img/art/d12.jpg","d13":"assets/img/art/d13.jpg","d14":"assets/img/art/d14.jpg","d15":"assets/img/art/d15.jpg","d16":"assets/img/art/d16.jpg","d17":"assets/img/art/d17.jpg","d18":"assets/img/art/d18.jpg","d19":"assets/img/art/d19.jpg","d20":"assets/img/art/d20.jpg","d21":"assets/img/art/d21.jpg","d22":"assets/img/art/d22.jpg","d23":"assets/img/art/d23.jpg","d24":"assets/img/art/d24.jpg","d25":"assets/img/art/d25.jpg","d26":"assets/img/art/d26.jpg","d27":"assets/img/art/d27.jpg","d28":"assets/img/art/d28.jpg","ds1":"assets/img/art/ds1.jpg","ds2":"assets/img/art/ds2.jpg","ds3":"assets/img/art/ds3.jpg","ds4":"assets/img/art/ds4.jpg","ds5":"assets/img/art/ds5.jpg","ds6":"assets/img/art/ds6.jpg","ds7":"assets/img/art/ds7.jpg","ds8":"assets/img/art/ds8.jpg","e1":"assets/img/art/e1.jpg","e2":"assets/img/art/e2.jpg","e3":"assets/img/art/e3.jpg","e4":"assets/img/art/e4.jpg","e5":"assets/img/art/e5.jpg","e6":"assets/img/art/e6.jpg","e7":"assets/img/art/e7.jpg","e8":"assets/img/art/e8.jpg","e9":"assets/img/art/e9.jpg","e10":"assets/img/art/e10.jpg","e11":"assets/img/art/e11.jpg","e12":"assets/img/art/e12.jpg","e13":"assets/img/art/e13.jpg","e14":"assets/img/art/e14.jpg","e15":"assets/img/art/e15.jpg","e16":"assets/img/art/e16.jpg","e17":"assets/img/art/e17.jpg","e18":"assets/img/art/e18.jpg","e19":"assets/img/art/e19.jpg","e20":"assets/img/art/e20.jpg","e21":"assets/img/art/e21.jpg","e22":"assets/img/art/e22.jpg","e23":"assets/img/art/e23.jpg","e24":"assets/img/art/e24.jpg","e25":"assets/img/art/e25.jpg","e26":"assets/img/art/e26.jpg","e27":"assets/img/art/e27.jpg","e28":"assets/img/art/e28.jpg","es1":"assets/img/art/es1.jpg","es2":"assets/img/art/es2.jpg","es3":"assets/img/art/es3.jpg","es4":"assets/img/art/es4.jpg","es5":"assets/img/art/es5.jpg","es6":"assets/img/art/es6.jpg","es7":"assets/img/art/es7.jpg","es8":"assets/img/art/es8.jpg","f1":"assets/img/art/f1.jpg","f2":"assets/img/art/f2.jpg","f3":"assets/img/art/f3.jpg","f4":"assets/img/art/f4.jpg","f5":"assets/img/art/f5.jpg","f6":"assets/img/art/f6.jpg","f7":"assets/img/art/f7.jpg","f8":"assets/img/art/f8.jpg","f9":"assets/img/art/f9.jpg","f10":"assets/img/art/f10.jpg","f11":"assets/img/art/f11.jpg","f12":"assets/img/art/f12.jpg","f13":"assets/img/art/f13.jpg","f14":"assets/img/art/f14.jpg","f15":"assets/img/art/f15.jpg","f16":"assets/img/art/f16.jpg","f17":"assets/img/art/f17.jpg","f18":"assets/img/art/f18.jpg","f19":"assets/img/art/f19.jpg","f20":"assets/img/art/f20.jpg","f21":"assets/img/art/f21.jpg","f22":"assets/img/art/f22.jpg","f23":"assets/img/art/f23.jpg","f24":"assets/img/art/f24.jpg","f25":"assets/img/art/f25.jpg","f26":"assets/img/art/f26.jpg","f27":"assets/img/art/f27.jpg","f28":"assets/img/art/f28.jpg","fs1":"assets/img/art/fs1.jpg","fs2":"assets/img/art/fs2.jpg","fs3":"assets/img/art/fs3.jpg","fs4":"assets/img/art/fs4.jpg","fs5":"assets/img/art/fs5.jpg","fs6":"assets/img/art/fs6.jpg","fs7":"assets/img/art/fs7.jpg","fs8":"assets/img/art/fs8.jpg","l1":"assets/img/art/l1.jpg","l2":"assets/img/art/l2.jpg","l3":"assets/img/art/l3.jpg","l4":"assets/img/art/l4.jpg","l5":"assets/img/art/l5.jpg","l6":"assets/img/art/l6.jpg","l7":"assets/img/art/l7.jpg","l8":"assets/img/art/l8.jpg","l9":"assets/img/art/l9.jpg","l10":"assets/img/art/l10.jpg","l11":"assets/img/art/l11.jpg","l12":"assets/img/art/l12.jpg","l13":"assets/img/art/l13.jpg","l14":"assets/img/art/l14.jpg","l15":"assets/img/art/l15.jpg","l16":"assets/img/art/l16.jpg","l17":"assets/img/art/l17.jpg","l18":"assets/img/art/l18.jpg","l19":"assets/img/art/l19.jpg","l20":"assets/img/art/l20.jpg","l21":"assets/img/art/l21.jpg","l22":"assets/img/art/l22.jpg","l23":"assets/img/art/l23.jpg","l24":"assets/img/art/l24.jpg","l25":"assets/img/art/l25.jpg","l26":"assets/img/art/l26.jpg","l27":"assets/img/art/l27.jpg","l28":"assets/img/art/l28.jpg","ls1":"assets/img/art/ls1.jpg","ls2":"assets/img/art/ls2.jpg","ls3":"assets/img/art/ls3.jpg","ls4":"assets/img/art/ls4.jpg","ls5":"assets/img/art/ls5.jpg","ls6":"assets/img/art/ls6.jpg","ls7":"assets/img/art/ls7.jpg","ls8":"assets/img/art/ls8.jpg","n1":"assets/img/art/n1.jpg","n2":"assets/img/art/n2.jpg","n3":"assets/img/art/n3.jpg","n4":"assets/img/art/n4.jpg","n5":"assets/img/art/n5.jpg","n6":"assets/img/art/n6.jpg","n7":"assets/img/art/n7.jpg","n8":"assets/img/art/n8.jpg","n9":"assets/img/art/n9.jpg","n10":"assets/img/art/n10.jpg","n11":"assets/img/art/n11.jpg","n12":"assets/img/art/n12.jpg","n13":"assets/img/art/n13.jpg","n14":"assets/img/art/n14.jpg","n15":"assets/img/art/n15.jpg","n16":"assets/img/art/n16.jpg","n17":"assets/img/art/n17.jpg","n18":"assets/img/art/n18.jpg","n19":"assets/img/art/n19.jpg","n20":"assets/img/art/n20.jpg","n21":"assets/img/art/n21.jpg","n22":"assets/img/art/n22.jpg","n23":"assets/img/art/n23.jpg","n24":"assets/img/art/n24.jpg","n25":"assets/img/art/n25.jpg","n26":"assets/img/art/n26.jpg","n27":"assets/img/art/n27.jpg","n28":"assets/img/art/n28.jpg","ns1":"assets/img/art/ns1.jpg","ns2":"assets/img/art/ns2.jpg","ns3":"assets/img/art/ns3.jpg","ns4":"assets/img/art/ns4.jpg","ns5":"assets/img/art/ns5.jpg","ns6":"assets/img/art/ns6.jpg","ns7":"assets/img/art/ns7.jpg","ns8":"assets/img/art/ns8.jpg","coin":"assets/img/art/coin.jpg","e40":"assets/img/art/e40.jpg"};

(function bootstrapCardArt() {
  if (typeof CARD_ART === "undefined" || typeof CARDS === "undefined") return;
  (CARDS || []).forEach(c => {
    if (!c || !c.id) return;
    if (c.type === "item") CARD_ART[c.id] = "assets/img/art/" + c.id + ".jpg";
  });
})();

const CARD_MAP = Object.fromEntries((CARDS || []).filter(c => c && c.id).map(c => [c.id, c]));

// Runtime roster guard — id prefix↔tribe, tribes equal count (28 now; may grow later; NOT a hard cap of 28)
(function assertUnitRoster() {
  if (typeof CARDS === "undefined") return;
  const letterTribe = { a: "water", d: "dark", e: "earth", f: "fire", l: "light", n: "wind" };
  const tribes = ["earth", "fire", "wind", "water", "light", "dark"];
  const counts = Object.fromEntries(tribes.map(t => [t, 0]));
  const idRe = /^[adefln]\d+$/;
  const badIds = [];
  const badTribe = [];
  for (const c of CARDS) {
    if (!c || c.type !== "minion" || c.token) continue;
    if (!idRe.test(c.id)) badIds.push(c.id);
    const expected = letterTribe[c.id && c.id[0]];
    if (expected && c.tribe !== expected) badTribe.push(c.id + ":" + c.tribe + "!=" + expected);
    if (counts[c.tribe] != null) counts[c.tribe]++;
  }
  const vals = tribes.map(t => counts[t]);
  const target = vals[0];
  const unequal = vals.some(v => v !== target);
  if (unequal || badIds.length || badTribe.length) {
    console.error("[cards-data] unit roster guard FAILED", { counts, unequal, badIds, badTribe });
  }
})();



let selectedHero = TRIBES.find(x => x.open);
let state = null;
let ui = { targeting: null, attacker: null, battling: false, rarityFilter: "all", typeFilter: "all", searchQuery: "" };


const CARD_LORE = {
  "e1": "언덕 그늘에 숨은 놀. 발이 흙을 밟을 때마다 돌멩이가 따라 일어나, 작은 무리가 곧 작은 산이 된다.",
  "e2": "대지술사는 주문을 외지 않는다. 손바닥으로 흙을 쓰다듬으면, 땅이 스스로 답을 내놓는다.",
  "e3": "그린드래곤의 비늘은 숲의 계약이다. 주문이 스쳐도 잎사귀처럼 미끄러지고, 뿌리만 남는다.",
  "e4": "나무 속에 사는 드라이어드. 가지가 팔을 대신하고, 잎사귀가 속삭이면 길 잃은 발걸음이 제자리를 찾는다.",
  "e5": "드워프 병사의 망치는 짧고 무겁다. 한 번 내려치면 바위의 결이 드러나고, 적의 방패도 같은 결을 따른다.",
  "e6": "만드라고라의 뿌리가 땅속에서 비명을 지른다. 뽑히는 순간 흙이 뒤집히고, 그 비명이 적의 무릅을 약하게 만든다.",
  "e7": "샌드맨은 모래를 옷처럼 입는다. 흩어져도 다시 모이고, 모이면 다시 주먹을 쥔다.",
  "e8": "나무궁수는 활시위를 나무결에 맞춘다. 화살이 날아가면 나뭇잎이 먼저 흔들리고, 그다음에 표적이 흔들린다.",
  "e9": "오크의 함성이 골짜기를 메운다. 도끼는 투박해도 정직하고, 두 번째 일격은 언제나 첫 번째보다 가깝다.",
  "e10": "드워프대장은 방패로 전열을 그린다. 그의 발자국이 멈춘 자리는 곧 전선의 기준이 된다.",
  "e11": "숲요정이 이슬을 밟고 나타난다. 작은 손짓에 덤불이 길을 열고, 전장에 초록빛이 먼저 도착한다.",
  "e12": "스톤골렘은 말이 없다. 돌이 쌓인 가슴이 방패가 되고, 한 걸음마다 대지가 그의 이름을 기억한다.",
  "e13": "마운록은 산등성이에서 내려온 명장. 쓰러져도 돌무더기가 일어서듯, 복수는 바위의 방식으로 돌아온다.",
  "e14": "마초의 창은 서량의 먼지를 먹으며 자랐다. 돌파하는 기세가 산허리를 가르면, 적진은 금이 간 절벽처럼 무너진다.",
  "e15": "암석창병은 창날을 돌결로 벼렸다. 짧은 한 찌름에도 흙먼지가 피어오르고, 전선의 숨이 잠깐 멎는다.",
  "e16": "켄타우로스는 말발굽으로 길을 낸다. 창과 다리가 하나처럼 달리면, 언덕도 잠깐 평지가 된다.",
  "e17": "고르곤의 시선이 스치면 근육이 돌처럼 굳는다. 석화는 저주가 아니라, 그녀의 고요한 숨결이다.",
  "e18": "대지의 정령이 쓰러지면 흙이 그를 감싼다. 마지막 숨이 씨앗이 되어, 전장에 새로운 돌이 돋아난다.",
  "e19": "곽가는 흙먼지를 지도처럼 읽는다. 손짓 하나에 전열이 다시 서고, 광야의 바람이 그의 계책을 따른다.",
  "e20": "베헤모스가 땅을 울리면 산맥이 숨을 쉰다. 돌진하는 무게는 성벽보다 먼저 마음을 무너뜨린다.",
  "e21": "록마운틴킹은 왕관을 쓰지 않는다. 산봉우리가 그의 왕좌이고, 쓰러진 적의 돌이 그의 조공이다.",
  "e22": "스핑크스의 수수께끼는 돌로 된 침묵이다. 답을 모르는 자는 발이 굳고, 알아도 쉽게 길을 열지 못한다.",
  "e23": "조조의 눈은 전장의 빈틈을 훔친다. 강탈은 칼보다 빠르고, 빼앗긴 숨은 그의 깃발 아래서 다시 선다.",
  "e24": "티라노의 이빨이 땅을 찍으면 골짜기가 벌어진다. 돌파하는 발자국마다 먼지가 왕관을 이룬다.",
  "e25": "대지자이언트가 허리를 펴면 하늘이 낮아진다. 그의 그림자가 닿는 곳은 이미 요새가 된다.",
  "e26": "사이클롭스의 외눈이 적을 고른다. 한 번 노려본 자리는 돌이 되고, 돌이 된 자리는 다시 무기가 된다.",
  "e27": "샌드웜이 모래 밑을 가르면 사막이 강처럼 흐른다. 입을 벌린 순간, 전장은 한 줄기의 골짜기가 된다.",
  "e28": "이끼방패병은 이끼를 갑옷처럼 두른다. 방패에 닿은 칼날은 미끄러지고, 그 자리에 푸른 흔적만 남는다.",
  "e40": "떠오른 섬에서 떨어진 한 조각. 작아도 흙의 기억이 남아, 빈 칸을 조용히 메운다.",
  "f1": "레드드래곤의 열기는 주문을 태우기 전에 먼저 삼킨다. 비늘 위에서는 마법도 재가 된다.",
  "f2": "불꽃궁수는 시위에 불씨를 매단다. 화살이 박힌 자리는 검게 남고, 연기가 적의 이름을 지운다.",
  "f3": "임프는 난로에서 튀어나온 장난. 커튼을 만나면 진지해지고, 진지해지면 이미 불길이다.",
  "f4": "고블린의 웃음은 횃불보다 먼저 번진다. 약탈이 끝나면 지붕만 재로 남는다.",
  "f5": "불꽃여우가 달리면 들판에 점이 찍힌다. 점이 이어지는 순간, 평원이 산불이 된다.",
  "f6": "가후의 계책은 불꽃처럼 짧고 뜨겁다. 한 번의 손짓에 전열이 타오르고, 적의 그림자가 먼저 사라진다.",
  "f7": "샐러맨더는 용암 강에서 태어났다. 혀가 닿는 자리마다 살이 식지 못하고, 상처가 불꽃으로 남는다.",
  "f8": "용암술사가 쓰러지면 땅속에서 마지막 불씨가 솟는다. 유언은 재가 아니라, 다시 타오르는 숨이다.",
  "f9": "용암늑대의 발자국은 검은 유리처럼 굳는다. 울음이 끝나면 숲이 이미 숯이 되어 있다.",
  "f10": "헬하운드의 숨결이 쇳물을 말린다. 연속으로 물어뜯는 이빨 사이로, 지옥의 열이 새어 나온다.",
  "f11": "바바리안은 분노를 갑옷 대신 입는다. 돌진이 시작되면 제동은 없고, 남은 것은 재와 함성뿐이다.",
  "f12": "여령기의 창끝은 정오의 태양처럼 날카롭다. 치명적 섬광이 스치면, 적의 숨이 한 박자 늦는다.",
  "f13": "파이어골렘은 돌과 불이 한 몸으로 굳은 요새. 식으면 석상처럼 보이지만, 달아오르면 복수로 다시 걷는다.",
  "f14": "폭염방패병은 방패 뒤에 열기를 숨긴다. 다가오는 칼날이 먼저 휘고, 전선은 잠시 고요해진다.",
  "f15": "장비의 고함은 장판교를 태운 전설이다. 창이 두 번 스치면 적진이 재가 되고, 불꽃조차 그를 삼키지 못한다.",
  "f16": "미노타우로스의 미궁은 뿔끝에서 시작된다. 연속으로 내려치는 도끼가 길을 닫고, 도망칠 출구를 지운다.",
  "f17": "불의 정령은 형체보다 온도로 말한다. 손끝이 스치면 갑옷이 무르고, 전장이 한낮처럼 밝아진다.",
  "f18": "이프리트의 웃음은 사막의 신기루다. 치명적 불꽃이 피어오르면, 신기루가 진짜 불길이 된다.",
  "f19": "케르베로스의 세 목이 동시에 으르렁댄다. 연속된 이빨이 전선을 찢고, 그림자가 세 겹으로 남는다.",
  "f20": "데빌은 혼란을 향기처럼 뿌린다. 시선이 엇갈리는 순간, 아군과 적군의 경계가 재처럼 흐려진다.",
  "f21": "화염창병은 창날에 불꽃을 감는다. 짧은 찌름에도 연기가 피어오르고, 전선이 한순간 밝아진다.",
  "f22": "하후돈의 눈은 짐승보다 뜨겁다. 흡혈처럼 빨아들이는 기세에, 적의 기운이 그의 창으로 흘러든다.",
  "f23": "발록의 불꽃은 남의 목숨을 연료로 삼는다. 칼이 스칠수록 그의 심장이 더 붉게 뛴다.",
  "f24": "키메라는 세 가지 숨결을 한몸에 품는다. 돌파하는 발걸음마다 불·독·이빨이 동시에 길을 연다.",
  "f25": "타이폰의 회오리는 폭풍이 아니라 분노다. 혼란 속에 번개가 섞이면, 산조차 무릎을 꿇는다.",
  "f26": "피닉스는 재 위에서 이름을 다시 쓴다. 타버린 날개가 접혀도, 새벽이 오면 불꽃이 새로 돋는다.",
  "f27": "화염자이언트가 한 걸음 내디디면 능선이 녹는다. 돌진하는 열기가 골짜기를 강물처럼 흐르게 한다.",
  "f28": "불꽃요정이 손끝에서 불티를 튕긴다. 작은 불씨가 전장에 내려앉으면, 공기가 먼저 뜨거워진다.",
  "n1": "깃털도마뱀은 절벽에서 뛰어내려도 떨어지지 않는다. 떨어지는 것은 뒤쫓는 적의 발이다.",
  "n2": "조운의 흰 갑옷에는 먼지만 앉는다. 일곱 번 적진을 드나들어도 창끝은 늘 바람을 먼저 가른다.",
  "n3": "질풍술사는 주문을 바람결에 실어 보낸다. 약화의 숨이 스치면, 강한 팔도 잠깐 가벼워진다.",
  "n4": "픽시는 손바닥만 한 요정이다. 티끌처럼 보여도 그 티끌이 폭풍의 씨앗이 된다.",
  "n5": "구름사슴이 달리면 발굽 아래 안개가 핀다. 잡히려는 손에는 구름만 남고, 사슴은 이미 능선 너머에 있다.",
  "n6": "매사냥꾼은 매와 한 몸을 이룬다. 창보다 먼저 그림자가 내려앉고, 표적은 하늘을 올려다볼 틈이 없다.",
  "n7": "바람늑대의 울음이 골짜기를 한 바퀴 돈다. 돌파하는 발자국이 이어지면, 사냥이 바람처럼 시작된다.",
  "n8": "선풍무사의 칼날은 손잡이 없는 돌풍이다. 연속으로 베어 나가면, 옷깃이 갈라진 뒤에야 통증을 느낀다.",
  "n9": "손상향의 화살은 바람의 길을 훔친다. 관통하듯 스치는 한 발이, 깃발보다 먼저 적의 숨을 가른다.",
  "n10": "하피의 날갯짓이 진영을 흩뜨린다. 약화의 비명이 퍼지면, 방패를 든 팔이 먼저 떨린다.",
  "n11": "그리핀이 하늘을 가르면 그림자가 창이 된다. 돌진하는 발톱이 땅에 닿기 전에, 심장부터 내려앉는다.",
  "n12": "윈드골렘은 공기로 빚은 거상이다. 칼이 스쳐도 상처를 남기지 못하고, 바람만 남는다.",
  "n13": "폭풍드래곤의 구름은 방패다. 뇌우 속에 숨은 비늘은 주문의 손을 잡지 않는다.",
  "n14": "폭풍창병은 창에 태풍을 묶었다. 짧은 찌름에도 공기가 갈라지고, 전선이 한순간 흔들린다.",
  "n15": "회오리무희가 한 바퀴 돌면 진형이 흩어진다. 혼란의 치마자락이 스치는 곳마다 방향이 뒤바뀐다.",
  "n16": "가루다의 날개는 태양을 가리는 깃발이다. 치명적 급강하가 끝나면, 땅 위에 깃털과 침묵만 남는다.",
  "n17": "바람의 정령이 흩어지면 마지막 돌풍이 남는다. 유언처럼 지나가는 숨결이, 아군의 등에 힘을 실어 준다.",
  "n18": "회오리궁수는 시위를 회오리에 맡긴다. 화살이 바람길을 타면, 방패 틈으로도 숨결이 스며든다.",
  "n19": "페가수스의 발굽은 구름을 디딘다. 돌진하는 날개가 열리면, 지상은 잠깐 하늘이 된다.",
  "n20": "호크라이더는 매의 등을 안장 삼는다. 돌파하는 그림자 아래, 적의 깃발이 거꾸로 펄럭인다.",
  "n21": "구름방패병은 안개로 방패를 짠다. 창이 들어오면 방향을 잃고, 방패 뒤에는 고요한 바람만 남는다.",
  "n22": "바람요정이 소매를 흔들면 공기가 맑아진다. 작은 출전에 전장이 숨 고르기를 하고, 템포가 다시 선다.",
  "n23": "템페스트는 방향을 잃은 바람의 이름이다. 칼날이 돌아와도, 폭풍은 반격의 길을 지워 버린다.",
  "n24": "폭풍자이언트가 허리를 펴면 천둥이 무릎을 꿇는다. 연속으로 내려치는 주먹이 구름을 깨뜨린다.",
  "n25": "썬더버드의 날갯짓에 번개가 깃든다. 치명적 섬광이 내리꽂히면, 밤조차 한순간 낮이 된다.",
  "n26": "와이번의 비늘은 바람결을 닮았다. 관통하는 꼬리치기가 성벽을 스치면, 돌도 잠깐 깃털처럼 가볍다.",
  "n27": "태사자의 칼춤은 강동을 가로지른 전설이다. 연속으로 가르는 검풍 앞에, 적진은 갈대처럼 눕는다.",
  "n28": "육손의 불꽃은 동풍을 타고 온다. 광역으로 번지는 계책에, 적장의 돛이 먼저 방향을 잃는다.",
  "a1": "관우의 청룡언월도는 강물처럼 무겁다. 돌진하는 의리가 적진을 가르면, 빼앗긴 숨도 그의 깃발 아래로 돌아온다.",
  "a2": "슬라임은 밟혀도 퍼지고, 퍼진 자리에서 다시 모인다. 물방울이 점액이 된 작은 끈질김이다.",
  "a3": "연못거북은 등딱지에 호수를 이고 산다. 적이 다가오면 물을 닫고, 등 위에는 잔잔한 파문만 남는다.",
  "a4": "피라냐의 이빨은 잔물결보다 빠르다. 한 마리가 물면 무리가 따라오고, 강이 잠깐 피로 물든다.",
  "a5": "나가의 시선이 스치면 근육이 축축해진다. 약화의 비늘이 스며들면, 강한 팔도 물처럼 풀린다.",
  "a6": "독두꺼비의 등은 예쁜 무늬로 거짓말한다. 먼저 아름다움을 보고, 독은 발밑에서 천천히 스민다.",
  "a7": "리자드맨은 강가를 성벽처럼 지킨다. 돌진하는 창끝이 물을 가르면, 물길이 곧 길이 된다.",
  "a8": "빙결술사의 숨결이 닿으면 시간이 굳는다. 석화처럼 얼어붙은 적은, 다음 파도를 기다릴 수밖에 없다.",
  "a9": "전기해파리의 촉수가 번쩍이면 방향이 뒤섞인다. 혼란의 전류가 흐르는 동안, 칼끝도 길을 잃는다.",
  "a10": "파도창병은 창날에 밀물을 담는다. 짧은 찌름 뒤에 두 번째 파도가 따라와, 방패 틈을 적신다.",
  "a11": "심해방패병은 어둠 속에서 등을 내민다. 방패에 닿은 칼날은 깊이로 미끄러지고, 전선은 고요해진다.",
  "a12": "머메이드의 노래는 상처를 핥는다. 흡혈처럼 빨아들인 숨결이, 그녀의 비늘 아래에서 다시 빛난다.",
  "a13": "대교의 미소는 강물보다 깊다. 약화의 손짓이 스치면, 강한 칼도 잠깐 물결처럼 흔들린다.",
  "a14": "아이스드래곤이 날개를 접으면 호수가 거울이 된다. 스펠의 불꽃도 그 얼음 위에서는 이름만 남긴다.",
  "a15": "손권은 강동의 파도를 왕좌로 삼는다. 강탈하듯 빼앗은 흐름이, 그의 깃발 아래서 새로운 물길이 된다.",
  "a16": "아이스골렘은 얼음으로 쌓은 요새다. 보호의 결정이 깨지기 전에는, 불꽃도 잠시 미끄러진다.",
  "a17": "물의 정령이 스러지면 마지막 물결이 남는다. 유언처럼 번지는 파문이 아군의 상처를 씻어 내린다.",
  "a18": "세이렌의 노래는 방향을 훔친다. 혼란에 빠진 귓가에는, 파도 소리와 칼소리가 같은 박자로 들린다.",
  "a19": "켈피는 물결을 안장 삼아 달린다. 돌파하는 발굽 아래, 적의 진형이 강바닥처럼 쓸려 간다.",
  "a20": "시서펜트가 수면을 가르면 지평선이 흔들린다. 돌진하는 비늘이 배의 뼈대를 스치고도 멈추지 않는다.",
  "a21": "물의요정이 손끝에서 이슬을 뿌린다. 출전하는 순간 공기가 촉촉해지고, 전장이 잠시 호수처럼 고요해진다.",
  "a22": "강가무녀가 달을 부르면 물이 차오른다. 약화의 축축함이 발목부터 잠기고, 강한 발도 미끄러진다.",
  "a23": "주유는 동풍을 읽듯 전장을 읽는다. 광역으로 번지는 불꽃의 계책 앞에, 적장의 돛이 먼저 기울다.",
  "a24": "심해상어는 빛이 없는 곳에서 이빨만 빛난다. 관통하는 돌진이 지나면, 수면에 붉은 길만 남는다.",
  "a25": "얼음궁수는 화살촉에 서리를 입힌다. 관통하는 한 발이 방패를 스치면, 그 자리에 하얀 금이 간다.",
  "a26": "바다자이언트가 허리를 펴면 파도가 성벽이 된다. 한 걸음에 항구가 흔들리고, 배들이 무릎을 꿇는다.",
  "a27": "크라켄의 갑각이 파도를 받아내면, 그 무게가 곧 돌진이 된다. 방패만큼의 바다가 함대를 덮친다.",
  "a28": "히드라의 목이 잘려도 물이 새 목을 키운다. 연속으로 물어뜯는 이빨 사이로, 강이 다시 흐른다.",
  "l1": "태양궁수는 시위에 정오를 매단다. 관통하는 광채가 날아가면, 그늘조차 잠깐 길을 비킨다.",
  "l2": "빛나방은 티끌만 한 날개로 성소를 지킨다. 날갯짓 한 번에 어둠이 얇아지고, 기도가 먼저 도착한다.",
  "l3": "치유술사가 쓰러져도 손끝의 온기는 남는다. 유언처럼 퍼지는 빛이 상처를 덮고, 숨을 다시 고르게 한다.",
  "l4": "제갈량의 부채는 별을 부린다. 광역으로 펼쳐지는 계책과 보호의 진이, 전장을 한밤의 성소로 바꾼다.",
  "l5": "축복방패병은 방패에 기도를 새긴다. 칼이 닿으면 빛이 먼저 받고, 병사의 어깨는 더 곧아진다.",
  "l6": "빛늑대의 털결에는 새벽이 묻어 있다. 울음이 골짜기를 밝히면, 그림자가 먼저 물러선다.",
  "l7": "성녀의 손바닥은 샘물보다 따뜻하다. 스치기만 해도 먼지가 씻기고, 마음이 잠시 고요해진다.",
  "l8": "신관은 향보다 침묵으로 말한다. 축복이 내려앉으면 방패가 두꺼워지고, 칼날의 조급함이 잦아든다.",
  "l9": "예언자는 아직 오지 않은 아침을 읽는다. 속삭임 하나에 전열이 정리되고, 불안이 기도로 바뀐다.",
  "l10": "황충의 화살은 백발백중의 전설이다. 치명적 한 발이 태양을 스치면, 적의 투구에 금이 간다.",
  "l11": "골드골렘은 황금으로 빚은 수호상이다. 보호의 광채가 깨지기 전에는, 어떠한 칼도 예의를 차린다.",
  "l12": "성기사의 창은 서약을 닮았다. 보호의 빛으로 전열을 가리면, 뒤에 선 이들이 다시 숨을 쉰다.",
  "l13": "광명창병은 창날에 촛불을 담는다. 짧은 찌름에도 전선이 밝아지고, 어둠이 한 발 물러선다.",
  "l14": "수도사는 주먹을 기도처럼 모은다. 말이 없어도 그 고요함이 성벽이 되어, 아군의 등을 받친다.",
  "l15": "인챈터의 손끝이 갑옷을 어루만지면 약함이 스민다. 적의 힘이 잠깐 풀리며, 빛이 틈을 만든다.",
  "l16": "금빛사자는 갈기에 석양을 두른다. 보호의 포효가 울리면, 무리 전체가 한 몸처럼 단단해진다.",
  "l17": "황월영의 미소는 달빛처럼 고요하다. 보호의 장막이 내려앉으면, 칼바람도 잠시 예의를 지킨다.",
  "l18": "십자군의 깃발은 기도의 창이다. 돌진하는 발걸음마다 성호가 그려지고, 길이 스스로 열린다.",
  "l19": "유비의 인덕은 칼보다 먼저 전장에 닿는다. 보호의 약속이 깃발을 세우면, 병사들의 등이 곧아진다.",
  "l20": "타이탄이 허리를 펴면 별자리가 흔들린다. 보호의 거체가 성문이 되어, 도시를 한 손에 안는다.",
  "l21": "발키리의 날개는 전장의 선택이다. 치명적 창끝이 내려오면, 운명조차 잠깐 숨을 고른다.",
  "l22": "빛의 정령은 형체보다 온기로 남는다. 스쳐 지나가기만 해도 먼지가 씻기고, 마음이 밝아진다.",
  "l23": "신전기사는 서약을 갑옷으로 입는다. 보호의 광채가 투구 위에서 춤추면, 적도 잠시 고개를 숙인다.",
  "l24": "유니콘의 뿔은 샘물의 바늘이다. 상처 위에 스치면 검은 기운이 걷히고, 숨이 다시 맑아진다.",
  "l25": "광휘요정이 손끝에서 별가루를 뿌린다. 출전하는 순간 전장이 성소처럼 밝아지고, 기도가 먼저 선다.",
  "l26": "골드드래곤의 광휘는 성소의 장막이다. 스펠이 닿아도 정오의 햇살처럼 튕겨 나간다.",
  "l27": "엔젤의 날개는 칼보다 먼저 내려앉는다. 면역의 후광 안에서는, 저주도 길을 찾지 못한다.",
  "l28": "태양자이언트가 한 걸음 내디디면 그림자가 짧아진다. 연속으로 내려치는 주먹이 대지를 정오로 물들인다.",
  "d1": "로그는 그림자 속에서만 이름을 단다. 돌파하는 단검이 등 뒤에 닿을 때, 달은 일부러 구름 뒤로 숨는다.",
  "d2": "사마의의 침묵은 함정이다. 광역으로 펼쳐지는 계책 앞에, 적진은 안개처럼 삼켜진다.",
  "d3": "그림자궁수는 시위를 어둠에 맡긴다. 관통하는 화살이 날아가면, 맞은 자의 그림자가 먼저 쓰러진다.",
  "d4": "해골나방은 뼈로 된 날개를 펄럭인다. 작은 날갯짓에 묘지의 먼지가 일고, 공기가 싸늘해진다.",
  "d5": "고스트는 벽을 갖지 않는다. 혼란처럼 스며드는 한기가 귓가를 스치면, 칼끝이 제 주인을 의심한다.",
  "d6": "구울은 무덤에서 이름을 다시 꺼낸다. 환생처럼 일어선 손아귀에, 아직 따뜻한 흙이 묻어 있다.",
  "d7": "여포의 방천화극은 하늘을 가른다. 혼란의 일격이 쏟아져도 그는 다시 일어나고, 전장이 그의 이름을 외친다.",
  "d8": "암흑창병은 창날에 심야를 담는다. 관통하는 짧은 찌름에, 횃불이 먼저 숨을 죽인다.",
  "d9": "스켈레톤은 살이 없어도 대열을 지킨다. 뼈가 부딪히는 소리가 북이 되어, 죽은 자들의 전진이 시작된다.",
  "d10": "심연술사가 쓰러지면 구덩이가 남는다. 유언처럼 열린 심연이 적의 발목을 끌어당긴다.",
  "d11": "초선의 미소는 칼보다 깊다. 환생처럼 되살아나는 매혹이, 전장의 숨결을 한쪽으로 기울게 한다.",
  "d12": "다크골렘은 검은 돌로 쌓인 원한이다. 복수가 깨지기 전에는, 어떠한 빛도 그의 가슴에 닿지 못한다.",
  "d13": "미라는 붕대 속에 시간을 묶었다. 환생처럼 다시 일어설 때마다, 먼지가 왕관을 이룬다.",
  "d14": "서큐버스의 속삭임은 피를 달게 한다. 흡혈의 입맞춤이 끝나면, 적의 기운이 그녀의 그림자 속으로 흘러든다.",
  "d15": "나이트메어는 잠든 자의 등을 탄다. 환생처럼 되풀이되는 악몽이, 아침이 와도 쉽게 깨지지 않는다.",
  "d16": "듀라한은 머리를 옆구리에 끼고 달린다. 연속으로 내려치는 칼질이 길 위의 이름표를 지운다.",
  "d17": "저주방패병은 방패에 저주를 새긴다. 칼이 닿으면 저주가 먼저 옮고, 전선이 싸늘하게 가라앉는다.",
  "d18": "장료의 돌파는 합비의 밤을 닮았다. 적진을 가르는 기세에, 함성보다 침묵이 먼저 무너진다.",
  "d19": "그림자요정이 소매를 펼치면 등불이 꺼진다. 출전하는 순간 공기가 얇아지고, 승부의 틈이 열린다.",
  "d20": "가고일은 석상인 척 밤을 지킨다. 보호의 날개가 펴지면, 침입자의 발소리가 돌에 삼켜진다.",
  "d21": "네크로맨서는 뼈로 악보를 쓴다. 석화처럼 굳어 가는 적이 악보의 쉼표가 되고, 심연이 박자를 맞춘다.",
  "d22": "만티코어의 꼬리는 독침의 편지다. 관통하는 가시가 꽂히면, 편지의 내용은 이미 늦다.",
  "d23": "리치의 왕관은 죽음을 한 번 거절한다. 뼈가 흩어져도 한 줌의 한기가 다시 일어선다.",
  "d24": "암흑의 정령은 공허의 온기를 닮았다. 약화의 손길이 스치면, 강한 팔도 그림자처럼 풀린다.",
  "d25": "뱀파이어의 망토는 달빛보다 검다. 흡혈의 이빨이 목을 스치면, 새벽이 한 박자 늦어진다.",
  "d26": "본맘모스는 뼈로 된 산맥이다. 돌진하는 엄니가 땅을 찍으면, 묘지조차 길을 비킨다.",
  "d27": "블랙드래곤의 비늘은 달을 삼킨 밤이다. 치명적 숨결이 골짜기를 스치면, 별조차 눈을 감는다.",
  "d28": "암흑자이언트가 허리를 펴면 지평선이 꺼진다. 강탈하듯 빼앗은 빛이 그의 주먹 안에서 꺼져 간다.",
  "fs1": "시위에 불씨를 맨 화살. 날아간 자리에 검게 남은 점이, 적의 이름을 조용히 지운다.",
  "fs2": "하늘이 분노로 물드는 폭풍. 그늘이 사라지고, 전장 전체가 한순간 화로가 된다.",
  "fs3": "손바닥에서 굴러가는 작은 태양. 던지는 순간 커지고, 맞는 순간 밤이 물러난다.",
  "fs4": "화염탄은 말이 없다. 한 점이 적중하면 형체가 재가 되고, 재만이 증거를 남긴다.",
  "fs5": "폭염은 아군의 숨까지 달군다. 뜨거운 숨결을 내쉬는 사이, 손패에 새로운 불씨가 내려앉는다.",
  "fs6": "광분은 내일의 마나를 오늘 빌려 온다. 심장이 세 박자 빠르게 뛰면, 다음 새벽이 벌써 타오른다.",
  "fs7": "화염방패는 열기로 짠 성벽이다. 다가오는 칼날이 먼저 휘고, 방패 뒤의 숨은 뜨겁게 고요하다.",
  "fs8": "메테오는 하늘이 던진 심판이다. 떨어지는 불덩이마다 코인의 기운이 타고, 대지가 짧게 울린다.",
  "ns1": "바람망토는 손패에 깃든 방패다. 펼치면 화살이 길을 잃고, 병사들의 어깨가 가벼워진다.",
  "ns2": "진공베기는 손잡이 없는 칼바람이다. 운을 걸친 자만이 그 공백에 삼켜진다.",
  "ns3": "상승기류가 손패를 들어 올린다. 네 장의 숨결이 내려앉으면, 전장의 템포가 다시 고르게 선다.",
  "ns4": "떠오르는 섬은 빈자리를 땅으로 바꾼다. 파편이 앉을수록 전장이 새로운 지평을 얻는다.",
  "ns5": "토네이도는 가벼운 목숨부터 집어 올린다. 작은 것들이 모래가 되면, 발밑이 잠깐 비어 보인다.",
  "ns6": "바람방패는 공기를 갑옷으로 짠다. 한 사람의 숨이 안정되면, 전선 전체가 한 박자 느긋해진다.",
  "ns7": "한줄기바람은 티끌만 한 숨결이다. 적의 볼을 스치고 지나가며, 손패에 작은 기류를 남겨 둔다.",
  "ns8": "폭풍우는 하늘이 낮아지는 주문이다. 비바람과 함께 운의 조각이 쓸려 가고, 지붕이 먼저 항복한다.",
  "as1": "냉기화살은 화살촉에 서리를 담는다. 맞은 자리는 움직임을 잃고, 다음 숨까지 얼음에 묶인다.",
  "as2": "물거울은 아군을 호수에 비춘다. 비친 형체가 일어나면 보호의 물결이 그 등을 감싼다.",
  "as3": "익사는 얕은 물을 심연으로 바꾼다. 가벼운 발걸음일수록 먼저 발목부터 잠긴다.",
  "as4": "수정호수가 손을 적시면 시야가 맑아진다. 손패가 늘어나는 사이, 적의 방패가 한 겹 얇아진다.",
  "as5": "얼음방패는 결빙으로 짠 성벽이다. 칼이 미끄러지는 소리와 함께, 전선이 잠시 고요해진다.",
  "as6": "눈보라가 몰아치면 발목이 먼저 굳는다. 맞은 자들은 다음 숨까지 칼끝을 들지 못한다.",
  "as7": "인어의노래는 힘을 잔물결로 낮춘다. 운의 조각이 잠기는 동안, 강한 팔도 물처럼 풀린다.",
  "as8": "개구리변신은 거만을 연못의 개구리로 바꾼다. 적의 기세가 한순간에 작고 촉촉해진다.",
  "es1": "거인의봉인은 이름을 사슬로 묶는다. 힘이 넘쳐흐르는 자일수록, 주먹을 펼 수 없는 돌이 된다.",
  "es2": "어스퀘이크는 대지가 허리를 꺾는 순간이다. 적의 숨이 골짜기로 쓸려 가고, 전장이 새로 갈라진다.",
  "es3": "샌드트랩은 빈자리를 손으로 센다. 비어 있는 칸이 많을수록, 모래의 주먹이 더 많이 올라온다.",
  "es4": "미로생성은 강한 자를 길 잃게 한다. 복수심이 아군의 발밑에 뿌리를 내려, 전열이 돌처럼 단단해진다.",
  "es5": "땅굴숨기는 병사 수만큼 숨을 고르게 한다. 흙 속에서 손패가 피어나고, 전선이 다시 숨 쉰다.",
  "es6": "낙석은 절벽이 준비한 인사다. 작은 돌도 투구를 깨고, 모든 어깨가 잠깐 낮아진다.",
  "es7": "모래지옥에 발이 빠지면 힘도 가죽도 함께 빠진다. 전장 전체가 천천히, 깊게 가라앉는다.",
  "es8": "거대화는 한 사람의 숨을 산으로 키운다. 가슴이 넓어질수록, 대지가 그의 등을 밀어 올린다.",
  "ls1": "치유의빛은 상처를 이슬처럼 덮는다. 아군 전열에 온기가 스며들면, 먼지가 먼저 씻긴다.",
  "ls2": "축복은 한 사람을 성소로 만든다. 손과 심장이 동시에 밝아지며, 칼끝이 두 번 숨 쉰다.",
  "ls3": "정화는 흉폭함을 고요한 등불로 낮춘다. 적의 기세가 걷히면, 남은 것은 길어진 숨뿐이다.",
  "ls4": "성역축복은 오늘의 운을 기도로 물들인다. 앞면이 더 자주 빛나고, 전선이 짧게 미소 짓는다.",
  "ls5": "수호의빛은 전열 전체에 장막을 드리운다. 칼이 닿기 전에 빛이 먼저 받고, 어깨가 다시 곧아진다.",
  "ls6": "성벽가호는 한 사람을 성문으로 세운다. 방패와 숨이 두꺼워질수록, 뒤에 선 이들이 안심한다.",
  "ls7": "빛의환영은 얇은 섬광의 인사다. 적에게는 따가움이, 아군에게는 이슬 같은 온기가 동시에 내린다.",
  "ls8": "헌금은 손을 모으고 기다리는 시간이다. 카드가 내려앉는 동안 병사는 나오지 못하고, 기도만 남는다.",
  "ds1": "파멸은 강한 것의 이름을 지운다. 힘이 넘친 자일수록, 공허가 먼저 그를 선택한다.",
  "ds2": "굶주림은 아군의 목숨을 대가로 손을 뻗는다. 쓰러진 숨 너머로, 두 장의 그림자가 손패에 앉는다.",
  "ds3": "헬게이트가 열리면 숨결이 동시에 꺼진다. 전장 전체가 한순간 심연의 문지방이 된다.",
  "ds4": "불길한예감은 아군의 운을 전부 검은 면으로 뒤집어 놓는다. 그 대신 공방체가 한꺼번에 솟는다.",
  "ds5": "블랙홀은 모든 이름을 삼킨다. 남은 것은 공허와, 한 단계 낮아진 숨의 한계뿐이다.",
  "ds6": "해골던지기는 약한 자의 목을 먼저 고른다. 뼈가 날아가 꽂히면, 작은 숨이 먼지처럼 흩어진다.",
  "ds7": "전염병은 무거운 자들부터 깎아 내린다. 큰 몸집일수록 빨리 마르고, 전장이 공동처럼 고요해진다.",
  "ds8": "13시의저주는 코인을 흔적 없이 지운다. 저주가 닿은 유닛은 행운을 벗겨낸 듯, 모든 코인이 사라진다.",
  "ei1": "골렘의심장은 돌로 된 고동이다. 가슴에 안으면 숨이 두꺼워지고, 보호의 결이 피부처럼 돋는다.",
  "ei2": "돌도끼는 투박해도 정직하다. 날이 바위를 닮아, 맞힌 자리의 결을 그대로 가른다.",
  "ei3": "바실리스크눈은 주머니 속의 침묵이다. 시선이 열리는 순간, 근육이 돌처럼 숨을 멈춘다.",
  "ei4": "노름바위는 운을 무게로 바꾼다. 코인이 쌓일수록 주먹과 숨이 함께 무거워진다.",
  "ei5": "모래시계는 흩어진 시간을 다시 모은다. 뒤집히는 순간, 쓰러진 숨이 환생처럼 되돌아온다.",
  "ei6": "대지의팔찌는 산허리를 팔에 감는다. 돌진하는 기세가 손목에서부터 일어나, 길이 스스로 열린다.",
  "fi1": "불꽃검은 칼날에 불씨를 먹인다. 스치기만 해도 갑옷이 무르고, 적의 기세가 잠깐 식는다.",
  "fi2": "불꽃도끼는 장작을 패듯 전선을 가른다. 관통하는 열기가 방패 틈으로 스며든다.",
  "fi3": "불붙은건틀렛은 주먹을 화로로 만든다. 막아내는 팔이 뜨거워질수록, 적의 칼도 잠시 머뭇거린다.",
  "fi4": "피닉스깃털은 재 위의 약속이다. 가슴에 꽂히면 숨이 두꺼워지고, 쓰러져도 다시 타오른다.",
  "fi5": "도박불꽃반지는 운을 불꽃에 건다. 연속으로 타오르다 뒷면만 남으면, 반지 스스로가 재가 된다.",
  "fi6": "분노의해머는 화산의 주먹이다. 한 번 내리치면 사방이 흔들리고, 성벽의 이름이 짧게 탄다.",
  "ni1": "요정의부츠는 발끝을 깃털처럼 만든다. 한 걸음이 가벼워지면, 전선의 템포가 안정적으로 선다.",
  "ni2": "올빼미의눈은 밤의 조준경이다. 관통하는 시선이 활시위에 실리면, 그늘 속의 표적도 드러난다.",
  "ni3": "페어리소드는 요정의 숨결을 칼에 묶는다. 스치는 순간 힘이 풀리고, 공기가 잠깐 맑아진다.",
  "ni4": "도둑바람은 전장의 운을 한꺼번에 쓸어 간다. 코인이 사라지면, 모두가 맨손으로 다시 선다.",
  "ni5": "하피의손톱은 급강하의 기억이다. 치명적 생채기가 남으면, 숨이 한 박자 늦어진다.",
  "ni6": "폭풍의구슬은 손안에 가둔 뇌우다. 깨지는 순간 광역의 바람이 퍼지고, 지붕이 먼저 흔들린다.",
  "ai1": "조개방패는 밀물을 등에 얹는다. 칼이 닿으면 물결이 받고, 전선이 잠시 잔잔해진다.",
  "ai2": "얼음창은 창날에 호수를 얼린다. 관통하는 한기가 방패를 스치면, 하얀 금이 남는다.",
  "ai3": "상어의턱뼈는 심해의 식탐이다. 흡혈처럼 빨아들인 기운이, 칼자루를 통해 주인에게 돌아온다.",
  "ai4": "진주방패는 운의 개수만큼 빛난다. 코인이 앉을수록 방패가 두꺼워지고, 파도가 등을 지탱한다.",
  "ai5": "산호검은 산호초의 날을 빌렸다. 돌파하는 검선이 성벽을 스쳐도, 산호는 다시 자란다.",
  "ai6": "인어의하프는 물결로 멜로디를 짠다. 혼란의 음이 울리면, 칼끝과 발걸음이 같은 박자를 잃는다.",
  "li1": "소생초는 이슬을 잎에 가뒀다. 상처 위에 얹으면 먼지가 걷히고, 숨이 다시 고르게 선다.",
  "li2": "별목걸이는 밤하늘의 보호다. 가슴에 닿으면 숨이 두꺼워지고, 빛이 먼저 칼을 받는다.",
  "li3": "성스러운주화는 오늘의 운을 기도로 닦는다. 앞면이 더 자주 빛나며, 전선이 짧게 안심한다.",
  "li4": "환상의거울은 칼날을 빛으로 비춘다. 보호의 장막이 내려앉으면, 적이 제 그림자를 의심한다.",
  "li5": "아이언실드는 서약을 철로 주조했다. 방패가 두꺼워질수록 보호의 광채가 또렷해진다.",
  "li6": "블레스트아머는 축복을 갑옷으로 입힌다. 쓰러져도 환생처럼 다시 일어나, 성소의 온기를 지킨다.",
  "di1": "저주의인형은 남의 이름을 바늘로 쓴다. 약화의 실이 당겨지면, 강한 팔도 잠깐 풀린다.",
  "di2": "피의망토는 달빛보다 진한 붉은색이다. 흡혈의 자락이 스치면, 적의 기운이 옷깃으로 스며든다.",
  "di3": "흑마법서는 빼앗는 법을 페이지마다 적었다. 강탈의 문장이 열리면, 숨이 그림자 쪽으로 기운다.",
  "di4": "조작된주화는 모든 앞면을 황금으로 물들인다. 운의 색깔이 바뀌는 순간, 전장이 한쪽으로 기울다.",
  "di5": "사신의낫은 이름을 거두는 곡선이다. 관통하는 한 자락에, 횃불이 먼저 숨을 죽인다.",
  "di6": "다크아머는 공허로 짠 갑옷이다. 보호의 어둠이 두꺼워질수록, 빛조차 예의를 차린다.",
  "coin": "손바닥만 한 약속의 조각. 뒤집히는 순간 오늘의 숨이 한 뼘 길어지고, 전장의 템포가 잠깐 열린다."
};
