// Fantasy Arena — minion-only overlay (conversation source)
// 마법/아이템 없음. atkSkill/ability 없음. cost=확정. 공방체·코인=임시.
const MINIONS = [
  { id:"e1", tribe:"earth", name:"놀", cost:1, type:"minion", atk:1, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e2", tribe:"earth", name:"대지술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e3", tribe:"earth", name:"그린드래곤", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e4", tribe:"earth", name:"드라이어드", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e5", tribe:"earth", name:"드워프병사", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e6", tribe:"earth", name:"만드라고라", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e7", tribe:"earth", name:"샌드맨", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e8", tribe:"earth", name:"나무궁수", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e9", tribe:"earth", name:"오크", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e10", tribe:"earth", name:"드워프대장", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e12", tribe:"earth", name:"스톤골렘", cost:3, type:"minion", atk:1, def:2, hp:5, atkC:0, defC:1, hpC:1, text:"" },
  { id:"e13", tribe:"earth", name:"마운록", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e14", tribe:"earth", name:"마초", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e15", tribe:"earth", name:"암석창병", cost:1, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e16", tribe:"earth", name:"켄타우로스", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e17", tribe:"earth", name:"고르곤", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e18", tribe:"earth", name:"대지의 정령", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e19", tribe:"earth", name:"곽가", cost:8, type:"minion", atk:8, def:3, hp:9, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e20", tribe:"earth", name:"베헤모스", cost:6, type:"minion", atk:6, def:5, hp:10, atkC:0, defC:0, hpC:2, text:"" },
  { id:"e21", tribe:"earth", name:"록마운틴킹", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e22", tribe:"earth", name:"스핑크스", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e23", tribe:"earth", name:"조조", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e24", tribe:"earth", name:"티라노", cost:4, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e25", tribe:"earth", name:"대지자이언트", cost:6, type:"minion", atk:4, def:4, hp:8, atkC:0, defC:0, hpC:2, text:"" },
  { id:"e26", tribe:"earth", name:"사이클롭스", cost:6, type:"minion", atk:4, def:4, hp:8, atkC:0, defC:0, hpC:2, text:"" },
  { id:"e27", tribe:"earth", name:"샌드웜", cost:5, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"e28", tribe:"earth", name:"이끼방패병", cost:1, type:"minion", atk:1, def:2, hp:4, atkC:0, defC:1, hpC:0, text:"" },
  { id:"f1", tribe:"fire", name:"레드드래곤", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f2", tribe:"fire", name:"불꽃궁수", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f3", tribe:"fire", name:"임프", cost:1, type:"minion", atk:1, def:0, hp:1, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f4", tribe:"fire", name:"고블린", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f5", tribe:"fire", name:"불꽃여우", cost:2, type:"minion", atk:2, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f6", tribe:"fire", name:"가후", cost:8, type:"minion", atk:8, def:3, hp:9, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f7", tribe:"fire", name:"샐러맨더", cost:2, type:"minion", atk:2, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f8", tribe:"fire", name:"용암술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f9", tribe:"fire", name:"용암늑대", cost:2, type:"minion", atk:2, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f10", tribe:"fire", name:"헬하운드", cost:3, type:"minion", atk:2, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f11", tribe:"fire", name:"바바리안", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f12", tribe:"fire", name:"여령기", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f13", tribe:"fire", name:"파이어골렘", cost:3, type:"minion", atk:1, def:2, hp:5, atkC:0, defC:1, hpC:1, text:"" },
  { id:"f14", tribe:"fire", name:"폭염방패병", cost:1, type:"minion", atk:1, def:2, hp:4, atkC:0, defC:1, hpC:0, text:"" },
  { id:"f15", tribe:"fire", name:"장비", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f16", tribe:"fire", name:"미노타우로스", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f17", tribe:"fire", name:"불의 정령", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f18", tribe:"fire", name:"이프리트", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f19", tribe:"fire", name:"케르베로스", cost:5, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f20", tribe:"fire", name:"데빌", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f21", tribe:"fire", name:"화염창병", cost:1, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f22", tribe:"fire", name:"하후돈", cost:7, type:"minion", atk:7, def:2, hp:8, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f23", tribe:"fire", name:"발록", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f24", tribe:"fire", name:"키메라", cost:6, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f25", tribe:"fire", name:"타이폰", cost:6, type:"minion", atk:8, def:3, hp:9, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f26", tribe:"fire", name:"피닉스", cost:5, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"f27", tribe:"fire", name:"화염자이언트", cost:6, type:"minion", atk:4, def:4, hp:8, atkC:0, defC:0, hpC:2, text:"" },
  { id:"n1", tribe:"wind", name:"깃털도마뱀", cost:2, type:"minion", atk:1, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n2", tribe:"wind", name:"조운", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n3", tribe:"wind", name:"질풍술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n4", tribe:"wind", name:"픽시", cost:1, type:"minion", atk:1, def:0, hp:1, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n5", tribe:"wind", name:"구름사슴", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n6", tribe:"wind", name:"매사냥꾼", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n7", tribe:"wind", name:"바람늑대", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n8", tribe:"wind", name:"선풍무사", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n9", tribe:"wind", name:"손상향", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n10", tribe:"wind", name:"하피", cost:2, type:"minion", atk:2, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n11", tribe:"wind", name:"그리핀", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n12", tribe:"wind", name:"윈드골렘", cost:3, type:"minion", atk:1, def:2, hp:5, atkC:0, defC:1, hpC:1, text:"" },
  { id:"n13", tribe:"wind", name:"폭풍드래곤", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n14", tribe:"wind", name:"폭풍창병", cost:1, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n15", tribe:"wind", name:"회오리무희", cost:5, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n16", tribe:"wind", name:"가루다", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n17", tribe:"wind", name:"바람의 정령", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n18", tribe:"wind", name:"회오리궁수", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n19", tribe:"wind", name:"페가수스", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n20", tribe:"wind", name:"호크라이더", cost:5, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n21", tribe:"wind", name:"구름방패병", cost:1, type:"minion", atk:1, def:2, hp:4, atkC:0, defC:1, hpC:0, text:"" },
  { id:"n23", tribe:"wind", name:"템페스트", cost:5, type:"minion", atk:6, def:1, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n24", tribe:"wind", name:"폭풍자이언트", cost:6, type:"minion", atk:5, def:4, hp:9, atkC:0, defC:0, hpC:2, text:"" },
  { id:"n25", tribe:"wind", name:"썬더버드", cost:6, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n26", tribe:"wind", name:"와이번", cost:6, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n27", tribe:"wind", name:"태사자", cost:7, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"n28", tribe:"wind", name:"육손", cost:8, type:"minion", atk:8, def:3, hp:9, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a1", tribe:"water", name:"관우", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a2", tribe:"water", name:"슬라임", cost:1, type:"minion", atk:1, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a3", tribe:"water", name:"연못거북", cost:2, type:"minion", atk:1, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a4", tribe:"water", name:"피라냐", cost:2, type:"minion", atk:1, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a5", tribe:"water", name:"나가", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a6", tribe:"water", name:"독두꺼비", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a7", tribe:"water", name:"리자드맨", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a8", tribe:"water", name:"빙결술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a9", tribe:"water", name:"전기해파리", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a10", tribe:"water", name:"파도창병", cost:1, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a11", tribe:"water", name:"심해방패병", cost:1, type:"minion", atk:1, def:2, hp:4, atkC:0, defC:1, hpC:0, text:"" },
  { id:"a12", tribe:"water", name:"머메이드", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a13", tribe:"water", name:"대교", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a14", tribe:"water", name:"아이스드래곤", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a15", tribe:"water", name:"손권", cost:4, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a16", tribe:"water", name:"아이스골렘", cost:3, type:"minion", atk:1, def:2, hp:5, atkC:0, defC:1, hpC:1, text:"" },
  { id:"a17", tribe:"water", name:"물의 정령", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a18", tribe:"water", name:"세이렌", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a19", tribe:"water", name:"켈피", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a20", tribe:"water", name:"시서펜트", cost:6, type:"minion", atk:8, def:3, hp:9, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a22", tribe:"water", name:"강가무녀", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a23", tribe:"water", name:"주유", cost:8, type:"minion", atk:8, def:3, hp:9, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a24", tribe:"water", name:"심해상어", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a25", tribe:"water", name:"얼음궁수", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a26", tribe:"water", name:"바다자이언트", cost:6, type:"minion", atk:4, def:4, hp:8, atkC:0, defC:0, hpC:2, text:"" },
  { id:"a27", tribe:"water", name:"크라켄", cost:6, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"a28", tribe:"water", name:"히드라", cost:5, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l1", tribe:"light", name:"태양궁수", cost:2, type:"minion", atk:1, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l2", tribe:"light", name:"빛나방", cost:1, type:"minion", atk:1, def:0, hp:1, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l3", tribe:"light", name:"치유술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l4", tribe:"light", name:"제갈량", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l5", tribe:"light", name:"축복방패병", cost:1, type:"minion", atk:1, def:2, hp:4, atkC:0, defC:1, hpC:0, text:"" },
  { id:"l6", tribe:"light", name:"빛늑대", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l7", tribe:"light", name:"성녀", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l8", tribe:"light", name:"신관", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l9", tribe:"light", name:"예언자", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l10", tribe:"light", name:"황충", cost:8, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l11", tribe:"light", name:"골드골렘", cost:3, type:"minion", atk:1, def:2, hp:5, atkC:0, defC:1, hpC:1, text:"" },
  { id:"l12", tribe:"light", name:"성기사", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l13", tribe:"light", name:"광명창병", cost:1, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l14", tribe:"light", name:"수도사", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l15", tribe:"light", name:"인챈터", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l16", tribe:"light", name:"금빛사자", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l18", tribe:"light", name:"십자군", cost:3, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l19", tribe:"light", name:"유비", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l20", tribe:"light", name:"타이탄", cost:6, type:"minion", atk:5, def:4, hp:9, atkC:0, defC:0, hpC:2, text:"" },
  { id:"l21", tribe:"light", name:"발키리", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l22", tribe:"light", name:"빛의 정령", cost:4, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l23", tribe:"light", name:"신전기사", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l24", tribe:"light", name:"유니콘", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l26", tribe:"light", name:"골드드래곤", cost:9, type:"minion", atk:8, def:3, hp:9, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l27", tribe:"light", name:"엔젤", cost:5, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l28", tribe:"light", name:"태양자이언트", cost:6, type:"minion", atk:4, def:4, hp:8, atkC:0, defC:0, hpC:2, text:"" },
  { id:"d1", tribe:"dark", name:"로그", cost:2, type:"minion", atk:1, def:0, hp:1, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d2", tribe:"dark", name:"사마의", cost:8, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"d3", tribe:"dark", name:"그림자궁수", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d4", tribe:"dark", name:"해골나방", cost:1, type:"minion", atk:1, def:0, hp:2, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d5", tribe:"dark", name:"고스트", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d6", tribe:"dark", name:"구울", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d7", tribe:"dark", name:"여포", cost:9, type:"minion", atk:9, def:3, hp:10, atkC:0, defC:0, hpC:1, text:"" },
  { id:"d8", tribe:"dark", name:"암흑창병", cost:1, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d9", tribe:"dark", name:"스켈레톤", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d10", tribe:"dark", name:"심연술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d11", tribe:"dark", name:"초선", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d12", tribe:"dark", name:"다크골렘", cost:3, type:"minion", atk:1, def:2, hp:5, atkC:0, defC:1, hpC:1, text:"" },
  { id:"d13", tribe:"dark", name:"미라", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"d14", tribe:"dark", name:"서큐버스", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"d15", tribe:"dark", name:"나이트메어", cost:4, type:"minion", atk:4, def:1, hp:5, atkC:0, defC:0, hpC:1, text:"" },
  { id:"d16", tribe:"dark", name:"듀라한", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:1, defC:0, hpC:0, text:"일반공격" },
  { id:"d17", tribe:"dark", name:"저주방패병", cost:1, type:"minion", atk:1, def:2, hp:4, atkC:0, defC:1, hpC:0, text:"" },
  { id:"d18", tribe:"dark", name:"장료", cost:6, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d20", tribe:"dark", name:"가고일", cost:5, type:"minion", atk:5, def:2, hp:4, atkC:1, defC:0, hpC:0, text:"일반공격" },
  { id:"d21", tribe:"dark", name:"네크로맨서", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d22", tribe:"dark", name:"만티코어", cost:5, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d23", tribe:"dark", name:"리치", cost:7, type:"minion", atk:7, def:2, hp:8, atkC:0, defC:0, hpC:1, text:"" },
  { id:"d24", tribe:"dark", name:"암흑의 정령", cost:4, type:"minion", atk:5, def:2, hp:6, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d25", tribe:"dark", name:"뱀파이어", cost:5, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d26", tribe:"dark", name:"본맘모스", cost:6, type:"minion", atk:6, def:2, hp:7, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d27", tribe:"dark", name:"블랙드래곤", cost:9, type:"minion", atk:8, def:3, hp:9, atkC:0, defC:0, hpC:1, text:"" },
  { id:"d28", tribe:"dark", name:"암흑자이언트", cost:6, type:"minion", atk:4, def:4, hp:8, atkC:0, defC:0, hpC:2, text:"" },
  { id:"e11", tribe:"earth", name:"숲요정", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"f28", tribe:"fire", name:"불꽃요정", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"n22", tribe:"wind", name:"실프", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"a21", tribe:"water", name:"물의요정", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l25", tribe:"light", name:"광휘요정", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"d19", tribe:"dark", name:"그림자요정", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"l17", tribe:"light", name:"황월영", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:0, hpC:0, text:"" },
];
// cards-data.js 의 CARDS에서 옛 유닛만 빼고, 확정 유닛 168장 + 주문/아이템 유지
(function overlayMinions() {
  if (typeof CARDS === "undefined") return;
  const keep = CARDS.filter(c => c && c.type !== "minion");
  CARDS.splice(0, CARDS.length, ...MINIONS, ...keep);
  // CARD_MAP was built in cards-data.js before this overlay — rebuild so every
  // CARDS id resolves correctly for cloneCard / deck builder / game.js.
  // Token minions (wiped by overlay — re-add for hero power / summon_islands)
  const TOKENS = [
    { id:"e40", tribe:"earth", name:"섬의파편", cost:1, type:"minion", token:true, atk:1, def:0, hp:2, atkC:0, defC:0, hpC:0, rarity:"common", text:"토큰" },
    { id:"recruit", tribe:"earth", name:"암석", cost:1, type:"minion", token:true, atk:1, def:0, hp:2, atkC:0, defC:0, hpC:0, text:"영웅 능력" },
  ];
  for (const t of TOKENS) {
    if (!CARDS.some(c => c && c.id === t.id)) CARDS.push(t);
  }
  if (typeof CARD_MAP !== "undefined") {
    for (const k of Object.keys(CARD_MAP)) delete CARD_MAP[k];
    for (const c of CARDS) {
      if (c && c.id) CARD_MAP[c.id] = c;
    }
  }
})();

