
const TRIBES = [
  { id: "earth", name: "땅", en: "Earth", icon: "🪨", open: true, color: "#8b5a2b" },
  { id: "fire", name: "불", en: "Fire", icon: "🔥", open: true, color: "#d44512" },
  { id: "wind", name: "바람", en: "Wind", icon: "🌬️", open: true, color: "#7ec8c8" },
  { id: "water", name: "물", en: "Water", icon: "💧", open: true, color: "#2a7ad4" },
  { id: "dark", name: "암흑", en: "Dark", icon: "🌑", open: true, color: "#5a2a7a" },
  { id: "light", name: "빛", en: "Light", icon: "✨", open: true, color: "#f0e0a0" },
];

const TRIBE_ICONS = {
  earth:"assets/img/icons/earth.jpg",
  fire:"assets/img/icons/fire.jpg",
  wind:"assets/img/icons/wind.jpg",
  water:"assets/img/icons/water.jpg",
  light:"assets/img/icons/light.jpg",
  dark:"assets/img/icons/dark.jpg",
  metal:"assets/img/frames/unit/metal.png"
};
const HUD_UI = {
  board:"assets/img/hud/board.jpg",
  hp:"assets/img/hud/hp.jpg",
  mana:"assets/img/hud/mana.jpg",
  deck:"assets/img/hud/deck.jpg"
};
const COIN_PLUS = "assets/img/coins/plus.png";
const COIN_MINUS = "assets/img/coins/minus.png";

const CARDS = [
// === UNITS (source of truth: 판타지아레나_유닛목록.xlsx + art {id}.jpg; never add orphan e29+ units here) ===
// 유닛 단일 소스 — 유닛목록.xlsx + art/{id}.jpg 가 정본. e29+ 고아 유닛 추가 금지.
  { id:"e1", tribe:"earth", name:"놀", cost:1, type:"minion", atk:1, def:0, hp:3, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e2", tribe:"earth", name:"대지술사", cost:4, type:"minion", atk:3, def:0, hp:6, atkC:0, defC:0, hpC:2, text:"" },
  { id:"e3", tribe:"earth", name:"그린드래곤", cost:9, type:"minion", atk:5, def:0, hp:11, atkC:-2, defC:0, hpC:2, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"e4", tribe:"earth", name:"드라이어드", cost:2, type:"minion", atk:0, def:0, hp:5, atkC:1, defC:0, hpC:1, text:"" },
  { id:"e5", tribe:"earth", name:"드워프병사", cost:2, type:"minion", atk:2, def:0, hp:4, atkC:-2, defC:0, hpC:2, text:"" },
  { id:"e6", tribe:"earth", name:"만드라고라", cost:2, type:"minion", atk:1, def:0, hp:3, atkC:0, defC:0, hpC:3, atkSkill:7, text:"약화공격" },
  { id:"e7", tribe:"earth", name:"샌드맨", cost:2, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:1, text:"" },
  { id:"e8", tribe:"earth", name:"나무궁수", cost:2, type:"minion", atk:1, def:1, hp:2, atkC:0, defC:0, hpC:1, atkSkill:2, text:"관통공격" },
  { id:"e9", tribe:"earth", name:"오크", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:-1, defC:0, hpC:0, atkSkill:4, text:"연속공격" },
  { id:"e10", tribe:"earth", name:"드워프대장", cost:3, type:"minion", atk:2, def:1, hp:4, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e12", tribe:"earth", name:"스톤골렘", cost:3, type:"minion", atk:2, def:0, hp:6, atkC:-1, defC:0, hpC:1, text:"" },
  { id:"e13", tribe:"earth", name:"마운록", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:0, defC:0, hpC:1, rarity:"uncommon", ability:"복수", text:"복수" },
  { id:"e14", tribe:"earth", name:"마초", cost:10, type:"minion", atk:7, def:1, hp:11, atkC:-1, defC:-1, hpC:1, rarity:"legendary", atkSkill:10, ability:"복수", text:"돌파공격 · 복수" },
  { id:"e15", tribe:"earth", name:"암석창병", cost:1, type:"minion", atk:3, def:0, hp:1, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e16", tribe:"earth", name:"켄타우로스", cost:3, type:"minion", atk:2, def:1, hp:3, atkC:-1, defC:-1, hpC:1, atkSkill:3, text:"돌진공격" },
  { id:"e17", tribe:"earth", name:"고르곤", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:0, defC:0, hpC:2, atkSkill:8, text:"석화공격" },
  { id:"e18", tribe:"earth", name:"대지의 정령", cost:4, type:"minion", atk:2, def:0, hp:6, atkC:-2, defC:0, hpC:2, ability:"유언", text:"유언" },
  { id:"e19", tribe:"earth", name:"곽가", cost:8, type:"minion", atk:3, def:1, hp:10, atkC:-1, defC:-1, hpC:1, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"e20", tribe:"earth", name:"베헤모스", cost:6, type:"minion", atk:3, def:2, hp:7, atkC:-2, defC:-2, hpC:2, rarity:"rare", atkSkill:3, text:"돌진공격" },
  { id:"e21", tribe:"earth", name:"록마운틴킹", cost:5, type:"minion", atk:3, def:0, hp:8, atkC:-1, defC:0, hpC:1, rarity:"uncommon", ability:"복수", text:"복수" },
  { id:"e22", tribe:"earth", name:"스핑크스", cost:5, type:"minion", atk:3, def:0, hp:8, atkC:0, defC:0, hpC:1, rarity:"uncommon", atkSkill:11, text:"혼란공격" },
  { id:"e23", tribe:"earth", name:"조조", cost:5, type:"minion", atk:3, def:1, hp:5, atkC:-1, defC:0, hpC:1, rarity:"rare", ability:"강탈", text:"강탈" },
  { id:"e24", tribe:"earth", name:"티라노", cost:4, type:"minion", atk:2, def:1, hp:6, atkC:-1, defC:-1, hpC:1, atkSkill:10, text:"돌파공격" },
  { id:"e25", tribe:"earth", name:"대지자이언트", cost:6, type:"minion", atk:3, def:0, hp:9, atkC:-3, defC:0, hpC:3, rarity:"uncommon", ability:"보호", text:"보호" },
  { id:"e26", tribe:"earth", name:"사이클롭스", cost:6, type:"minion", atk:3, def:0, hp:8, atkC:-2, defC:0, hpC:2, rarity:"uncommon", atkSkill:5, text:"치명공격" },
  { id:"e27", tribe:"earth", name:"샌드웜", cost:5, type:"minion", atk:2, def:0, hp:6, atkC:2, defC:2, hpC:2, rarity:"uncommon", atkSkill:2, text:"관통공격" },
  { id:"e28", tribe:"earth", name:"이끼방패병", cost:1, type:"minion", atk:2, def:1, hp:1, atkC:0, defC:-1, hpC:1, text:"" },
  { id:"f1", tribe:"fire", name:"레드드래곤", cost:9, type:"minion", atk:10, def:0, hp:10, atkC:-4, defC:0, hpC:-4, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"f2", tribe:"fire", name:"불꽃궁수", cost:2, type:"minion", atk:5, def:0, hp:2, atkC:-3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"f3", tribe:"fire", name:"임프", cost:1, type:"minion", atk:1, def:0, hp:4, atkC:-1, defC:0, hpC:0, text:"" },
  { id:"f4", tribe:"fire", name:"고블린", cost:2, type:"minion", atk:1, def:2, hp:3, atkC:-1, defC:-1, hpC:-1, text:"" },
  { id:"f5", tribe:"fire", name:"불꽃여우", cost:2, type:"minion", atk:3, def:1, hp:2, atkC:-1, defC:-1, hpC:0, atkSkill:10, text:"돌파공격" },
  { id:"f6", tribe:"fire", name:"가후", cost:8, type:"minion", atk:7, def:1, hp:7, atkC:-4, defC:0, hpC:0, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"f7", tribe:"fire", name:"샐러맨더", cost:2, type:"minion", atk:4, def:0, hp:3, atkC:-4, defC:0, hpC:0, atkSkill:6, text:"흡혈공격" },
  { id:"f8", tribe:"fire", name:"용암술사", cost:4, type:"minion", atk:6, def:1, hp:5, atkC:-4, defC:0, hpC:-4, ability:"유언", text:"유언" },
  { id:"f9", tribe:"fire", name:"용암늑대", cost:2, type:"minion", atk:2, def:1, hp:2, atkC:-1, defC:-1, hpC:-1, atkSkill:3, text:"돌진공격" },
  { id:"f10", tribe:"fire", name:"헬하운드", cost:3, type:"minion", atk:4, def:0, hp:5, atkC:-4, defC:0, hpC:-4, atkSkill:4, text:"연속공격" },
  { id:"f11", tribe:"fire", name:"바바리안", cost:3, type:"minion", atk:3, def:1, hp:3, atkC:-2, defC:0, hpC:-2, atkSkill:3, text:"돌진공격" },
  { id:"f12", tribe:"fire", name:"여령기", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:-2, defC:0, hpC:0, rarity:"rare", atkSkill:5, text:"치명공격" },
  { id:"f13", tribe:"fire", name:"파이어골렘", cost:3, type:"minion", atk:4, def:2, hp:3, atkC:-2, defC:-2, hpC:0, text:"" },
  { id:"f14", tribe:"fire", name:"폭염방패병", cost:1, type:"minion", atk:1, def:0, hp:1, atkC:-1, defC:1, hpC:0, ability:"보호", text:"보호" },
  { id:"f15", tribe:"fire", name:"장비", cost:10, type:"minion", atk:10, def:1, hp:9, atkC:-5, defC:0, hpC:-5, rarity:"legendary", atkSkill:4, ability:"면역", text:"연속공격 · 면역" },
  { id:"f16", tribe:"fire", name:"미노타우로스", cost:4, type:"minion", atk:5, def:0, hp:5, atkC:-5, defC:0, hpC:0, atkSkill:4, text:"연속공격" },
  { id:"f17", tribe:"fire", name:"불의 정령", cost:4, type:"minion", atk:5, def:2, hp:5, atkC:-2, defC:-2, hpC:0, text:"" },
  { id:"f18", tribe:"fire", name:"이프리트", cost:4, type:"minion", atk:4, def:0, hp:6, atkC:-3, defC:0, hpC:-3, atkSkill:5, text:"치명공격" },
  { id:"f19", tribe:"fire", name:"케르베로스", cost:5, type:"minion", atk:6, def:0, hp:6, atkC:-4, defC:0, hpC:0, rarity:"uncommon", atkSkill:4, text:"연속공격" },
  { id:"f20", tribe:"fire", name:"데빌", cost:3, type:"minion", atk:6, def:0, hp:5, atkC:-4, defC:0, hpC:-4, atkSkill:11, text:"혼란공격" },
  { id:"f21", tribe:"fire", name:"화염창병", cost:1, type:"minion", atk:4, def:0, hp:1, atkC:-3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"f22", tribe:"fire", name:"하후돈", cost:7, type:"minion", atk:9, def:0, hp:9, atkC:-5, defC:0, hpC:0, rarity:"rare", atkSkill:6, text:"흡혈공격" },
  { id:"f23", tribe:"fire", name:"발록", cost:5, type:"minion", atk:7, def:0, hp:6, atkC:-4, defC:0, hpC:-4, rarity:"uncommon", atkSkill:9, text:"광역공격" },
  { id:"f24", tribe:"fire", name:"키메라", cost:6, type:"minion", atk:7, def:2, hp:7, atkC:-2, defC:-2, hpC:-2, rarity:"uncommon", atkSkill:10, text:"돌파공격" },
  { id:"f25", tribe:"fire", name:"타이폰", cost:6, type:"minion", atk:8, def:0, hp:8, atkC:-5, defC:0, hpC:0, rarity:"rare", atkSkill:11, text:"혼란공격" },
  { id:"f26", tribe:"fire", name:"피닉스", cost:5, type:"minion", atk:7, def:1, hp:5, atkC:-3, defC:0, hpC:-3, rarity:"rare", ability:"환생", text:"환생" },
  { id:"f27", tribe:"fire", name:"화염자이언트", cost:6, type:"minion", atk:7, def:2, hp:6, atkC:-5, defC:0, hpC:-5, rarity:"uncommon", atkSkill:3, text:"돌진공격" },
  { id:"n1", tribe:"wind", name:"깃털도마뱀", cost:2, type:"minion", atk:2, def:0, hp:5, atkC:-2, defC:0, hpC:0, text:"" },
  { id:"n2", tribe:"wind", name:"조운", cost:10, type:"minion", atk:7, def:1, hp:9, atkC:-1, defC:-1, hpC:-1, rarity:"legendary", atkSkill:4, ability:"면역", text:"연속공격 · 면역" },
  { id:"n3", tribe:"wind", name:"질풍술사", cost:4, type:"minion", atk:5, def:1, hp:5, atkC:-1, defC:-1, hpC:0, text:"" },
  { id:"n4", tribe:"wind", name:"픽시", cost:1, type:"minion", atk:1, def:0, hp:4, atkC:0, defC:0, hpC:-1, text:"" },
  { id:"n5", tribe:"wind", name:"구름사슴", cost:2, type:"minion", atk:3, def:1, hp:3, atkC:-1, defC:-1, hpC:0, text:"" },
  { id:"n6", tribe:"wind", name:"매사냥꾼", cost:3, type:"minion", atk:4, def:0, hp:4, atkC:-1, defC:1, hpC:0, text:"" },
  { id:"n7", tribe:"wind", name:"바람늑대", cost:2, type:"minion", atk:3, def:0, hp:3, atkC:-1, defC:0, hpC:-1, atkSkill:10, text:"돌파공격" },
  { id:"n8", tribe:"wind", name:"선풍무사", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:0, defC:0, hpC:-1, atkSkill:4, text:"연속공격" },
  { id:"n9", tribe:"wind", name:"손상향", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:0, hpC:0, rarity:"rare", atkSkill:2, text:"관통공격" },
  { id:"n10", tribe:"wind", name:"하피", cost:2, type:"minion", atk:2, def:0, hp:4, atkC:0, defC:0, hpC:-1, atkSkill:7, text:"약화공격" },
  { id:"n11", tribe:"wind", name:"그리핀", cost:3, type:"minion", atk:3, def:1, hp:3, atkC:0, defC:-1, hpC:-1, atkSkill:3, text:"돌진공격" },
  { id:"n12", tribe:"wind", name:"윈드골렘", cost:3, type:"minion", atk:4, def:0, hp:3, atkC:0, defC:0, hpC:-2, rarity:"uncommon", ability:"면역", text:"면역" },
  { id:"n13", tribe:"wind", name:"폭풍드래곤", cost:9, type:"minion", atk:9, def:0, hp:8, atkC:-1, defC:0, hpC:-1, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"n14", tribe:"wind", name:"폭풍창병", cost:1, type:"minion", atk:3, def:0, hp:1, atkC:-1, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"n15", tribe:"wind", name:"회오리무희", cost:5, type:"minion", atk:6, def:0, hp:6, atkC:-1, defC:0, hpC:-1, rarity:"uncommon", atkSkill:11, text:"혼란공격" },
  { id:"n16", tribe:"wind", name:"가루다", cost:4, type:"minion", atk:4, def:0, hp:4, atkC:-1, defC:0, hpC:-1, atkSkill:5, text:"치명공격" },
  { id:"n17", tribe:"wind", name:"바람의 정령", cost:4, type:"minion", atk:5, def:0, hp:5, atkC:-1, defC:0, hpC:-1, ability:"유언", text:"유언" },
  { id:"n18", tribe:"wind", name:"회오리궁수", cost:2, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:-1, atkSkill:2, text:"관통공격" },
  { id:"n19", tribe:"wind", name:"페가수스", cost:4, type:"minion", atk:4, def:2, hp:4, atkC:-2, defC:-2, hpC:-2, atkSkill:3, text:"돌진공격" },
  { id:"n20", tribe:"wind", name:"호크라이더", cost:5, type:"minion", atk:6, def:0, hp:7, atkC:-1, defC:0, hpC:-1, rarity:"uncommon", atkSkill:10, text:"돌파공격" },
  { id:"n21", tribe:"wind", name:"구름방패병", cost:1, type:"minion", atk:2, def:1, hp:1, atkC:-1, defC:0, hpC:0, text:"" },
  { id:"n23", tribe:"wind", name:"템페스트", cost:5, type:"minion", atk:4, def:0, hp:5, atkC:-1, defC:0, hpC:0, rarity:"uncommon", atkSkill:9, text:"광역공격" },
  { id:"n24", tribe:"wind", name:"폭풍자이언트", cost:6, type:"minion", atk:7, def:0, hp:6, atkC:-1, defC:0, hpC:-1, rarity:"uncommon", atkSkill:4, text:"연속공격" },
  { id:"n25", tribe:"wind", name:"썬더버드", cost:6, type:"minion", atk:4, def:0, hp:7, atkC:-1, defC:1, hpC:-1, rarity:"uncommon", atkSkill:5, text:"치명공격" },
  { id:"n26", tribe:"wind", name:"와이번", cost:6, type:"minion", atk:8, def:0, hp:7, atkC:-1, defC:0, hpC:-1, rarity:"rare", atkSkill:2, text:"관통공격" },
  { id:"n27", tribe:"wind", name:"태사자", cost:7, type:"minion", atk:7, def:1, hp:6, atkC:1, defC:-1, hpC:-1, rarity:"rare", atkSkill:4, text:"연속공격" },
  { id:"n28", tribe:"wind", name:"육손", cost:8, type:"minion", atk:6, def:1, hp:8, atkC:0, defC:-1, hpC:-1, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"a1", tribe:"water", name:"관우", cost:10, type:"minion", atk:4, def:3, hp:5, atkC:-1, defC:1, hpC:-1, rarity:"legendary", atkSkill:3, ability:"강탈", text:"돌진공격 · 강탈" },
  { id:"a2", tribe:"water", name:"슬라임", cost:1, type:"minion", atk:1, def:1, hp:1, atkC:-1, defC:1, hpC:0, text:"" },
  { id:"a3", tribe:"water", name:"연못거북", cost:2, type:"minion", atk:2, def:1, hp:2, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"a4", tribe:"water", name:"피라냐", cost:2, type:"minion", atk:2, def:1, hp:2, atkC:-1, defC:1, hpC:0, text:"" },
  { id:"a5", tribe:"water", name:"나가", cost:2, type:"minion", atk:3, def:0, hp:1, atkC:-3, defC:3, hpC:0, atkSkill:7, text:"약화공격" },
  { id:"a6", tribe:"water", name:"독두꺼비", cost:2, type:"minion", atk:1, def:1, hp:3, atkC:-1, defC:1, hpC:-1, text:"" },
  { id:"a7", tribe:"water", name:"리자드맨", cost:3, type:"minion", atk:2, def:1, hp:2, atkC:0, defC:1, hpC:-1, atkSkill:3, text:"돌진공격" },
  { id:"a8", tribe:"water", name:"빙결술사", cost:4, type:"minion", atk:2, def:2, hp:1, atkC:-1, defC:1, hpC:0, atkSkill:8, text:"석화공격" },
  { id:"a9", tribe:"water", name:"전기해파리", cost:3, type:"minion", atk:2, def:1, hp:2, atkC:1, defC:1, hpC:-1, atkSkill:11, text:"혼란공격" },
  { id:"a10", tribe:"water", name:"파도창병", cost:1, type:"minion", atk:2, def:0, hp:1, atkC:-1, defC:1, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"a11", tribe:"water", name:"심해방패병", cost:1, type:"minion", atk:0, def:0, hp:1, atkC:1, defC:1, hpC:0, ability:"보호", text:"보호" },
  { id:"a12", tribe:"water", name:"머메이드", cost:3, type:"minion", atk:1, def:2, hp:1, atkC:-1, defC:1, hpC:0, atkSkill:6, text:"흡혈공격" },
  { id:"a13", tribe:"water", name:"대교", cost:3, type:"minion", atk:1, def:2, hp:2, atkC:-1, defC:1, hpC:-1, rarity:"rare", atkSkill:7, text:"약화공격" },
  { id:"a14", tribe:"water", name:"아이스드래곤", cost:9, type:"minion", atk:4, def:3, hp:4, atkC:-1, defC:1, hpC:-1, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"a15", tribe:"water", name:"손권", cost:4, type:"minion", atk:1, def:2, hp:2, atkC:-1, defC:1, hpC:0, rarity:"rare", ability:"강탈", text:"강탈" },
  { id:"a16", tribe:"water", name:"아이스골렘", cost:3, type:"minion", atk:3, def:1, hp:3, atkC:-2, defC:2, hpC:-2, text:"" },
  { id:"a17", tribe:"water", name:"물의 정령", cost:4, type:"minion", atk:2, def:2, hp:1, atkC:0, defC:1, hpC:0, ability:"유언", text:"유언" },
  { id:"a18", tribe:"water", name:"세이렌", cost:4, type:"minion", atk:2, def:1, hp:4, atkC:0, defC:2, hpC:-2, atkSkill:11, text:"혼란공격" },
  { id:"a19", tribe:"water", name:"켈피", cost:4, type:"minion", atk:3, def:2, hp:1, atkC:0, defC:1, hpC:0, atkSkill:10, text:"돌파공격" },
  { id:"a20", tribe:"water", name:"시서펜트", cost:6, type:"minion", atk:4, def:2, hp:4, atkC:-1, defC:1, hpC:-1, rarity:"uncommon", atkSkill:3, text:"돌진공격" },
  { id:"a22", tribe:"water", name:"강가무녀", cost:5, type:"minion", atk:4, def:2, hp:4, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"a23", tribe:"water", name:"주유", cost:8, type:"minion", atk:3, def:3, hp:3, atkC:-1, defC:1, hpC:0, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"a24", tribe:"water", name:"심해상어", cost:5, type:"minion", atk:4, def:2, hp:2, atkC:-2, defC:2, hpC:0, rarity:"uncommon", atkSkill:2, text:"관통공격" },
  { id:"a25", tribe:"water", name:"얼음궁수", cost:2, type:"minion", atk:1, def:0, hp:3, atkC:1, defC:1, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"a26", tribe:"water", name:"바다자이언트", cost:6, type:"minion", atk:5, def:2, hp:5, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"a27", tribe:"water", name:"크라켄", cost:6, type:"minion", atk:2, def:2, hp:3, atkC:-1, defC:1, hpC:0, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"a28", tribe:"water", name:"히드라", cost:5, type:"minion", atk:3, def:2, hp:2, atkC:-1, defC:1, hpC:-1, rarity:"uncommon", atkSkill:4, text:"연속공격" },
  { id:"l1", tribe:"light", name:"태양궁수", cost:2, type:"minion", atk:2, def:0, hp:2, atkC:3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"l2", tribe:"light", name:"빛나방", cost:1, type:"minion", atk:0, def:0, hp:3, atkC:1, defC:1, hpC:0, text:"" },
  { id:"l3", tribe:"light", name:"치유술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:1, hpC:1, ability:"유언", text:"유언" },
  { id:"l4", tribe:"light", name:"제갈량", cost:10, type:"minion", atk:4, def:0, hp:9, atkC:1, defC:1, hpC:1, rarity:"legendary", atkSkill:9, ability:"보호", text:"광역공격 · 보호" },
  { id:"l5", tribe:"light", name:"축복방패병", cost:1, type:"minion", atk:2, def:0, hp:1, atkC:1, defC:1, hpC:0, text:"" },
  { id:"l6", tribe:"light", name:"빛늑대", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:1, hpC:0, text:"" },
  { id:"l7", tribe:"light", name:"성녀", cost:2, type:"minion", atk:2, def:1, hp:1, atkC:0, defC:0, hpC:3, text:"" },
  { id:"l8", tribe:"light", name:"신관", cost:2, type:"minion", atk:1, def:0, hp:2, atkC:0, defC:3, hpC:0, text:"" },
  { id:"l9", tribe:"light", name:"예언자", cost:2, type:"minion", atk:3, def:0, hp:2, atkC:0, defC:1, hpC:1, text:"" },
  { id:"l10", tribe:"light", name:"황충", cost:8, type:"minion", atk:1, def:0, hp:9, atkC:3, defC:3, hpC:3, rarity:"rare", atkSkill:5, text:"치명공격" },
  { id:"l11", tribe:"light", name:"골드골렘", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:1, defC:1, hpC:1, text:"" },
  { id:"l12", tribe:"light", name:"성기사", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:0, defC:1, hpC:0, ability:"보호", text:"보호" },
  { id:"l13", tribe:"light", name:"광명창병", cost:1, type:"minion", atk:3, def:0, hp:1, atkC:1, defC:0, hpC:0, text:"" },
  { id:"l14", tribe:"light", name:"수도사", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:0, defC:0, hpC:5, text:"" },
  { id:"l15", tribe:"light", name:"인챈터", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:2, defC:0, hpC:0, text:"" },
  { id:"l16", tribe:"light", name:"금빛사자", cost:4, type:"minion", atk:4, def:0, hp:3, atkC:1, defC:1, hpC:1, ability:"보호", text:"보호" },
  { id:"l18", tribe:"light", name:"십자군", cost:3, type:"minion", atk:2, def:1, hp:2, atkC:1, defC:0, hpC:0, atkSkill:3, text:"돌진공격" },
  { id:"l19", tribe:"light", name:"유비", cost:4, type:"minion", atk:1, def:1, hp:4, atkC:1, defC:1, hpC:1, rarity:"rare", ability:"보호", text:"보호" },
  { id:"l20", tribe:"light", name:"타이탄", cost:6, type:"minion", atk:5, def:0, hp:6, atkC:1, defC:1, hpC:1, rarity:"rare", ability:"보호", text:"보호" },
  { id:"l21", tribe:"light", name:"발키리", cost:5, type:"minion", atk:4, def:0, hp:4, atkC:1, defC:0, hpC:1, rarity:"uncommon", atkSkill:5, text:"치명공격" },
  { id:"l22", tribe:"light", name:"빛의 정령", cost:4, type:"minion", atk:4, def:0, hp:3, atkC:2, defC:2, hpC:2, text:"" },
  { id:"l23", tribe:"light", name:"신전기사", cost:5, type:"minion", atk:4, def:0, hp:5, atkC:1, defC:1, hpC:1, rarity:"uncommon", ability:"보호", text:"보호" },
  { id:"l24", tribe:"light", name:"유니콘", cost:5, type:"minion", atk:5, def:0, hp:6, atkC:0, defC:1, hpC:1, text:"" },
  { id:"l26", tribe:"light", name:"골드드래곤", cost:9, type:"minion", atk:7, def:0, hp:7, atkC:1, defC:1, hpC:1, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"l27", tribe:"light", name:"엔젤", cost:5, type:"minion", atk:4, def:0, hp:4, atkC:1, defC:1, hpC:1, rarity:"rare", ability:"면역", text:"면역" },
  { id:"l28", tribe:"light", name:"태양자이언트", cost:6, type:"minion", atk:5, def:0, hp:5, atkC:1, defC:1, hpC:1, rarity:"uncommon", atkSkill:4, text:"연속공격" },
  { id:"d1", tribe:"dark", name:"로그", cost:2, type:"minion", atk:4, def:0, hp:1, atkC:-4, defC:0, hpC:4, atkSkill:10, text:"돌파공격" },
  { id:"d2", tribe:"dark", name:"사마의", cost:8, type:"minion", atk:6, def:0, hp:8, atkC:-5, defC:0, hpC:5, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"d3", tribe:"dark", name:"그림자궁수", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:0, defC:1, hpC:-1, atkSkill:2, text:"관통공격" },
  { id:"d4", tribe:"dark", name:"해골나방", cost:1, type:"minion", atk:1, def:0, hp:3, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"d5", tribe:"dark", name:"고스트", cost:2, type:"minion", atk:3, def:0, hp:2, atkC:-3, defC:0, hpC:3, atkSkill:11, text:"혼란공격" },
  { id:"d6", tribe:"dark", name:"구울", cost:4, type:"minion", atk:2, def:0, hp:2, atkC:4, defC:0, hpC:4, ability:"환생", text:"환생" },
  { id:"d7", tribe:"dark", name:"여포", cost:10, type:"minion", atk:11, def:1, hp:10, atkC:-5, defC:0, hpC:-5, rarity:"legendary", atkSkill:11, ability:"환생", text:"혼란공격 · 환생" },
  { id:"d8", tribe:"dark", name:"암흑창병", cost:1, type:"minion", atk:2, def:0, hp:1, atkC:1, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"d9", tribe:"dark", name:"스켈레톤", cost:2, type:"minion", atk:3, def:0, hp:3, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"d10", tribe:"dark", name:"심연술사", cost:4, type:"minion", atk:3, def:0, hp:3, atkC:5, defC:0, hpC:5, text:"" },
  { id:"d11", tribe:"dark", name:"초선", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:3, defC:0, hpC:-3, rarity:"rare", ability:"환생", text:"환생" },
  { id:"d12", tribe:"dark", name:"다크골렘", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:0, defC:3, hpC:-3, text:"" },
  { id:"d13", tribe:"dark", name:"미라", cost:3, type:"minion", atk:5, def:0, hp:5, atkC:-4, defC:0, hpC:-4, ability:"환생", text:"환생" },
  { id:"d14", tribe:"dark", name:"서큐버스", cost:6, type:"minion", atk:5, def:0, hp:5, atkC:3, defC:0, hpC:3, rarity:"uncommon", atkSkill:6, text:"흡혈공격" },
  { id:"d15", tribe:"dark", name:"나이트메어", cost:3, type:"minion", atk:6, def:0, hp:6, atkC:-5, defC:0, hpC:-5, atkSkill:11, text:"혼란공격" },
  { id:"d16", tribe:"dark", name:"듀라한", cost:3, type:"minion", atk:3, def:0, hp:2, atkC:-3, defC:0, hpC:3, atkSkill:4, text:"연속공격" },
  { id:"d17", tribe:"dark", name:"저주방패병", cost:1, type:"minion", atk:1, def:1, hp:1, atkC:1, defC:0, hpC:0, text:"" },
  { id:"d18", tribe:"dark", name:"장료", cost:6, type:"minion", atk:6, def:1, hp:6, atkC:5, defC:0, hpC:-5, rarity:"rare", atkSkill:10, text:"돌파공격" },
  { id:"d20", tribe:"dark", name:"가고일", cost:5, type:"minion", atk:6, def:0, hp:5, atkC:-3, defC:3, hpC:-3, rarity:"uncommon", ability:"보호", text:"보호" },
  { id:"d21", tribe:"dark", name:"네크로맨서", cost:5, type:"minion", atk:4, def:0, hp:4, atkC:3, defC:0, hpC:3, rarity:"uncommon", ability:"유언", text:"유언" },
  { id:"d22", tribe:"dark", name:"만티코어", cost:5, type:"minion", atk:5, def:0, hp:5, atkC:-3, defC:3, hpC:0, rarity:"uncommon", atkSkill:2, text:"관통공격" },
  { id:"d23", tribe:"dark", name:"리치", cost:7, type:"minion", atk:6, def:0, hp:6, atkC:-5, defC:0, hpC:5, rarity:"rare", atkSkill:9, text:"광역공격" },
  { id:"d24", tribe:"dark", name:"암흑의 정령", cost:4, type:"minion", atk:5, def:0, hp:4, atkC:-3, defC:3, hpC:0, text:"" },
  { id:"d25", tribe:"dark", name:"뱀파이어", cost:5, type:"minion", atk:5, def:0, hp:5, atkC:0, defC:3, hpC:-3, rarity:"uncommon", atkSkill:6, text:"흡혈공격" },
  { id:"d26", tribe:"dark", name:"본맘모스", cost:6, type:"minion", atk:4, def:2, hp:4, atkC:3, defC:0, hpC:-3, rarity:"uncommon", atkSkill:3, text:"돌진공격" },
  { id:"d27", tribe:"dark", name:"블랙드래곤", cost:9, type:"minion", atk:4, def:0, hp:10, atkC:0, defC:4, hpC:-4, rarity:"rare", atkSkill:5, text:"치명공격" },
  { id:"d28", tribe:"dark", name:"암흑자이언트", cost:6, type:"minion", atk:6, def:0, hp:6, atkC:5, defC:0, hpC:-5, rarity:"uncommon", ability:"강탈", text:"강탈" },
  { id:"e11", tribe:"earth", name:"숲요정", cost:3, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:1, ability:"출전", text:"출전" },
  { id:"f28", tribe:"fire", name:"불꽃요정", cost:3, type:"minion", atk:4, def:0, hp:4, atkC:-2, defC:2, hpC:-2, text:"" },
  { id:"n22", tribe:"wind", name:"바람요정", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:-1, defC:0, hpC:-1, ability:"출전", text:"출전" },
  { id:"a21", tribe:"water", name:"물의요정", cost:3, type:"minion", atk:2, def:1, hp:1, atkC:-2, defC:2, hpC:0, ability:"출전", text:"출전" },
  { id:"l25", tribe:"light", name:"광휘요정", cost:3, type:"minion", atk:3, def:0, hp:2, atkC:1, defC:0, hpC:1, ability:"출전", text:"출전" },
  { id:"d19", tribe:"dark", name:"그림자요정", cost:3, type:"minion", atk:4, def:0, hp:2, atkC:-4, defC:0, hpC:4, ability:"출전", text:"출전" },
  { id:"l17", tribe:"light", name:"황월영", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:1, hpC:1, rarity:"rare", ability:"보호", text:"보호" },
  // --- tokens ---
  { id:"e40", tribe:"earth", name:"섬의파편", cost:1, type:"minion", token:true, atk:1, def:0, hp:2, atkC:0, defC:0, hpC:0, rarity:"common", text:"토큰" },
  // --- spells / items ---
{ id:"fs1", tribe:"fire", name:"화염화살", cost:2, type:"spell", rarity:"common", text:"유닛 하나 체-3", spell:{ type:"dmg", value:3, target:"any_minion" } },
  { id:"fs2", tribe:"fire", name:"화염폭풍", cost:4, type:"spell", rarity:"common", text:"적 전체 체-2, 코인-1", spell:{ type:"aoe_pack", enemy:2, coin:-1 } },
  { id:"fs3", tribe:"fire", name:"화염구", cost:3, type:"spell", rarity:"common", text:"유닛 하나 체-5, 코인-1", spell:{ type:"dmg", value:5, target:"any_minion", coin:-1 } },
  { id:"fs4", tribe:"fire", name:"화염탄", cost:4, type:"spell", rarity:"uncommon", text:"적 하나 파괴", spell:{ type:"kill", target:"enemy_minion" } },
  { id:"fs5", tribe:"fire", name:"폭염", cost:2, type:"spell", rarity:"common", text:"아군 전체 체-2, 드로우2", spell:{ type:"draw_ex", ownAllHp:2, draw:2 } },
  { id:"ns1", tribe:"wind", name:"바람망토", cost:2, type:"spell", rarity:"common", text:"손패 유닛 전체 보호 부여", spell:{ type:"grant_kw", where:"hand", ability:"보호", kw:"shield" } },
  { id:"ns2", tribe:"wind", name:"진공베기", cost:3, type:"spell", rarity:"common", text:"코인 있는 적 하나 파괴", spell:{ type:"kill_if", anyCoin:true } },
  { id:"ns3", tribe:"wind", name:"상승기류", cost:5, type:"spell", rarity:"rare", text:"드로우4", spell:{ type:"draw", value:4 } },
  { id:"as1", tribe:"water", name:"냉기화살", cost:1, type:"spell", rarity:"common", text:"적 하나 체-2, 다음 턴 공격 불가", spell:{ type:"dmg", value:2, target:"enemy_minion", skipAttack:true } },
  { id:"as2", tribe:"water", name:"물거울", cost:6, type:"spell", rarity:"rare", text:"아군 하나 복사, 보호 부여", spell:{ type:"copy_own", ability:"보호", kw:"shield" } },
  { id:"as3", tribe:"water", name:"익사", cost:3, type:"spell", rarity:"common", text:"5코 이하 적 하나 파괴", spell:{ type:"kill_if", maxCost:5 } },
  { id:"es1", tribe:"earth", name:"거인의봉인", cost:3, type:"spell", rarity:"uncommon", text:"공7 이상 적 하나 파괴", spell:{ type:"kill_if", minAtk:7 } },
  { id:"ns4", tribe:"wind", name:"떠오르는섬", cost:3, type:"spell", rarity:"uncommon", text:"내 전장 빈칸 수만큼 섬의파편(1/0/2) 소환", spell:{ type:"summon_islands" } },
  { id:"es2", tribe:"earth", name:"어스퀘이크", cost:6, type:"spell", rarity:"rare", text:"적 전체 체력을 내 최대마나 절반만큼 깎음", spell:{ type:"earthquake" } },
  { id:"es3", tribe:"earth", name:"샌드트랩", cost:4, type:"spell", rarity:"uncommon", text:"내 전장 빈칸 수만큼 적 체-3", spell:{ type:"sandtrap" } },
  { id:"es4", tribe:"earth", name:"미로생성", cost:3, type:"spell", rarity:"common", text:"아군 전체 복수 부여", spell:{ type:"grant_kw", ability:"복수", kw:"revenge" } },
  { id:"es5", tribe:"earth", name:"땅굴숨기", cost:2, type:"spell", rarity:"common", text:"내 유닛 수만큼 드로우", spell:{ type:"draw_ex", drawBoard:true } },
  { id:"ns5", tribe:"wind", name:"토네이도", cost:4, type:"spell", rarity:"uncommon", text:"2코 이하 유닛 전체 파괴", spell:{ type:"tornado" } },
  { id:"es6", tribe:"earth", name:"낙석", cost:2, type:"spell", rarity:"common", text:"유닛 전체 체-2", spell:{ type:"aoe_pack", all:2 } },
  { id:"es7", tribe:"earth", name:"모래지옥", cost:4, type:"spell", rarity:"common", text:"적 전체 공·방·체-2", spell:{ type:"sandhell", value:2 } },
  { id:"ls1", tribe:"light", name:"치유의빛", cost:2, type:"spell", rarity:"common", text:"아군 전체 체+3", spell:{ type:"buff_all", hp:3 } },
  { id:"ls2", tribe:"light", name:"축복", cost:7, type:"spell", rarity:"rare", text:"아군 하나 공·체+8, 연속공격 부여", spell:{ type:"grant_extra", atk:8, hp:8 } },
  { id:"ls3", tribe:"light", name:"정화", cost:3, type:"spell", rarity:"common", text:"유닛 하나 공=0 방=0 체=7", spell:{ type:"set_one", atk:0, def:0, hp:7, target:"any_minion" } },
  { id:"ds1", tribe:"dark", name:"파멸", cost:3, type:"spell", rarity:"common", text:"공4 이상 적 하나 파괴", spell:{ type:"kill_if", minAtk:4 } },
  { id:"coin", name:"동전", cost:0, type:"spell", text:"이번 턴 마나 +1", spell:{ type:"mana", value:1 }, token:true },
  { id:"ei1", tribe:"earth", name:"골렘의심장", cost:1, type:"item", rarity:"common", atk:0, def:0, hp:2, ability:"보호", text:"보호 부여" },
  { id:"ei2", tribe:"earth", name:"돌도끼", cost:2, type:"item", rarity:"common", atk:3, def:-1, hp:0, atkSkill:2, text:"관통공격 부여" },
  { id:"ei3", tribe:"earth", name:"바실리스크눈", cost:3, type:"item", rarity:"common", ability:"면역", atk:1, def:0, hp:1, text:"면역 부여" },
  { id:"ei4", tribe:"earth", name:"노름바위", cost:4, type:"item", rarity:"common", atk:0, def:0, hp:0, text:"이 유닛 코인 수만큼 공·체+" },
  { id:"ei5", tribe:"earth", name:"모래시계", cost:5, type:"item", rarity:"uncommon", atk:1, def:0, hp:1, ability:"환생", text:"환생 부여" },
  { id:"ei6", tribe:"earth", name:"대지의팔찌", cost:7, type:"item", rarity:"rare", atk:2, def:2, hp:0, atkSkill:3, text:"돌진공격 부여" },
  { id:"fi1", tribe:"fire", name:"불꽃검", cost:1, type:"item", rarity:"common", atk:2, def:0, hp:0, text:"" },
  { id:"fi2", tribe:"fire", name:"불꽃도끼", cost:2, type:"item", rarity:"common", atk:3, def:0, hp:0, text:"" },
  { id:"fi3", tribe:"fire", name:"불붙은건틀렛", cost:3, type:"item", rarity:"common", atk:1, def:2, hp:0, text:"" },
  { id:"fi4", tribe:"fire", name:"피닉스깃털", cost:5, type:"item", rarity:"common", atk:0, def:0, hp:2, ability:"환생", text:"환생 부여" },
  { id:"fi5", tribe:"fire", name:"도박불꽃반지", cost:6, type:"item", rarity:"rare", atk:5, def:1, hp:5, atkSkill:4, text:"연속공격 부여. 코인=5" },