
const TRIBES = [
  { id: "earth", name: "땅", en: "Earth", icon: "🪨", open: true, color: "#8b5a2b",
    powerName: "암석 방패", powerText: "1/2 암석 소환", power: { type: "summon", value: [1,2] } },
  { id: "fire", name: "불", en: "Fire", icon: "🔥", open: true, color: "#d44512",
    powerName: "불씨", powerText: "적 영웅에게 피해 1", power: { type: "face", value: 1 } },
  { id: "wind", name: "바람", en: "Wind", icon: "🌬️", open: true, color: "#7ec8c8",
    powerName: "돌풍", powerText: "적 영웅에게 피해 1", power: { type: "face", value: 1 } },
  { id: "water", name: "물", en: "Water", icon: "💧", open: true, color: "#2a7ad4",
    powerName: "샘물", powerText: "내 영웅 회복 2", power: { type: "heal_hero", value: 2 } },
  { id: "dark", name: "암흑", en: "Dark", icon: "🌑", open: true, color: "#5a2a7a",
    powerName: "암흑검", powerText: "적 영웅에게 피해 1", power: { type: "face", value: 1 } },
  { id: "light", name: "빛", en: "Light", icon: "✨", open: true, color: "#f0e0a0",
    powerName: "성광", powerText: "내 영웅 회복 2", power: { type: "heal_hero", value: 2 } },
];

const TRIBE_ICONS = {
  earth:"assets/img/icons/earth.jpg",
  fire:"assets/img/icons/fire.jpg",
  wind:"assets/img/icons/wind.jpg",
  water:"assets/img/icons/water.jpg",
  light:"assets/img/icons/light.jpg",
  dark:"assets/img/icons/dark.jpg",
  metal:"assets/img/frames/unit/metal.png"
};
const HUD_UI = {
  board:"assets/img/hud/board.jpg",
  hp:"assets/img/hud/hp.jpg",
  mana:"assets/img/hud/mana.jpg",
  deck:"assets/img/hud/deck.jpg"
};
const COIN_PLUS = "assets/img/coins/plus.png";
const COIN_MINUS = "assets/img/coins/minus.png";

const CARDS = [
// === UNITS (source of truth: 판타지아레나_유닛목록.xlsx + art {id}.jpg; never add orphan e29+ units here) ===
// 유닛 단일 소스 — 유닛목록.xlsx + art/{id}.jpg 가 정본. e29+ 고아 유닛 추가 금지.
  { id:"e1", tribe:"earth", name:"놀", cost:1, type:"minion", atk:0, def:0, hp:3, atkC:0, defC:0, hpC:1, text:"" },
  { id:"e2", tribe:"earth", name:"대지술사", cost:4, type:"minion", atk:3, def:0, hp:6, atkC:0, defC:0, hpC:3, atkSkill:7, text:"약화공격" },
  { id:"e3", tribe:"earth", name:"그린드래곤", cost:9, type:"minion", atk:6, def:0, hp:12, atkC:-3, defC:0, hpC:3, atkSkill:9, text:"광역공격" },
  { id:"e4", tribe:"earth", name:"드라이어드", cost:2, type:"minion", atk:0, def:0, hp:4, atkC:0, defC:0, hpC:1, ability:"활력", text:"활력" },
  { id:"e5", tribe:"earth", name:"드워프병사", cost:2, type:"minion", atk:2, def:0, hp:4, atkC:-2, defC:0, hpC:2, text:"" },
  { id:"e6", tribe:"earth", name:"만드라고라", cost:2, type:"minion", atk:1, def:0, hp:3, atkC:0, defC:0, hpC:3, atkSkill:7, text:"약화공격" },
  { id:"e7", tribe:"earth", name:"샌드맨", cost:2, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:1, text:"" },
  { id:"e8", tribe:"earth", name:"나무궁수", cost:2, type:"minion", atk:0, def:0, hp:4, atkC:0, defC:0, hpC:2, atkSkill:2, text:"관통공격" },
  { id:"e9", tribe:"earth", name:"오크", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:-1, defC:0, hpC:1, atkSkill:4, text:"연속공격" },
  { id:"e10", tribe:"earth", name:"드워프대장", cost:3, type:"minion", atk:2, def:1, hp:4, atkC:-1, defC:-1, hpC:1, ability:"결속", text:"결속" },
  { id:"e12", tribe:"earth", name:"스톤골렘", cost:3, type:"minion", atk:2, def:0, hp:5, atkC:-1, defC:0, hpC:1, ability:"보호", text:"보호" },
  { id:"e13", tribe:"earth", name:"마운록", cost:3, type:"minion", atk:1, def:0, hp:5, atkC:0, defC:0, hpC:2, rarity:"heroic", ability:"복수", text:"복수" },
  { id:"e14", tribe:"earth", name:"마초", cost:10, type:"minion", atk:6, def:1, hp:12, atkC:0, defC:0, hpC:1, rarity:"legendary", atkSkill:10, ability:"면역", text:"돌파공격 · 면역" },
  { id:"e15", tribe:"earth", name:"암석창병", cost:1, type:"minion", atk:0, def:0, hp:1, atkC:0, defC:0, hpC:3, atkSkill:2, text:"관통공격" },
  { id:"e16", tribe:"earth", name:"켄타우로스", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:-3, defC:0, hpC:3, atkSkill:3, text:"돌진공격" },
  { id:"e17", tribe:"earth", name:"고르곤", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:0, defC:0, hpC:2, atkSkill:8, text:"석화공격" },
  { id:"e18", tribe:"earth", name:"대지의 정령", cost:4, type:"minion", atk:2, def:0, hp:7, atkC:-2, defC:0, hpC:2, ability:"유언", text:"유언" },
  { id:"e19", tribe:"earth", name:"곽가", cost:8, type:"minion", atk:3, def:1, hp:10, atkC:0, defC:0, hpC:3, rarity:"heroic", atkSkill:9, text:"광역공격" },
  { id:"e20", tribe:"earth", name:"베헤모스", cost:6, type:"minion", atk:3, def:0, hp:10, atkC:0, defC:0, hpC:1, atkSkill:3, text:"돌진공격" },
  { id:"e21", tribe:"earth", name:"록마운틴킹", cost:5, type:"minion", atk:3, def:0, hp:9, atkC:-1, defC:0, hpC:1, ability:"복수", text:"복수" },
  { id:"e22", tribe:"earth", name:"스핑크스", cost:5, type:"minion", atk:3, def:0, hp:8, atkC:0, defC:0, hpC:2, atkSkill:11, text:"혼란공격" },
  { id:"e23", tribe:"earth", name:"조조", cost:5, type:"minion", atk:3, def:1, hp:5, atkC:0, defC:0, hpC:2, rarity:"heroic", ability:"강탈", text:"강탈" },
  { id:"e24", tribe:"earth", name:"티라노", cost:4, type:"minion", atk:2, def:1, hp:7, atkC:-1, defC:-1, hpC:1, atkSkill:10, text:"돌파공격" },
  { id:"e25", tribe:"earth", name:"대지자이언트", cost:6, type:"minion", atk:3, def:0, hp:8, atkC:-3, defC:3, hpC:3, ability:"보호", text:"보호" },
  { id:"e26", tribe:"earth", name:"사이클롭스", cost:6, type:"minion", atk:3, def:0, hp:9, atkC:-2, defC:0, hpC:2, atkSkill:5, text:"치명공격" },
  { id:"e27", tribe:"earth", name:"샌드웜", cost:5, type:"minion", atk:2, def:0, hp:6, atkC:0, defC:3, hpC:3, atkSkill:2, text:"관통공격" },
  { id:"e28", tribe:"earth", name:"이끼방패병", cost:1, type:"minion", atk:0, def:0, hp:1, atkC:0, defC:0, hpC:1, ability:"보호", text:"보호" },
  { id:"f1", tribe:"fire", name:"레드드래곤", cost:9, type:"minion", atk:10, def:0, hp:10, atkC:-3, defC:0, hpC:0, atkSkill:9, text:"광역공격" },
  { id:"f2", tribe:"fire", name:"불꽃궁수", cost:2, type:"minion", atk:5, def:0, hp:2, atkC:-3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"f3", tribe:"fire", name:"임프", cost:1, type:"minion", atk:3, def:0, hp:2, atkC:-3, defC:0, hpC:0, text:"" },
  { id:"f4", tribe:"fire", name:"고블린", cost:2, type:"minion", atk:1, def:2, hp:3, atkC:-1, defC:-1, hpC:-1, text:"" },
  { id:"f5", tribe:"fire", name:"불꽃여우", cost:2, type:"minion", atk:3, def:1, hp:2, atkC:-1, defC:-1, hpC:0, atkSkill:10, text:"돌파공격" },
  { id:"f6", tribe:"fire", name:"가후", cost:8, type:"minion", atk:6, def:1, hp:8, atkC:-4, defC:0, hpC:4, rarity:"heroic", atkSkill:9, text:"광역공격" },
  { id:"f7", tribe:"fire", name:"샐러맨더", cost:2, type:"minion", atk:4, def:0, hp:3, atkC:-4, defC:0, hpC:0, atkSkill:6, text:"흡혈공격" },
  { id:"f8", tribe:"fire", name:"용암술사", cost:4, type:"minion", atk:6, def:1, hp:4, atkC:-1, defC:-1, hpC:-1, ability:"유언", text:"유언" },
  { id:"f9", tribe:"fire", name:"용암늑대", cost:2, type:"minion", atk:3, def:0, hp:3, atkC:-2, defC:0, hpC:-2, atkSkill:3, text:"돌진공격" },
  { id:"f10", tribe:"fire", name:"헬하운드", cost:3, type:"minion", atk:5, def:0, hp:5, atkC:-4, defC:0, hpC:-4, atkSkill:4, text:"연속공격" },
  { id:"f11", tribe:"fire", name:"바바리안", cost:3, type:"minion", atk:4, def:0, hp:4, atkC:-3, defC:0, hpC:0, atkSkill:3, text:"돌진공격" },
  { id:"f12", tribe:"fire", name:"여령기", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:-2, defC:0, hpC:0, rarity:"heroic", atkSkill:5, text:"치명공격" },
  { id:"f13", tribe:"fire", name:"파이어골렘", cost:3, type:"minion", atk:3, def:2, hp:3, atkC:-2, defC:-2, hpC:0, ability:"복수", text:"복수" },
  { id:"f14", tribe:"fire", name:"폭염방패병", cost:1, type:"minion", atk:1, def:0, hp:2, atkC:-1, defC:0, hpC:0, atkSkill:7, text:"약화공격" },
  { id:"f15", tribe:"fire", name:"장비", cost:10, type:"minion", atk:9, def:1, hp:11, atkC:-4, defC:0, hpC:0, rarity:"legendary", atkSkill:4, ability:"복수", text:"연속공격 · 복수" },
  { id:"f16", tribe:"fire", name:"미노타우로스", cost:4, type:"minion", atk:5, def:0, hp:5, atkC:-3, defC:0, hpC:0, atkSkill:4, text:"연속공격" },
  { id:"f17", tribe:"fire", name:"불의 정령", cost:4, type:"minion", atk:5, def:2, hp:4, atkC:-2, defC:-2, hpC:0, atkSkill:7, text:"약화공격" },
  { id:"f18", tribe:"fire", name:"이프리트", cost:4, type:"minion", atk:6, def:0, hp:6, atkC:-4, defC:0, hpC:-4, atkSkill:5, text:"치명공격" },
  { id:"f19", tribe:"fire", name:"케르베로스", cost:5, type:"minion", atk:6, def:0, hp:6, atkC:-3, defC:0, hpC:0, atkSkill:4, text:"연속공격" },
  { id:"f20", tribe:"fire", name:"데빌", cost:3, type:"minion", atk:6, def:0, hp:5, atkC:-4, defC:0, hpC:-4, atkSkill:11, text:"혼란공격" },
  { id:"f21", tribe:"fire", name:"화염창병", cost:1, type:"minion", atk:1, def:0, hp:2, atkC:-1, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"f22", tribe:"fire", name:"하후돈", cost:7, type:"minion", atk:9, def:0, hp:9, atkC:-3, defC:0, hpC:0, rarity:"heroic", atkSkill:6, text:"흡혈공격" },
  { id:"f23", tribe:"fire", name:"발록", cost:5, type:"minion", atk:7, def:0, hp:7, atkC:-4, defC:0, hpC:-4, atkSkill:9, text:"광역공격" },
  { id:"f24", tribe:"fire", name:"키메라", cost:6, type:"minion", atk:8, def:2, hp:7, atkC:-2, defC:-2, hpC:-2, atkSkill:10, text:"돌파공격" },
  { id:"f25", tribe:"fire", name:"타이폰", cost:6, type:"minion", atk:8, def:0, hp:8, atkC:-3, defC:0, hpC:0, atkSkill:11, text:"혼란공격" },
  { id:"f26", tribe:"fire", name:"피닉스", cost:5, type:"minion", atk:7, def:1, hp:5, atkC:-1, defC:-1, hpC:-1, ability:"환생", text:"환생" },
  { id:"f27", tribe:"fire", name:"화염자이언트", cost:6, type:"minion", atk:9, def:0, hp:9, atkC:-4, defC:0, hpC:-4, atkSkill:3, text:"돌진공격" },
  { id:"n1", tribe:"wind", name:"깃털도마뱀", cost:2, type:"minion", atk:2, def:0, hp:5, atkC:-2, defC:0, hpC:0, text:"" },
  { id:"n2", tribe:"wind", name:"조운", cost:10, type:"minion", atk:6, def:1, hp:10, atkC:1, defC:0, hpC:1, rarity:"legendary", atkSkill:4, ability:"면역", text:"연속공격 · 면역" },
  { id:"n3", tribe:"wind", name:"질풍술사", cost:4, type:"minion", atk:5, def:1, hp:5, atkC:0, defC:-1, hpC:-1, atkSkill:7, text:"약화공격" },
  { id:"n4", tribe:"wind", name:"픽시", cost:1, type:"minion", atk:2, def:0, hp:2, atkC:-1, defC:0, hpC:0, text:"" },
  { id:"n5", tribe:"wind", name:"구름사슴", cost:2, type:"minion", atk:3, def:1, hp:3, atkC:-1, defC:-1, hpC:0, text:"" },
  { id:"n6", tribe:"wind", name:"매사냥꾼", cost:3, type:"minion", atk:4, def:0, hp:4, atkC:-1, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"n7", tribe:"wind", name:"바람늑대", cost:2, type:"minion", atk:3, def:0, hp:3, atkC:-1, defC:0, hpC:-1, atkSkill:10, text:"돌파공격" },
  { id:"n8", tribe:"wind", name:"선풍무사", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:-1, defC:0, hpC:-1, atkSkill:4, text:"연속공격" },
  { id:"n9", tribe:"wind", name:"손상향", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:1, defC:0, hpC:0, rarity:"heroic", atkSkill:2, text:"관통공격" },
  { id:"n10", tribe:"wind", name:"하피", cost:2, type:"minion", atk:2, def:0, hp:4, atkC:0, defC:0, hpC:-1, atkSkill:7, text:"약화공격" },
  { id:"n11", tribe:"wind", name:"그리핀", cost:3, type:"minion", atk:3, def:1, hp:3, atkC:0, defC:-1, hpC:-1, atkSkill:3, text:"돌진공격" },
  { id:"n12", tribe:"wind", name:"윈드골렘", cost:3, type:"minion", atk:4, def:0, hp:3, atkC:0, defC:0, hpC:-2, ability:"면역", text:"면역" },
  { id:"n13", tribe:"wind", name:"폭풍드래곤", cost:9, type:"minion", atk:9, def:0, hp:10, atkC:0, defC:0, hpC:-1, atkSkill:9, text:"광역공격" },
  { id:"n14", tribe:"wind", name:"폭풍창병", cost:1, type:"minion", atk:1, def:0, hp:2, atkC:0, defC:0, hpC:-1, atkSkill:2, text:"관통공격" },
  { id:"n15", tribe:"wind", name:"회오리무희", cost:5, type:"minion", atk:7, def:0, hp:7, atkC:-2, defC:0, hpC:-2, atkSkill:11, text:"혼란공격" },
  { id:"n16", tribe:"wind", name:"가루다", cost:4, type:"minion", atk:4, def:0, hp:4, atkC:-1, defC:0, hpC:0, atkSkill:5, text:"치명공격" },
  { id:"n17", tribe:"wind", name:"바람의 정령", cost:4, type:"minion", atk:5, def:0, hp:5, atkC:0, defC:0, hpC:-1, ability:"유언", text:"유언" },
  { id:"n18", tribe:"wind", name:"회오리궁수", cost:2, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:-1, atkSkill:2, text:"관통공격" },
  { id:"n19", tribe:"wind", name:"페가수스", cost:4, type:"minion", atk:6, def:0, hp:5, atkC:-2, defC:0, hpC:-2, atkSkill:3, text:"돌진공격" },
  { id:"n20", tribe:"wind", name:"호크라이더", cost:5, type:"minion", atk:6, def:0, hp:7, atkC:0, defC:0, hpC:-1, atkSkill:10, text:"돌파공격" },
  { id:"n21", tribe:"wind", name:"구름방패병", cost:1, type:"minion", atk:1, def:0, hp:1, atkC:-1, defC:0, hpC:0, ability:"보호", text:"보호" },
  { id:"n23", tribe:"wind", name:"템페스트", cost:5, type:"minion", atk:5, def:0, hp:5, atkC:-1, defC:0, hpC:0, atkSkill:9, text:"광역공격" },
  { id:"n24", tribe:"wind", name:"폭풍자이언트", cost:6, type:"minion", atk:7, def:0, hp:8, atkC:-2, defC:0, hpC:-2, atkSkill:4, text:"연속공격" },
  { id:"n25", tribe:"wind", name:"썬더버드", cost:6, type:"minion", atk:6, def:0, hp:7, atkC:0, defC:0, hpC:-1, atkSkill:5, text:"치명공격" },
  { id:"n26", tribe:"wind", name:"와이번", cost:6, type:"minion", atk:8, def:0, hp:8, atkC:-1, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"n27", tribe:"wind", name:"태사자", cost:7, type:"minion", atk:7, def:1, hp:6, atkC:1, defC:0, hpC:0, rarity:"heroic", atkSkill:4, text:"연속공격" },
  { id:"n28", tribe:"wind", name:"육손", cost:8, type:"minion", atk:3, def:1, hp:10, atkC:1, defC:0, hpC:1, rarity:"heroic", atkSkill:9, text:"광역공격" },
  { id:"a1", tribe:"water", name:"관우", cost:10, type:"minion", atk:5, def:3, hp:7, atkC:-1, defC:1, hpC:-1, rarity:"legendary", atkSkill:3, ability:"강탈", text:"돌진공격 · 강탈" },
  { id:"a2", tribe:"water", name:"슬라임", cost:1, type:"minion", atk:1, def:0, hp:2, atkC:-1, defC:1, hpC:0, text:"" },
  { id:"a3", tribe:"water", name:"연못거북", cost:2, type:"minion", atk:2, def:1, hp:2, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"a4", tribe:"water", name:"피라냐", cost:2, type:"minion", atk:2, def:0, hp:1, atkC:-1, defC:1, hpC:0, atkSkill:4, text:"연속공격" },
  { id:"a5", tribe:"water", name:"나가", cost:2, type:"minion", atk:3, def:0, hp:1, atkC:-3, defC:3, hpC:0, atkSkill:7, text:"약화공격" },
  { id:"a6", tribe:"water", name:"독두꺼비", cost:2, type:"minion", atk:1, def:1, hp:3, atkC:-1, defC:1, hpC:-1, text:"" },
  { id:"a7", tribe:"water", name:"리자드맨", cost:3, type:"minion", atk:2, def:1, hp:2, atkC:0, defC:1, hpC:-1, atkSkill:3, text:"돌진공격" },
  { id:"a8", tribe:"water", name:"빙결술사", cost:4, type:"minion", atk:2, def:2, hp:2, atkC:-1, defC:1, hpC:-1, atkSkill:8, text:"석화공격" },
  { id:"a9", tribe:"water", name:"전기해파리", cost:3, type:"minion", atk:1, def:2, hp:2, atkC:-1, defC:1, hpC:-1, atkSkill:11, text:"혼란공격" },
  { id:"a10", tribe:"water", name:"파도창병", cost:1, type:"minion", atk:1, def:0, hp:1, atkC:-1, defC:1, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"a11", tribe:"water", name:"심해방패병", cost:1, type:"minion", atk:0, def:0, hp:1, atkC:0, defC:1, hpC:1, atkSkill:2, text:"관통공격" },
  { id:"a12", tribe:"water", name:"머메이드", cost:3, type:"minion", atk:1, def:2, hp:1, atkC:0, defC:1, hpC:0, atkSkill:6, text:"흡혈공격" },
  { id:"a13", tribe:"water", name:"대교", cost:3, type:"minion", atk:1, def:2, hp:2, atkC:-1, defC:1, hpC:-1, rarity:"heroic", atkSkill:7, text:"약화공격" },
  { id:"a14", tribe:"water", name:"아이스드래곤", cost:9, type:"minion", atk:5, def:3, hp:6, atkC:-1, defC:1, hpC:-1, atkSkill:9, text:"광역공격" },
  { id:"a15", tribe:"water", name:"손권", cost:4, type:"minion", atk:1, def:2, hp:2, atkC:0, defC:1, hpC:0, rarity:"heroic", ability:"강탈", text:"강탈" },
  { id:"a16", tribe:"water", name:"아이스골렘", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:-3, defC:3, hpC:-3, ability:"보호", text:"보호" },
  { id:"a17", tribe:"water", name:"물의 정령", cost:4, type:"minion", atk:2, def:2, hp:1, atkC:-2, defC:2, hpC:0, ability:"유언", text:"유언" },
  { id:"a18", tribe:"water", name:"세이렌", cost:4, type:"minion", atk:2, def:1, hp:4, atkC:0, defC:3, hpC:-3, atkSkill:11, text:"혼란공격" },
  { id:"a19", tribe:"water", name:"켈피", cost:4, type:"minion", atk:4, def:2, hp:1, atkC:0, defC:1, hpC:0, atkSkill:10, text:"돌파공격" },
  { id:"a20", tribe:"water", name:"시서펜트", cost:6, type:"minion", atk:4, def:2, hp:4, atkC:0, defC:2, hpC:-2, atkSkill:3, text:"돌진공격" },
  { id:"a22", tribe:"water", name:"강가무녀", cost:5, type:"minion", atk:4, def:2, hp:3, atkC:0, defC:2, hpC:-2, atkSkill:7, text:"약화공격" },
  { id:"a23", tribe:"water", name:"주유", cost:8, type:"minion", atk:3, def:3, hp:5, atkC:-1, defC:1, hpC:0, rarity:"heroic", atkSkill:9, text:"광역공격" },
  { id:"a24", tribe:"water", name:"심해상어", cost:5, type:"minion", atk:3, def:2, hp:2, atkC:-3, defC:3, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"a25", tribe:"water", name:"얼음궁수", cost:2, type:"minion", atk:0, def:1, hp:1, atkC:0, defC:2, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"a26", tribe:"water", name:"바다자이언트", cost:6, type:"minion", atk:5, def:1, hp:5, atkC:-3, defC:3, hpC:0, ability:"결속", text:"결속" },
  { id:"a27", tribe:"water", name:"크라켄", cost:6, type:"minion", atk:4, def:2, hp:3, atkC:-1, defC:1, hpC:-1, atkSkill:9, text:"광역공격" },
  { id:"a28", tribe:"water", name:"히드라", cost:5, type:"minion", atk:3, def:2, hp:3, atkC:-1, defC:1, hpC:-1, atkSkill:4, text:"연속공격" },
  { id:"l1", tribe:"light", name:"태양궁수", cost:2, type:"minion", atk:2, def:0, hp:2, atkC:3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"l2", tribe:"light", name:"빛나방", cost:1, type:"minion", atk:1, def:0, hp:1, atkC:0, defC:1, hpC:1, text:"" },
  { id:"l3", tribe:"light", name:"치유술사", cost:4, type:"minion", atk:3, def:0, hp:4, atkC:2, defC:0, hpC:2, ability:"유언", text:"유언" },
  { id:"l4", tribe:"light", name:"제갈량", cost:10, type:"minion", atk:4, def:1, hp:10, atkC:1, defC:1, hpC:1, rarity:"legendary", atkSkill:9, ability:"보호", text:"광역공격 · 보호" },
  { id:"l5", tribe:"light", name:"축복방패병", cost:1, type:"minion", atk:0, def:0, hp:1, atkC:1, defC:0, hpC:0, ability:"보호", text:"보호" },
  { id:"l6", tribe:"light", name:"빛늑대", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:1, defC:1, hpC:0, text:"" },
  { id:"l7", tribe:"light", name:"성녀", cost:2, type:"minion", atk:2, def:0, hp:1, atkC:1, defC:1, hpC:1, ability:"활력", text:"활력" },
  { id:"l8", tribe:"light", name:"신관", cost:2, type:"minion", atk:1, def:0, hp:2, atkC:2, defC:0, hpC:2, ability:"고무", text:"고무" },
  { id:"l9", tribe:"light", name:"예언자", cost:2, type:"minion", atk:3, def:0, hp:2, atkC:0, defC:1, hpC:1, text:"" },
  { id:"l10", tribe:"light", name:"황충", cost:8, type:"minion", atk:2, def:1, hp:10, atkC:1, defC:1, hpC:1, rarity:"heroic", atkSkill:5, text:"치명공격" },
  { id:"l11", tribe:"light", name:"골드골렘", cost:3, type:"minion", atk:2, def:0, hp:3, atkC:0, defC:0, hpC:3, ability:"보호", text:"보호" },
  { id:"l12", tribe:"light", name:"성기사", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:0, defC:1, hpC:0, ability:"보호", text:"보호" },
  { id:"l13", tribe:"light", name:"광명창병", cost:1, type:"minion", atk:0, def:0, hp:1, atkC:3, defC:0, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"l14", tribe:"light", name:"수도사", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:1, defC:1, hpC:0, ability:"활력", text:"활력" },
  { id:"l15", tribe:"light", name:"인챈터", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:2, defC:0, hpC:0, atkSkill:7, text:"약화공격" },
  { id:"l16", tribe:"light", name:"금빛사자", cost:4, type:"minion", atk:4, def:0, hp:4, atkC:3, defC:0, hpC:0, ability:"보호", text:"보호" },
  { id:"l18", tribe:"light", name:"십자군", cost:3, type:"minion", atk:2, def:0, hp:2, atkC:1, defC:1, hpC:1, atkSkill:3, text:"돌진공격" },
  { id:"l19", tribe:"light", name:"유비", cost:4, type:"minion", atk:1, def:1, hp:4, atkC:1, defC:1, hpC:1, rarity:"heroic", ability:"보호", text:"보호" },
  { id:"l20", tribe:"light", name:"타이탄", cost:6, type:"minion", atk:6, def:0, hp:6, atkC:2, defC:0, hpC:2, ability:"보호", text:"보호" },
  { id:"l21", tribe:"light", name:"발키리", cost:5, type:"minion", atk:4, def:0, hp:4, atkC:1, defC:1, hpC:1, atkSkill:5, text:"치명공격" },
  { id:"l22", tribe:"light", name:"빛의 정령", cost:4, type:"minion", atk:4, def:0, hp:3, atkC:1, defC:1, hpC:1, ability:"결속", text:"결속" },
  { id:"l23", tribe:"light", name:"신전기사", cost:5, type:"minion", atk:5, def:0, hp:5, atkC:0, defC:0, hpC:3, ability:"보호", text:"보호" },
  { id:"l24", tribe:"light", name:"유니콘", cost:5, type:"minion", atk:5, def:0, hp:6, atkC:1, defC:1, hpC:0, ability:"활력", text:"활력" },
  { id:"l26", tribe:"light", name:"골드드래곤", cost:9, type:"minion", atk:9, def:0, hp:8, atkC:1, defC:1, hpC:1, atkSkill:9, text:"광역공격" },
  { id:"l27", tribe:"light", name:"엔젤", cost:5, type:"minion", atk:5, def:0, hp:4, atkC:2, defC:0, hpC:2, ability:"면역", text:"면역" },
  { id:"l28", tribe:"light", name:"태양자이언트", cost:6, type:"minion", atk:6, def:0, hp:5, atkC:1, defC:1, hpC:1, atkSkill:4, text:"연속공격" },
  { id:"d1", tribe:"dark", name:"로그", cost:2, type:"minion", atk:4, def:0, hp:1, atkC:-4, defC:0, hpC:4, atkSkill:10, text:"돌파공격" },
  { id:"d2", tribe:"dark", name:"사마의", cost:8, type:"minion", atk:6, def:1, hp:8, atkC:-4, defC:0, hpC:4, rarity:"heroic", atkSkill:9, text:"광역공격" },
  { id:"d3", tribe:"dark", name:"그림자궁수", cost:2, type:"minion", atk:2, def:0, hp:3, atkC:0, defC:1, hpC:-1, atkSkill:2, text:"관통공격" },
  { id:"d4", tribe:"dark", name:"해골나방", cost:1, type:"minion", atk:1, def:1, hp:1, atkC:0, defC:-1, hpC:1, text:"" },
  { id:"d5", tribe:"dark", name:"고스트", cost:2, type:"minion", atk:3, def:0, hp:2, atkC:-3, defC:0, hpC:3, atkSkill:11, text:"혼란공격" },
  { id:"d6", tribe:"dark", name:"구울", cost:2, type:"minion", atk:2, def:0, hp:2, atkC:-1, defC:0, hpC:1, ability:"환생", text:"환생" },
  { id:"d7", tribe:"dark", name:"여포", cost:10, type:"minion", atk:9, def:0, hp:12, atkC:-5, defC:0, hpC:5, rarity:"legendary", atkSkill:10, ability:"환생", text:"돌파공격 · 환생" },
  { id:"d8", tribe:"dark", name:"암흑창병", cost:1, type:"minion", atk:0, def:0, hp:2, atkC:0, defC:1, hpC:-1, atkSkill:2, text:"관통공격" },
  { id:"d9", tribe:"dark", name:"스켈레톤", cost:2, type:"minion", atk:3, def:0, hp:3, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"d10", tribe:"dark", name:"심연술사", cost:4, type:"minion", atk:4, def:0, hp:5, atkC:-4, defC:4, hpC:-4, ability:"유언", text:"유언" },
  { id:"d11", tribe:"dark", name:"초선", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:3, defC:0, hpC:-3, rarity:"heroic", ability:"환생", text:"환생" },
  { id:"d12", tribe:"dark", name:"다크골렘", cost:3, type:"minion", atk:3, def:0, hp:4, atkC:-3, defC:3, hpC:-3, ability:"복수", text:"복수" },
  { id:"d13", tribe:"dark", name:"미라", cost:3, type:"minion", atk:4, def:0, hp:2, atkC:-4, defC:0, hpC:4, ability:"환생", text:"환생" },
  { id:"d14", tribe:"dark", name:"서큐버스", cost:3, type:"minion", atk:2, def:0, hp:4, atkC:0, defC:3, hpC:-3, atkSkill:6, text:"흡혈공격" },
  { id:"d15", tribe:"dark", name:"나이트메어", cost:4, type:"minion", atk:4, def:0, hp:5, atkC:3, defC:0, hpC:-3, ability:"환생", text:"환생" },
  { id:"d16", tribe:"dark", name:"듀라한", cost:3, type:"minion", atk:3, def:0, hp:3, atkC:-3, defC:0, hpC:3, atkSkill:4, text:"연속공격" },
  { id:"d17", tribe:"dark", name:"저주방패병", cost:1, type:"minion", atk:1, def:0, hp:2, atkC:0, defC:1, hpC:-1, text:"" },
  { id:"d18", tribe:"dark", name:"장료", cost:6, type:"minion", atk:7, def:1, hp:6, atkC:4, defC:0, hpC:-4, rarity:"heroic", atkSkill:10, text:"돌파공격" },
  { id:"d20", tribe:"dark", name:"가고일", cost:5, type:"minion", atk:6, def:0, hp:6, atkC:-3, defC:3, hpC:-3, ability:"보호", text:"보호" },
  { id:"d21", tribe:"dark", name:"네크로맨서", cost:5, type:"minion", atk:5, def:0, hp:6, atkC:-5, defC:0, hpC:5, atkSkill:8, text:"석화공격" },
  { id:"d22", tribe:"dark", name:"만티코어", cost:5, type:"minion", atk:6, def:0, hp:5, atkC:-3, defC:3, hpC:0, atkSkill:2, text:"관통공격" },
  { id:"d23", tribe:"dark", name:"리치", cost:7, type:"minion", atk:7, def:0, hp:7, atkC:-5, defC:0, hpC:5, atkSkill:9, text:"광역공격" },
  { id:"d24", tribe:"dark", name:"암흑의 정령", cost:4, type:"minion", atk:5, def:0, hp:2, atkC:-5, defC:5, hpC:0, atkSkill:7, text:"약화공격" },
  { id:"d25", tribe:"dark", name:"뱀파이어", cost:5, type:"minion", atk:5, def:0, hp:5, atkC:0, defC:4, hpC:-4, atkSkill:6, text:"흡혈공격" },
  { id:"d26", tribe:"dark", name:"본맘모스", cost:6, type:"minion", atk:6, def:0, hp:7, atkC:-4, defC:4, hpC:-4, atkSkill:3, text:"돌진공격" },
  { id:"d27", tribe:"dark", name:"블랙드래곤", cost:9, type:"minion", atk:9, def:0, hp:10, atkC:5, defC:0, hpC:-5, atkSkill:5, text:"치명공격" },
  { id:"d28", tribe:"dark", name:"암흑자이언트", cost:6, type:"minion", atk:7, def:0, hp:7, atkC:5, defC:0, hpC:-5, ability:"강탈", text:"강탈" },
  { id:"e11", tribe:"earth", name:"숲요정", cost:3, type:"minion", atk:2, def:1, hp:3, atkC:0, defC:-1, hpC:1, ability:"출전", text:"출전" },
  { id:"f28", tribe:"fire", name:"불꽃요정", cost:3, type:"minion", atk:4, def:1, hp:3, atkC:-1, defC:-1, hpC:-1, ability:"출전", text:"출전" },
  { id:"n22", tribe:"wind", name:"바람요정", cost:3, type:"minion", atk:3, def:1, hp:4, atkC:-1, defC:-1, hpC:-1, ability:"출전", text:"출전" },
  { id:"a21", tribe:"water", name:"물의요정", cost:3, type:"minion", atk:2, def:1, hp:1, atkC:-2, defC:2, hpC:0, ability:"출전", text:"출전" },
  { id:"l25", tribe:"light", name:"광휘요정", cost:3, type:"minion", atk:3, def:0, hp:2, atkC:2, defC:0, hpC:2, ability:"출전", text:"출전" },
  { id:"d19", tribe:"dark", name:"그림자요정", cost:3, type:"minion", atk:5, def:0, hp:2, atkC:-5, defC:0, hpC:5, ability:"출전", text:"출전" },
  { id:"l17", tribe:"light", name:"황월영", cost:3, type:"minion", atk:1, def:1, hp:2, atkC:1, defC:1, hpC:1, rarity:"heroic", ability:"보호", text:"보호" },
  // --- tokens ---
  { id:"e40", tribe:"earth", name:"섬의파편", cost:1, type:"minion", token:true, atk:1, def:0, hp:2, atkC:0, defC:0, hpC:0, rarity:"common", text:"토큰" },
  { id:"recruit", tribe:"earth", name:"암석", cost:1, type:"minion", token:true, atk:1, def:0, hp:2, atkC:0, defC:0, hpC:0, text:"영웅 능력" },
  // --- spells / items ---
{ id:"fs1", tribe:"fire", name:"화염화살", cost:2, type:"spell", text:"적 하나 피해 3", spell:{ type:"dmg", value:3, target:"enemy_minion" } },
  { id:"fs2", tribe:"fire", name:"화염폭풍", cost:4, type:"spell", text:"적 전체 피해 2, 코인-1", spell:{ type:"aoe_pack", enemy:2, coin:-1 } },
  { id:"fs3", tribe:"fire", name:"화염구", cost:3, type:"spell", text:"적 하나 피해 5, 코인-1", spell:{ type:"dmg", value:5, target:"enemy_minion", coin:-1 } },
  { id:"fs4", tribe:"fire", name:"화염탄", cost:4, type:"spell", text:"적 유닛 하나 파괴", spell:{ type:"kill", target:"enemy_minion" } },
  { id:"fs5", tribe:"fire", name:"폭염", cost:2, type:"spell", text:"아군 전체 체-2, 카드 2장 뽑기", spell:{ type:"draw_ex", ownAllHp:2, draw:2 } },
  { id:"ns1", tribe:"wind", name:"바람망토", cost:2, type:"spell", text:"손패 유닛 전체 활력 부여", spell:{ type:"grant_kw", where:"hand", ability:"활력", kw:"vital" } },
  { id:"ns2", tribe:"wind", name:"진공베기", cost:3, type:"spell", text:"코인이 있는 적 하나 파괴", spell:{ type:"kill_if", anyCoin:true } },
  { id:"ns3", tribe:"wind", name:"상승기류", cost:5, type:"spell", text:"카드 4장 뽑기", spell:{ type:"draw", value:4 } },
  { id:"as1", tribe:"water", name:"냉기화살", cost:1, type:"spell", text:"적 하나 피해 2, 다음 턴 공격 불가", spell:{ type:"dmg", value:2, target:"enemy_minion", skipAttack:true } },
  { id:"as2", tribe:"water", name:"물거울", cost:6, type:"spell", text:"아군 하나 복사, 복사본에 보호 부여", spell:{ type:"copy_own", ability:"보호", kw:"shield" } },
  { id:"as3", tribe:"water", name:"익사", cost:3, type:"spell", text:"5코 이하 적 하나 파괴", spell:{ type:"kill_if", maxCost:5 } },
  { id:"es1", tribe:"earth", name:"거인의봉인", cost:3, type:"spell", rarity:"rare", text:"공격력 7 이상 적 하나 파괴", spell:{ type:"kill_if", minAtk:7 } },
  { id:"ns4", tribe:"wind", name:"떠오르는섬", cost:3, type:"spell", rarity:"common", text:"내 빈 칸만큼 섬의파편(1/0/2)을 소환", spell:{ type:"summon_islands" } },
  { id:"es2", tribe:"earth", name:"어스퀘이크", cost:6, type:"spell", rarity:"legendary", text:"적 전체 체력을 내 최대 마나 절반만큼 감소", spell:{ type:"earthquake" } },
  { id:"es3", tribe:"earth", name:"샌드트랩", cost:4, type:"spell", rarity:"common", text:"내 빈 칸 수만큼 적에게 피해 3", spell:{ type:"sandtrap" } },
  { id:"es4", tribe:"earth", name:"미로생성", cost:3, type:"spell", rarity:"heroic", text:"아군 전체 혼란 부여", spell:{ type:"grant_kw", ability:"혼란", kw:"confuse" } },
  { id:"es5", tribe:"earth", name:"땅굴숨기", cost:2, type:"spell", rarity:"common", text:"내 유닛 수만큼 카드 뽑기(없으면 0)", spell:{ type:"draw_ex", drawBoard:true } },
  { id:"ns5", tribe:"wind", name:"토네이도", cost:4, type:"spell", rarity:"heroic", text:"2코 이하 유닛 전체 파괴", spell:{ type:"tornado" } },
  { id:"es6", tribe:"earth", name:"낙석", cost:2, type:"spell", rarity:"common", text:"모든 유닛 피해 2", spell:{ type:"aoe_pack", all:2 } },
  { id:"es7", tribe:"earth", name:"모래지옥", cost:4, type:"spell", rarity:"rare", text:"적 전체 공·방·체 -2", spell:{ type:"sandhell", value:2 } },
  { id:"ls1", tribe:"light", name:"치유의빛", cost:2, type:"spell", text:"아군 전체 체+3", spell:{ type:"buff_all", hp:3 } },
  { id:"ls2", tribe:"light", name:"축복", cost:7, type:"spell", text:"아군 하나 공+8 체+8, 연속공격", spell:{ type:"grant_extra", atk:8, hp:8 } },
  { id:"ls3", tribe:"light", name:"정화", cost:3, type:"spell", text:"적 유닛 하나 공=0 방=0 체=7", spell:{ type:"set_one", atk:0, def:0, hp:7 } },
  { id:"ds1", tribe:"dark", name:"파멸", cost:3, type:"spell", text:"공격력 4 이상 적 하나 파괴", spell:{ type:"kill_if", minAtk:4 } },
  { id:"coin", name:"동전", cost:0, type:"spell", text:"이번 턴 마나 +1", spell:{ type:"mana", value:1 }, token:true },
  { id:"ei1", tribe:"earth", name:"골렘의심장", cost:1, type:"item", rarity:"common", atk:0, def:0, hp:2, ability:"보호", text:"장착: 체+2. 보호" },
  { id:"ei2", tribe:"earth", name:"돌도끼", cost:2, type:"item", rarity:"common", atk:3, def:-1, hp:0, atkSkill:2, text:"장착: 공+3 방-1. 관통공격" },
  { id:"ei3", tribe:"earth", name:"바실리스크눈", cost:3, type:"item", rarity:"common", atk:1, def:0, hp:1, atkSkill:8, text:"장착: 공+1 체+1. 석화공격" },
  { id:"ei4", tribe:"earth", name:"노름바위", cost:4, type:"item", rarity:"rare", atk:0, def:0, hp:0, text:"장착: 이 유닛 코인 수만큼 공+ · 체+" },
  { id:"ei5", tribe:"earth", name:"모래시계", cost:5, type:"item", rarity:"rare", atk:1, def:0, hp:1, ability:"위압", text:"장착: 공+1 체+1. 위압" },
  { id:"ei6", tribe:"earth", name:"대지의팔찌", cost:7, type:"item", rarity:"heroic", atk:2, def:2, hp:0, atkSkill:3, text:"장착: 공+2 방+2. 돌진공격" },
  { id:"fi1", tribe:"fire", name:"불꽃검", cost:1, type:"item", rarity:"common", atk:2, def:0, hp:0, atkSkill:7, text:"장착: 공+2. 약화공격" },
  { id:"fi2", tribe:"fire", name:"불꽃도끼", cost:2, type:"item", rarity:"common", atk:3, def:0, hp:0, atkSkill:2, text:"장착: 공+3. 관통공격" },
  { id:"fi3", tribe:"fire", name:"불붙은건틀렛", cost:3, type:"item", rarity:"common", atk:1, def:2, hp:0, text:"장착: 공+1 방+2" },
  { id:"fi4", tribe:"fire", name:"피닉스깃털", cost:5, type:"item", rarity:"rare", atk:0, def:0, hp:2, ability:"환생", text:"장착: 체+2. 환생" },
  { id:"fi5", tribe:"fire", name:"도박불꽃반지", cost:6, type:"item", rarity:"heroic", atk:10, def:0, hp:0, atkSkill:4, text:"장착: 공+10. 연속공격. 코인이 전부 뒷면이면 이 아이템 파괴" },
  { id:"fi6", tribe:"fire", name:"분노의해머", cost:7, type:"item", rarity:"heroic", atk:4, def:0, hp:0, atkSkill:9, text:"장착: 공+4. 광역공격" },
  { id:"ni1", tribe:"wind", name:"요정의부츠", cost:1, type:"item", rarity:"common", atk:0, def:1, hp:1, text:"장착: 방+1 체+1" },
  { id:"ni2", tribe:"wind", name:"올빼미의눈", cost:2, type:"item", rarity:"common", atk:2, def:0, hp:0, atkSkill:2, text:"장착: 공+2. 관통공격" },
  { id:"ni3", tribe:"wind", name:"페어리소드", cost:3, type:"item", rarity:"common", atk:2, def:0, hp:0, atkSkill:7, text:"장착: 공+2. 약화공격" },
  { id:"ni4", tribe:"wind", name:"도둑바람", cost:3, type:"item", rarity:"rare", atk:0, def:0, hp:0, text:"전장 모든 유닛의 코인을 삭제한다" },
  { id:"ni5", tribe:"wind", name:"하피의손톱", cost:5, type:"item", rarity:"rare", atk:3, def:0, hp:0, atkSkill:5, text:"장착: 공+3. 치명공격" },
  { id:"ni6", tribe:"wind", name:"폭풍의구슬", cost:7, type:"item", rarity:"heroic", atk:2, def:0, hp:0, atkSkill:9, text:"장착: 공+2. 광역공격" },
  { id:"ai1", tribe:"water", name:"조개방패", cost:1, type:"item", rarity:"common", atk:0, def:2, hp:0, text:"장착: 방+2" },
  { id:"ai2", tribe:"water", name:"얼음창", cost:2, type:"item", rarity:"common", atk:2, def:0, hp:0, atkSkill:2, text:"장착: 공+2. 관통공격" },
  { id:"ai3", tribe:"water", name:"상어의턱뼈", cost:3, type:"item", rarity:"common", atk:3, def:0, hp:0, atkSkill:6, text:"장착: 공+3. 흡혈공격" },
  { id:"ai4", tribe:"water", name:"진주방패", cost:3, type:"item", rarity:"rare", atk:0, def:0, hp:0, text:"장착: 이 유닛 코인 수만큼 방+" },
  { id:"ai5", tribe:"water", name:"산호검", cost:5, type:"item", rarity:"rare", atk:3, def:1, hp:0, atkSkill:1, text:"장착: 공+3 방+1. 돌파공격" },
  { id:"ai6", tribe:"water", name:"인어의하프", cost:7, type:"item", rarity:"heroic", atk:1, def:0, hp:2, atkSkill:11, text:"장착: 공+1 체+2. 혼란공격" },
  { id:"li1", tribe:"light", name:"소생초", cost:1, type:"item", rarity:"common", atk:0, def:0, hp:2, text:"장착: 체+2" },
  { id:"li2", tribe:"light", name:"별목걸이", cost:2, type:"item", rarity:"common", atk:0, def:0, hp:2, ability:"활력", text:"장착: 체+2. 활력" },
  { id:"li3", tribe:"light", name:"성스러운주화", cost:2, type:"item", rarity:"rare", atk:0, def:0, hp:0, text:"이번 턴 앞면 확률 +20%" },
  { id:"li4", tribe:"light", name:"환상의거울", cost:3, type:"item", rarity:"common", atk:0, def:0, hp:0, ability:"보호", text:"장착: 보호" },
  { id:"li5", tribe:"light", name:"아이언실드", cost:5, type:"item", rarity:"rare", atk:0, def:2, hp:0, ability:"결속", text:"장착: 방+2. 결속" },
  { id:"li6", tribe:"light", name:"블레스트아머", cost:7, type:"item", rarity:"heroic", atk:0, def:2, hp:2, ability:"환생", text:"장착: 방+2 체+2. 환생" },
  { id:"di1", tribe:"dark", name:"저주의인형", cost:1, type:"item", rarity:"common", atk:2, def:0, hp:0, atkSkill:7, text:"장착: 공+2. 약화공격" },
  { id:"di2", tribe:"dark", name:"피의망토", cost:2, type:"item", rarity:"common", atk:2, def:0, hp:0, atkSkill:6, text:"장착: 공+2. 흡혈공격" },
  { id:"di3", tribe:"dark", name:"흑마법서", cost:3, type:"item", rarity:"common", atk:1, def:0, hp:1, ability:"위압", text:"장착: 공+1 체+1. 위압" },
  { id:"di4", tribe:"dark", name:"조작된주화", cost:4, type:"item", rarity:"rare", atk:0, def:0, hp:0, text:"모든 코인을 골드코인으로 바꾼다" },
  { id:"di5", tribe:"dark", name:"사신의낫", cost:5, type:"item", rarity:"rare", atk:4, def:0, hp:0, atkSkill:2, text:"장착: 공+4. 관통공격" },
  { id:"di6", tribe:"dark", name:"다크아머", cost:7, type:"item", rarity:"heroic", atk:0, def:3, hp:0, ability:"보호", text:"장착: 방+3. 보호" },
  { id:"ns6", tribe:"wind", name:"바람방패", cost:2, type:"spell", rarity:"common", text:"아군 하나 공+1 방+1 체+1", spell:{ type:"buff", target:"own_minion", atk:1, def:1, hp:1 } },
  { id:"ds2", tribe:"dark", name:"굶주림", cost:2, type:"spell", rarity:"common", text:"아군 유닛 하나 파괴, 카드 2장 뽑기", spell:{ type:"draw_ex", sacOwn:true, draw:2 } },
  { id:"as4", tribe:"water", name:"수정호수", cost:4, type:"spell", rarity:"common", text:"카드 2장 뽑기, 적 전체 방-1", spell:{ type:"draw_ex", draw:2, enemyDef:-1 } },
  { id:"as5", tribe:"water", name:"얼음방패", cost:2, type:"spell", rarity:"common", text:"아군 하나 방+2", spell:{ type:"buff", target:"own_minion", def:2 } },
  { id:"ls4", tribe:"light", name:"성역축복", cost:1, type:"spell", rarity:"common", text:"이번 턴 내 코인확률 +50%", spell:{ type:"coin_luck", value:0.75 } },
  { id:"ls5", tribe:"light", name:"수호의빛", cost:4, type:"spell", rarity:"common", text:"아군 전체 보호 부여", spell:{ type:"grant_kw", ability:"보호", kw:"shield" } },
  { id:"es8", tribe:"earth", name:"거대화", cost:1, type:"spell", rarity:"common", text:"아군 하나 체+4", spell:{ type:"buff", target:"own_minion", hp:4 } },
  { id:"ls6", tribe:"light", name:"성벽가호", cost:5, type:"spell", rarity:"common", text:"아군 하나 방+2 체+8", spell:{ type:"buff", target:"own_minion", def:2, hp:8 } },
  { id:"as6", tribe:"water", name:"눈보라", cost:5, type:"spell", rarity:"common", text:"적 전체 피해 2. 맞은 적은 다음 턴 공격 불가", spell:{ type:"aoe_pack", enemy:2, skipAttack:true } },
  { id:"ns7", tribe:"wind", name:"한줄기바람", cost:1, type:"spell", rarity:"common", text:"적 유닛 하나 피해 1, 카드 1장 뽑기", spell:{ type:"draw_ex", enemyDmg:1, draw:1 } },
  { id:"as7", tribe:"water", name:"인어의노래", cost:2, type:"spell", rarity:"common", text:"유닛 하나 공=1, 코인=0", spell:{ type:"set_one", atk:1, coinZero:true, target:"any_minion" } },
  { id:"ls7", tribe:"light", name:"빛의환영", cost:2, type:"spell", rarity:"common", text:"적 전체 피해 1, 아군 전체 체+1", spell:{ type:"aoe_pack", enemy:1, ownHp:1 } },
  { id:"as8", tribe:"water", name:"개구리변신", cost:4, type:"spell", rarity:"common", text:"적 전체 공=1 체=1", spell:{ type:"set_stats", atk:1, hp:1, target:"all_enemy" } },
  { id:"ns8", tribe:"wind", name:"폭풍우", cost:4, type:"spell", rarity:"common", text:"적 전체 피해 2, 코인-1", spell:{ type:"aoe_pack", enemy:2, coin:-1 } },
  { id:"fs6", tribe:"fire", name:"광분", cost:1, type:"spell", rarity:"common", text:"다음 턴 내 마나 +3", spell:{ type:"mana_next", value:3 } },
  { id:"fs7", tribe:"fire", name:"화염방패", cost:6, type:"spell", rarity:"common", text:"아군 하나 방+3, 보호 부여", spell:{ type:"buff", target:"own_minion", def:3, kws:["shield"], ability:"보호" } },
  { id:"ls8", tribe:"light", name:"헌금", cost:3, type:"spell", rarity:"common", text:"카드 2장 뽑기. 이번 턴 유닛을 낼 수 없다", spell:{ type:"draw_ex", draw:2, noPlayMinion:true } },
  { id:"ds3", tribe:"dark", name:"헬게이트", cost:4, type:"spell", rarity:"common", text:"모든 유닛 피해 3", spell:{ type:"aoe_pack", all:3 } },
  { id:"ds4", tribe:"dark", name:"불길한예감", cost:1, type:"spell", rarity:"common", text:"이번 턴 내 코인확률 -50%", spell:{ type:"coin_luck", value:0.25 } },
  { id:"ds5", tribe:"dark", name:"블랙홀", cost:7, type:"spell", rarity:"common", text:"아군·적 모든 유닛 파괴, 아군 최대마나 1 감소", spell:{ type:"wipe_all", maxMana:-1 } },
  { id:"ds6", tribe:"dark", name:"해골던지기", cost:3, type:"spell", rarity:"common", text:"공격력 4 이하 적 하나 파괴", spell:{ type:"kill_if", maxAtk:4 } },
  { id:"ds7", tribe:"dark", name:"전염병", cost:4, type:"spell", rarity:"common", text:"4코 이상 모든 유닛 공=1 체=1", spell:{ type:"plague", minCost:4 } },
  { id:"ds8", tribe:"dark", name:"13시의저주", cost:1, type:"spell", rarity:"common", text:"아군 유닛 강탈 부여", spell:{ type:"grant_kw", ability:"강탈", kw:"steal" } },
  { id:"fs8", tribe:"fire", name:"메테오", cost:7, type:"spell", rarity:"common", text:"적 전체 피해 4, 코인-1", spell:{ type:"aoe_pack", enemy:4, coin:-1 } }
];
const SPELL_SCHOOL = { fire:"염술", wind:"풍술", water:"물술", light:"성술", dark:"암술", earth:"지술" };
const CARD_RACE = {
  a1:"장수",
  a2:"짐승",
  a3:"짐승",
  a4:"벌레",
  a5:"짐승",
  a6:"벌레",
  a7:"짐승",
  a8:"정령",
  a9:"벌레",
  a10:"부족",
  a11:"부족",
  a12:"짐승",
  a13:"명장",
  a14:"거인",
  a15:"명장",
  a16:"짐승",
  a17:"정령",
  a18:"짐승",
  a19:"짐승",
  a20:"짐승",
  a21:"정령",
  a22:"짐승",
  a23:"명장",
  a24:"짐승",
  a25:"부족",
  a26:"거인",
  a27:"거인",
  a28:"거인",
  d1:"해골",
  d2:"명장",
  d3:"부족",
  d4:"해골",
  d5:"해골",
  d6:"해골",
  d7:"장수",
  d8:"부족",
  d9:"해골",
  d10:"정령",
  d11:"명장",
  d12:"해골",
  d13:"해골",
  d14:"해골",
  d15:"해골",
  d16:"해골",
  d17:"부족",
  d18:"장수",
  d19:"정령",
  d20:"해골",
  d21:"해골",
  d22:"해골",
  d23:"해골",
  d24:"정령",
  d25:"해골",
  d26:"해골",
  d27:"거인",
  d28:"거인",
  e1:"부족",
  e2:"정령",
  e3:"거인",
  e4:"정령",
  e5:"부족",
  e6:"벌레",
  e7:"부족",
  e8:"부족",
  e9:"부족",
  e10:"부족",
  e11:"정령",
  e12:"짐승",
  e13:"명장",
  e14:"장수",
  e15:"부족",
  e16:"기수",
  e17:"짐승",
  e18:"정령",
  e19:"명장",
  e20:"거인",
  e21:"짐승",
  e22:"짐승",
  e23:"명장",
  e24:"짐승",
  e25:"거인",
  e26:"거인",
  e27:"벌레",
  e28:"부족",
  e40:"짐승",
  f1:"거인",
  f2:"부족",
  f3:"정령",
  f4:"부족",
  f5:"짐승",
  f6:"명장",
  f7:"정령",
  f8:"정령",
  f9:"짐승",
  f10:"짐승",
  f11:"부족",
  f12:"명장",
  f13:"짐승",
  f14:"부족",
  f15:"장수",
  f16:"짐승",
  f17:"정령",
  f18:"정령",
  f19:"짐승",
  f20:"짐승",
  f21:"부족",
  f22:"장수",
  f23:"짐승",
  f24:"짐승",
  f25:"거인",
  f26:"짐승",
  f27:"거인",
  f28:"정령",
  l1:"부족",
  l2:"벌레",
  l3:"정령",
  l4:"명장",
  l5:"부족",
  l6:"정령",
  l7:"정령",
  l8:"정령",
  l9:"정령",
  l10:"장수",
  l11:"정령",
  l12:"기사",
  l13:"부족",
  l14:"정령",
  l15:"정령",
  l16:"정령",
  l17:"명장",
  l18:"기사",
  l19:"명장",
  l20:"거인",
  l21:"기사",
  l22:"정령",
  l23:"기사",
  l24:"정령",
  l25:"정령",
  l26:"거인",
  l27:"정령",
  l28:"거인",
  n1:"기수",
  n2:"장수",
  n3:"정령",
  n4:"정령",
  n5:"기수",
  n6:"기수",
  n7:"기수",
  n8:"기수",
  n9:"장수",
  n10:"기수",
  n11:"기수",
  n12:"기수",
  n13:"거인",
  n14:"부족",
  n15:"기수",
  n16:"기수",
  n17:"정령",
  n18:"부족",
  n19:"기수",
  n20:"기수",
  n21:"부족",
  n22:"정령",
  n23:"기수",
  n24:"거인",
  n25:"기수",
  n26:"기수",
  n27:"장수",
  n28:"명장",
  recruit:"짐승"
};
function parseCoin(v) {
  if (v == null || v === "") return 0;
  if (typeof v === "number" && isFinite(v)) return Math.max(-5, Math.min(5, v | 0));
  const s = String(v).trim();
  const neg = /^-/.test(s) || /−/.test(s) || /-\s*c/i.test(s);
  const nums = s.replace(/[xX×*]/g, " ").match(/-?\d+/g);
  if (!nums) return 0;
  let n = parseInt(nums[nums.length - 1], 10);
  if (/^-\d+$/.test(s)) n = parseInt(s, 10);
  if (neg && n > 0) n = -n;
  if (!isFinite(n)) return 0;
  return Math.max(-5, Math.min(5, n));
}
const FOCUS_X = {
  e2:0.58, e11:0.78, e15:0.70, e16:0.72, e5:0.42, e12:0.38,
  e3:0.40, e20:0.35, f2:0.70, f4:0.45, f10:0.55, f17:0.40,
  n2:0.55, n11:0.45, a1:0.62, a2:0.68, a6:0.55, a10:0.50, a17:0.60
};
const DECK_FRAMES = {
  earth: "assets/img/frames/rarity/earth_minion_common.png",
  fire: "assets/img/frames/unit/fire.png",
  wind: "assets/img/frames/unit/wind.png",
  water: "assets/img/frames/unit/water.png",
  light: "assets/img/frames/unit/light.png",
  dark: "assets/img/frames/unit/dark.png",
  metal: "assets/img/frames/unit/metal.png"
};
const SPELL_FRAMES = {
  earth: "assets/img/frames/rarity/earth_spell_common.png",
  metal: "assets/img/frames/unit/metal.png",
  fire: "assets/img/frames/spell/fire.webp",
  wind: "assets/img/frames/spell/wind.webp",
  water: "assets/img/frames/spell/water.webp",
  light: "assets/img/frames/spell/light.webp",
  dark: "assets/img/frames/spell/dark.webp"
};
const BADGES = {
  'mana': "assets/img/badges/mana.svg",
  'atk': "assets/img/badges/atk.svg",
  'def': "assets/img/badges/def.svg",
  'hp': "assets/img/badges/hp.svg",
};
const CARD_FACE = {"e1": "assets/img/faces/e1.jpg", "e2": "assets/img/faces/e2.jpg", "e3": "assets/img/faces/e3.jpg", "e4": "assets/img/faces/e4.jpg", "e5": "assets/img/faces/e5.jpg", "e6": "assets/img/faces/e6.jpg", "e7": "assets/img/faces/e7.jpg", "e8": "assets/img/faces/e8.jpg", "e9": "assets/img/faces/e9.jpg", "e10": "assets/img/faces/e10.jpg", "e11": "assets/img/faces/e11.jpg", "e12": "assets/img/faces/e12.jpg", "e13": "assets/img/faces/e13.jpg", "e14": "assets/img/faces/e14.jpg", "e15": "assets/img/faces/e15.jpg", "e16": "assets/img/faces/e16.jpg", "e17": "assets/img/faces/e17.jpg", "e18": "assets/img/faces/e18.jpg", "e19": "assets/img/faces/e19.jpg", "e20": "assets/img/faces/e20.jpg", "f1": "assets/img/faces/f1.jpg", "f2": "assets/img/faces/f2.jpg", "f3": "assets/img/faces/f3.jpg", "f4": "assets/img/faces/f4.jpg", "f5": "assets/img/faces/f5.jpg", "f6": "assets/img/faces/f6.jpg", "f7": "assets/img/faces/f7.jpg", "f8": "assets/img/faces/f8.jpg", "f9": "assets/img/faces/f9.jpg", "f10": "assets/img/faces/f10.jpg", "f11": "assets/img/faces/f11.jpg", "f12": "assets/img/faces/f12.jpg", "f13": "assets/img/faces/f13.jpg", "f14": "assets/img/faces/f14.jpg", "f15": "assets/img/faces/f15.jpg", "f16": "assets/img/faces/f16.jpg", "f17": "assets/img/faces/f17.jpg", "f18": "assets/img/faces/f18.jpg", "f19": "assets/img/faces/f19.jpg", "f20": "assets/img/faces/f20.jpg", "n1": "assets/img/faces/n1.jpg", "n2": "assets/img/faces/n2.jpg", "n3": "assets/img/faces/n3.jpg", "n4": "assets/img/faces/n4.jpg", "n5": "assets/img/faces/n5.jpg", "n6": "assets/img/faces/n6.jpg", "n7": "assets/img/faces/n7.jpg", "n8": "assets/img/faces/n8.jpg", "n9": "assets/img/faces/n9.jpg", "n10": "assets/img/faces/n10.jpg", "n11": "assets/img/faces/n11.jpg", "n12": "assets/img/faces/n12.jpg", "n13": "assets/img/faces/n13.jpg", "n14": "assets/img/faces/n14.jpg", "n15": "assets/img/faces/n15.jpg", "n16": "assets/img/faces/n16.jpg", "n17": "assets/img/faces/n17.jpg", "n18": "assets/img/faces/n18.jpg", "n19": "assets/img/faces/n19.jpg", "n20": "assets/img/faces/n20.jpg", "a1": "assets/img/faces/a1.jpg", "a2": "assets/img/faces/a2.jpg", "a3": "assets/img/faces/a3.jpg", "a4": "assets/img/faces/a4.jpg", "a5": "assets/img/faces/a5.jpg", "a6": "assets/img/faces/a6.jpg", "a7": "assets/img/faces/a7.jpg", "a8": "assets/img/faces/a8.jpg", "a9": "assets/img/faces/a9.jpg", "a10": "assets/img/faces/a10.jpg", "a11": "assets/img/faces/a11.jpg", "a12": "assets/img/faces/a12.jpg", "a13": "assets/img/faces/a13.jpg", "a14": "assets/img/faces/a14.jpg", "a15": "assets/img/faces/a15.jpg", "a16": "assets/img/faces/a16.jpg", "a17": "assets/img/faces/a17.jpg", "a18": "assets/img/faces/a18.jpg", "a19": "assets/img/faces/a19.jpg", "a20": "assets/img/faces/a20.jpg", "coin": "assets/img/faces/coin.jpg", "recruit": "assets/img/faces/recruit.jpg"};
const RARITY_FRAMES = {
  "earth|minion|common": "assets/img/frames/rarity/earth_minion_common.png",
  "earth|minion|rare": "assets/img/frames/rarity/earth_minion_rare.png",
  "earth|minion|heroic": "assets/img/frames/rarity/earth_minion_heroic.png",
  "earth|minion|legendary": "assets/img/frames/rarity/earth_minion_legendary.png",
  "earth|spell|common": "assets/img/frames/rarity/earth_spell_common.png",
  "earth|spell|rare": "assets/img/frames/rarity/earth_spell_rare.png",
  "earth|spell|heroic": "assets/img/frames/rarity/earth_spell_heroic.png",
  "earth|spell|legendary": "assets/img/frames/rarity/earth_spell_legendary.png"
};
function frameOf(c) {
  const tribe = (typeof TRIBES !== "undefined" && TRIBES.find(x => x.id === (c && c.tribe))) || { id: "earth" };
  if (c && (c.type === "spell" || c.type === "item") && typeof SPELL_FRAMES !== "undefined") return SPELL_FRAMES[tribe.id] || SPELL_FRAMES.earth;
  return (typeof DECK_FRAMES !== "undefined" && (DECK_FRAMES[tribe.id] || DECK_FRAMES.earth)) || "";
}
function pickFrameUrl(c, tribe) {
  const t = tribe || (typeof TRIBES !== "undefined" && TRIBES.find(x => x.id === (c && c.tribe))) || { id: "earth" };
  const kind = (c && (c.type === "spell" || c.type === "item")) ? "spell" : "minion";
  const rarity = (c && c.rarity) || "common";
  const key = (t.id || "earth") + "|" + kind + "|" + rarity;
  if (typeof RARITY_FRAMES !== "undefined" && RARITY_FRAMES[key]) return RARITY_FRAMES[key];
  // fallback same-tribe other rarity, then frameOf
  if (typeof RARITY_FRAMES !== "undefined") {
    const alt = ["common","rare","heroic","legendary"].map(r => (t.id||"earth") + "|" + kind + "|" + r).find(k => RARITY_FRAMES[k]);
    if (alt) return RARITY_FRAMES[alt];
  }
  return frameOf(c);
}
const CARD_ART = {"a1":"assets/img/art/a1.jpg","a2":"assets/img/art/a2.jpg","a3":"assets/img/art/a3.jpg","a4":"assets/img/art/a4.jpg","a5":"assets/img/art/a5.jpg","a6":"assets/img/art/a6.jpg","a7":"assets/img/art/a7.jpg","a8":"assets/img/art/a8.jpg","a9":"assets/img/art/a9.jpg","a10":"assets/img/art/a10.jpg","a11":"assets/img/art/a11.jpg","a12":"assets/img/art/a12.jpg","a13":"assets/img/art/a13.jpg","a14":"assets/img/art/a14.jpg","a15":"assets/img/art/a15.jpg","a16":"assets/img/art/a16.jpg","a17":"assets/img/art/a17.jpg","a18":"assets/img/art/a18.jpg","a19":"assets/img/art/a19.jpg","a20":"assets/img/art/a20.jpg","a21":"assets/img/art/a21.jpg","a22":"assets/img/art/a22.jpg","a23":"assets/img/art/a23.jpg","a24":"assets/img/art/a24.jpg","a25":"assets/img/art/a25.jpg","a26":"assets/img/art/a26.jpg","a27":"assets/img/art/a27.jpg","a28":"assets/img/art/a28.jpg","as1":"assets/img/art/as1.jpg","as2":"assets/img/art/as2.jpg","as3":"assets/img/art/as3.jpg","as4":"assets/img/art/as4.jpg","as5":"assets/img/art/as5.jpg","as6":"assets/img/art/as6.jpg","as7":"assets/img/art/as7.jpg","as8":"assets/img/art/as8.jpg","d1":"assets/img/art/d1.jpg","d2":"assets/img/art/d2.jpg","d3":"assets/img/art/d3.jpg","d4":"assets/img/art/d4.jpg","d5":"assets/img/art/d5.jpg","d6":"assets/img/art/d6.jpg","d7":"assets/img/art/d7.jpg","d8":"assets/img/art/d8.jpg","d9":"assets/img/art/d9.jpg","d10":"assets/img/art/d10.jpg","d11":"assets/img/art/d11.jpg","d12":"assets/img/art/d12.jpg","d13":"assets/img/art/d13.jpg","d14":"assets/img/art/d14.jpg","d15":"assets/img/art/d15.jpg","d16":"assets/img/art/d16.jpg","d17":"assets/img/art/d17.jpg","d18":"assets/img/art/d18.jpg","d19":"assets/img/art/d19.jpg","d20":"assets/img/art/d20.jpg","d21":"assets/img/art/d21.jpg","d22":"assets/img/art/d22.jpg","d23":"assets/img/art/d23.jpg","d24":"assets/img/art/d24.jpg","d25":"assets/img/art/d25.jpg","d26":"assets/img/art/d26.jpg","d27":"assets/img/art/d27.jpg","d28":"assets/img/art/d28.jpg","ds1":"assets/img/art/ds1.jpg","ds2":"assets/img/art/ds2.jpg","ds3":"assets/img/art/ds3.jpg","ds4":"assets/img/art/ds4.jpg","ds5":"assets/img/art/ds5.jpg","ds6":"assets/img/art/ds6.jpg","ds7":"assets/img/art/ds7.jpg","ds8":"assets/img/art/ds8.jpg","e1":"assets/img/art/e1.jpg","e2":"assets/img/art/e2.jpg","e3":"assets/img/art/e3.jpg","e4":"assets/img/art/e4.jpg","e5":"assets/img/art/e5.jpg","e6":"assets/img/art/e6.jpg","e7":"assets/img/art/e7.jpg","e8":"assets/img/art/e8.jpg","e9":"assets/img/art/e9.jpg","e10":"assets/img/art/e10.jpg","e11":"assets/img/art/e11.jpg","e12":"assets/img/art/e12.jpg","e13":"assets/img/art/e13.jpg","e14":"assets/img/art/e14.jpg","e15":"assets/img/art/e15.jpg","e16":"assets/img/art/e16.jpg","e17":"assets/img/art/e17.jpg","e18":"assets/img/art/e18.jpg","e19":"assets/img/art/e19.jpg","e20":"assets/img/art/e20.jpg","e21":"assets/img/art/e21.jpg","e22":"assets/img/art/e22.jpg","e23":"assets/img/art/e23.jpg","e24":"assets/img/art/e24.jpg","e25":"assets/img/art/e25.jpg","e26":"assets/img/art/e26.jpg","e27":"assets/img/art/e27.jpg","e28":"assets/img/art/e28.jpg","es1":"assets/img/art/es1.jpg","es2":"assets/img/art/es2.jpg","es3":"assets/img/art/es3.jpg","es4":"assets/img/art/es4.jpg","es5":"assets/img/art/es5.jpg","es6":"assets/img/art/es6.jpg","es7":"assets/img/art/es7.jpg","es8":"assets/img/art/es8.jpg","f1":"assets/img/art/f1.jpg","f2":"assets/img/art/f2.jpg","f3":"assets/img/art/f3.jpg","f4":"assets/img/art/f4.jpg","f5":"assets/img/art/f5.jpg","f6":"assets/img/art/f6.jpg","f7":"assets/img/art/f7.jpg","f8":"assets/img/art/f8.jpg","f9":"assets/img/art/f9.jpg","f10":"assets/img/art/f10.jpg","f11":"assets/img/art/f11.jpg","f12":"assets/img/art/f12.jpg","f13":"assets/img/art/f13.jpg","f14":"assets/img/art/f14.jpg","f15":"assets/img/art/f15.jpg","f16":"assets/img/art/f16.jpg","f17":"assets/img/art/f17.jpg","f18":"assets/img/art/f18.jpg","f19":"assets/img/art/f19.jpg","f20":"assets/img/art/f20.jpg","f21":"assets/img/art/f21.jpg","f22":"assets/img/art/f22.jpg","f23":"assets/img/art/f23.jpg","f24":"assets/img/art/f24.jpg","f25":"assets/img/art/f25.jpg","f26":"assets/img/art/f26.jpg","f27":"assets/img/art/f27.jpg","f28":"assets/img/art/f28.jpg","fs1":"assets/img/art/fs1.jpg","fs2":"assets/img/art/fs2.jpg","fs3":"assets/img/art/fs3.jpg","fs4":"assets/img/art/fs4.jpg","fs5":"assets/img/art/fs5.jpg","fs6":"assets/img/art/fs6.jpg","fs7":"assets/img/art/fs7.jpg","fs8":"assets/img/art/fs8.jpg","l1":"assets/img/art/l1.jpg","l2":"assets/img/art/l2.jpg","l3":"assets/img/art/l3.jpg","l4":"assets/img/art/l4.jpg","l5":"assets/img/art/l5.jpg","l6":"assets/img/art/l6.jpg","l7":"assets/img/art/l7.jpg","l8":"assets/img/art/l8.jpg","l9":"assets/img/art/l9.jpg","l10":"assets/img/art/l10.jpg","l11":"assets/img/art/l11.jpg","l12":"assets/img/art/l12.jpg","l13":"assets/img/art/l13.jpg","l14":"assets/img/art/l14.jpg","l15":"assets/img/art/l15.jpg","l16":"assets/img/art/l16.jpg","l17":"assets/img/art/l17.jpg","l18":"assets/img/art/l18.jpg","l19":"assets/img/art/l19.jpg","l20":"assets/img/art/l20.jpg","l21":"assets/img/art/l21.jpg","l22":"assets/img/art/l22.jpg","l23":"assets/img/art/l23.jpg","l24":"assets/img/art/l24.jpg","l25":"assets/img/art/l25.jpg","l26":"assets/img/art/l26.jpg","l27":"assets/img/art/l27.jpg","l28":"assets/img/art/l28.jpg","ls1":"assets/img/art/ls1.jpg","ls2":"assets/img/art/ls2.jpg","ls3":"assets/img/art/ls3.jpg","ls4":"assets/img/art/ls4.jpg","ls5":"assets/img/art/ls5.jpg","ls6":"assets/img/art/ls6.jpg","ls7":"assets/img/art/ls7.jpg","ls8":"assets/img/art/ls8.jpg","n1":"assets/img/art/n1.jpg","n2":"assets/img/art/n2.jpg","n3":"assets/img/art/n3.jpg","n4":"assets/img/art/n4.jpg","n5":"assets/img/art/n5.jpg","n6":"assets/img/art/n6.jpg","n7":"assets/img/art/n7.jpg","n8":"assets/img/art/n8.jpg","n9":"assets/img/art/n9.jpg","n10":"assets/img/art/n10.jpg","n11":"assets/img/art/n11.jpg","n12":"assets/img/art/n12.jpg","n13":"assets/img/art/n13.jpg","n14":"assets/img/art/n14.jpg","n15":"assets/img/art/n15.jpg","n16":"assets/img/art/n16.jpg","n17":"assets/img/art/n17.jpg","n18":"assets/img/art/n18.jpg","n19":"assets/img/art/n19.jpg","n20":"assets/img/art/n20.jpg","n21":"assets/img/art/n21.jpg","n22":"assets/img/art/n22.jpg","n23":"assets/img/art/n23.jpg","n24":"assets/img/art/n24.jpg","n25":"assets/img/art/n25.jpg","n26":"assets/img/art/n26.jpg","n27":"assets/img/art/n27.jpg","n28":"assets/img/art/n28.jpg","ns1":"assets/img/art/ns1.jpg","ns2":"assets/img/art/ns2.jpg","ns3":"assets/img/art/ns3.jpg","ns4":"assets/img/art/ns4.jpg","ns5":"assets/img/art/ns5.jpg","ns6":"assets/img/art/ns6.jpg","ns7":"assets/img/art/ns7.jpg","ns8":"assets/img/art/ns8.jpg"};

(function bootstrapCardArt() {
  if (typeof CARD_ART === "undefined" || typeof CARDS === "undefined") return;
  (CARDS || []).forEach(c => {
    if (!c || !c.id) return;
    if (c.type === "item") CARD_ART[c.id] = "assets/img/art/" + c.id + ".jpg";
  });
})();

const CARD_MAP = Object.fromEntries((CARDS || []).filter(c => c && c.id).map(c => [c.id, c]));

// Runtime roster guard — id prefix↔tribe, tribes equal count (28 now; may grow later; NOT a hard cap of 28)
(function assertUnitRoster() {
  if (typeof CARDS === "undefined") return;
  const letterTribe = { a: "water", d: "dark", e: "earth", f: "fire", l: "light", n: "wind" };
  const tribes = ["earth", "fire", "wind", "water", "light", "dark"];
  const counts = Object.fromEntries(tribes.map(t => [t, 0]));
  const idRe = /^[adefln]\d+$/;
  const badIds = [];
  const badTribe = [];
  for (const c of CARDS) {
    if (!c || c.type !== "minion" || c.token) continue;
    if (!idRe.test(c.id)) badIds.push(c.id);
    const expected = letterTribe[c.id && c.id[0]];
    if (expected && c.tribe !== expected) badTribe.push(c.id + ":" + c.tribe + "!=" + expected);
    if (counts[c.tribe] != null) counts[c.tribe]++;
  }
  const vals = tribes.map(t => counts[t]);
  const target = vals[0];
  const unequal = vals.some(v => v !== target);
  if (unequal || badIds.length || badTribe.length) {
    console.error("[cards-data] unit roster guard FAILED", { counts, unequal, badIds, badTribe });
  }
})();



let selectedHero = TRIBES.find(x => x.open);
let state = null;
let ui = { targeting: null, attacker: null, battling: false, rarityFilter: "all", typeFilter: "all" };


const CARD_LORE = {
  e25:"하늘이 갈라지고 산이 떨어진다. 독수리가 먼저 알고, 병사들은 나중에 안다.",
  e26:"땅이 제 무게를 잊으면 성도 떠오른다. 발밑이 비는 만큼 방어도 얇아진다.",
  e27:"거인을 묶는 사슬은 살이 아니라 이름을 묶는다. 힘이 있어도 주먹을 펼 수 없다.",
  e28:"바다 위로 섬이 솟는다. 빈 전장은 곧 새로운 땅이다.",
  e29:"쇠와 돌이 제 자리를 버리고 한곳으로 빨려든다. 무기를 든 손은 빈손이 된다.",
  e30:"산맥이 허리를 꺾으면 골짜기가 생기고, 그 골짜기가 적을 삼킨다.",
  e31:"모래는 기다린다. 빈자리가 많을수록 손이 많이 올라온다.",
  e32:"미로는 강한 자를 가둔다. 지금 이 땅의 한계를 넘는 것들은 길을 잃는다.",
  e33:"작은 것들은 땅속으로 숨는다. 주먹은 약해져도 등은 돌이 된다.",
  e34:"회오리는 가벼운 것부터 집어 올린다. 작은 목숨은 모래가 된다.",
  e35:"주먹을 모으면 방패도 돌이 된다. 한 번 내리치면 가죽이 아니라 뼈를 본다.",
  e36:"절벽은 언제나 무너질 준비를 한다. 작은 돌도 투구는 깬다.",
  e37:"거인의 숨이 가슴으로 들어온다. 주먹이 두 배로 무거워진다.",
  e38:"발이 빠지면 힘도, 가죽도, 숨도 같이 빠진다.",
  e39:"살았던 것이 돌이 되면 주먹은 멈추고 등만 단단해진다.",
  e40:"떠오른 섬에서 떨어진 한 조각. 작아도 땅은 땅이다.",

  e1:"바위 산맥이 걸어 다니기 시작했다. 발이 땅에 닿을 때마다 돌이 솟고, 주먹은 절벽이다. 한 번 자리를 잡으면 산이 된 것처럼 잘 움직이지 않는다.",
  e2:"사막 아래에 강처럼 긴 것이 산다. 모래가 갈라지면 입이 열리고, 그 입 안에는 또 사막이 있다.",
  e3:"닭의 머리와 뱀의 꼬리를 가진 짐승. 눈빛이 스치면 근육이 돌처럼 굳는다. 석화는 저주가 아니라 이 새의 숨결이다.",
  e4:"백 개의 눈을 가진 돌사자. 잠든 척하지만 모든 방향을 동시에 본다. 한 눈이 감겨도 아흔아홉이 남는다.",
  e5:"사자의 몸, 전갈의 꼬리. 사막의 왕좌를 가시로 지킨다. 독침이 땅에 꽂히면 모래가 끓는다.",
  e6:"보물상자로 위장한 황금 짐승. 뚜껑을 여는 손만 기다린다. 탐욕이 미끼고, 이빨이 덫이다.",
  e7:"가시만 남은 사람 꼴. 안으면 피가 난다. 그래서 아무도 안지 않고, 그 점이 이 자의 갑옷이다.",
  e8:"거친 언덕의 전사. 투박한 도끼와 더 투박한 맹세. 화려한 주문은 못 하지만 한 대는 정직하다.",
  e9:"모래를 등 위에 지고 달리는 멧돼지 인간. 돌진이 시작되면 제동은 없다.",
  e10:"늪이 사람으로 일어선 것. 발이 빠지는 곳이 이 자의 집이고, 집 전체가 무기이다.",
  e11:"모래 바람 속의 작은 정령. 작아서 무시당하지만, 눈에 들어가면 폭풍이 된다.",
  e12:"바위 절벽을 나는 날개 달린 도마뱀. 그림자가 땅을 덮으면 이미 늦다.",
  e13:"허리 아래가 뱀인 사막의 무희. 노래가 끝나면 뼈만 남는다.",
  e14:"낮에는 표범, 밤에도 표범. 사람 가죽은 축제 때나 입는다.",
  e15:"동굴 천장의 여덟 다리. 거미줄은 지도이고, 지도의 한가운데가 입이다.",
  e16:"백 마디가 따로 움직이는 모래 지네. 한 마디를 잘라내도 아흔아홉이 기어온다.",
  e17:"콜키스의 청동 황소. 콧구멍에서 증기가 나고, 발굽이 신전 기둥을 가루로 만든다. 돌진은 저주가 아니라 이 황소의 걸음이다.",
  e18:"머리가 둘인 거인. 한쪽이 잠들면 다른 쪽이 싸운다. 합의가 안 될 때는 둘 다 도끼를 든다.",
  e19:"모래가 사람 모양을 유지하는 동안만 산다. 바람이 거세면 흩어지고, 다시 모이면 또 싸운다.",
  e20:"사자의 몸에 사람의 얼굴을 한 수호자. 수수께끼를 못 맞히면 돌이 되고, 맞춰도 쉽게 길을 열어주지 않는다.",
  e21:"서량의 먼지를 먹고 자란 기병. 말발굽이 닿는 땅마다 바위가 창처럼 일어난다. 창과 갑옷을 함께 쓰는 서량의 화신.",
  e22:"대지 전선을 이끄는 장군. 창끝이 땅을 찍으면 병사들의 발도 굳어진다.",
  e23:"모래 바람을 읽는 여장군. 한 번의 손짓으로 전열이 다시 선다.",
  e24:"아직 어린 어깨에 갑옷을 맞춘 신예 장수. 작은 창이지만 흙을 가르는 힘은 분명하다.",
  f1:"난로에서 튀어나온 작은 불씨. 장난처럼 붙지만, 커튼을 만나면 진지해진다.",
  f2:"재 더미에서 태어난 쥐. 타다 남은 것을 먹고, 아직 안 탄 것을 찾아 다닌다.",
  f3:"시위에 불꽃을 매는 한 발. 맞은 자리는 검게 남고, 연기는 이름을 지운다.",
  f4:"꼬리가 횃불인 여우. 달릴 때마다 들판에 점이 찍힌다. 점이 이어지면 산불이다.",
  f5:"주먹이 식기 전에 휘두르는 용암. 한 대가 벽을 녹인다.",
  f6:"하늘이 노을이 아니라 분노로 물드는 주문. 그늘이 없어진다.",
  f7:"불꽃을 갑옷처럼 두른 전사. 다가가면 눈썹이 먼저 탄다.",
  f8:"마을을 약탈하고 지붕을 횃불로 남긴다. 남는 것은 재와 웃는 얼굴이다.",
  f9:"손바닥에서 굴러가는 작은 태양. 던지면 커지고, 맞으면 밤이 된다.",
  f10:"용암 강에서 나온 사냥개. 숨결이 쇳물을 말린다.",
  f11:"재를 점으로 읽는 주술사. 타버린 뼈로 미래를 말하고, 미래는 항상 뜨겁다.",
  f12:"채찍이 불꽃의 혀다. 한 번 휘두르면 세 곳이 동시에 운다.",
  f13:"땅속에서 올라온 지옥의 꽃. 향기가 아니라 비명으로 핀다.",
  f14:"화산이 거인으로 일어선 것. 한 걸음에 능선이 무너진다.",
  f15:"창끝에 태양을 꽂은 기사. 돌진하는 길이 곧 낙화다.",
  f16:"작은 불덩이를 탄환처럼 쏜다. 한 발은 약해 보여도, 두 번째가 숨통이다.",
  f17:"털 대신 재를 두른 늑대. 울음이 끝나면 숲이 검게 남는다.",
  f18:"한낮을 한순간에 정오로 만드는 폭염. 그늘을 찾는 자는 이미 늦다.",
  f19:"돌과 불이 한 몸으로 굳은 골렘. 식으면 석상이고, 달아오르면 요새다.",
  f20:"가슴에 심장을 불로 갈아 넣은 자. 고동이 한 번 칠 때마다 전장이 밝아진다.",
  f21:"장판교의 고함이 불길이 된 장수. 창은 화산이고 갑옷은 거의 없다. 한 수가 전장을 태운다.",
  n1:"바람보다 가벼운 요정. 손바닥에 올려도 티끌만 남지만, 그 티끌이 폭풍의 씨앗이다.",
  n2:"깃털이 돛인 작은 도마뱀. 절벽에서 뛰어내려도 떨어지지 않는다. 떨어지는 것은 적이다.",
  n3:"칼이 아니라 칼 모양의 돌풍. 베인 줄도 모르게 옷깃이 갈라진다.",
  n4:"매와 한 몸을 이룬 사냥꾼. 창보다 먼저 그림자가 내려앉는다.",
  n5:"회오리를 치마처럼 두른 무희. 한 바퀴 돌면 진형이 흩어진다.",
  n6:"칼날이 된 바람. 방향만 있고 손잡이는 없다.",
  n7:"말 대신 돌풍을 탄 기수. 지나간 자리의 깃발이 모두 반대쪽을 본다.",
  n8:"망토가 방패인 자. 펼치면 화살이 길을 잃고, 접으면 칼이 된다.",
  n9:"창에 태풍을 묶은 창병. 찌르지 않아도 적이 흔들린다.",
  n10:"하늘이 낮아지는 주문. 지붕이 먼저 항복한다.",
  n11:"구름을 발굽 삼아 달리는 사슴. 잡히려는 손에는 안개만 남는다.",
  n12:"귀에만 들리는 바람. 속삭임이 끝나면 칼이 이미 등 뒤에 있다.",
  n13:"하늘 길을 훔치는 도적. 발자국이 구름에만 찍힌다.",
  n14:"공기를 베어 진공을 남기는 일격. 막으려는 방패가 먼저 풀려 나간다.",
  n15:"폭풍을 왕관으로 쓴 군주. 명령은 천둥이고, 신하는 비바람이다.",
  n16:"연에 올라탄 기사. 실이 끊기면 적이 떨어지고, 자신은 더 높이 간다.",
  n17:"울음이 바람인 늑대. 울음이 골짜기를 한 바퀴 돌면 사냥이 시작된다.",
  n18:"발밑을 들어 올리는 기류. 서 있던 자가 갑자기 하늘 손님이 된다.",
  n19:"바람의 이름만 남은 정령. 만지면 손만 차갑고, 놓치면 집이 날아간다.",
  n20:"바람으로 짠 방패. 창을 받아내면 창이 방향을 잃는다.",
  n21:"장판의 창기병. 일곱 번 적진을 드나들어도 흰 갑옷의 먼지만 남을 뿐, 창끝은 늘 바람을 먼저 가른다.",
  a1:"물방울이 점액이 된 작은 생명. 밟으면 퍼지고, 퍼진 자리에서 다시 모인다.",
  a2:"개울 돌 위의 개구리. 울음이 비가 되고, 비가 되면 개울이 강이 된다.",
  a3:"상처에 손을 담그면 물이 피를 밀어낸다. 샘은 질문이 없고, 치유만 한다.",
  a4:"파도를 창처럼 쓰는 병사. 한 번 찌르면 두 번째 파도가 따라온다.",
  a5:"화살촉이 얼음인 한 발. 맞은 자리는 움직임을 잃는다.",
  a6:"투명한 우산 아래 독이 있다. 예쁜 것을 먼저 보고, 독은 나중에 본다.",
  a7:"강가에서 달을 부르는 무녀. 물이 차오르면 적의 발목이 먼저 잠긴다.",
  a8:"썰물이 끝난 자리에 밀물이 밀고 들어온다. 이 주문은 그 밀물이다.",
  a9:"산호로 된 갑옷의 수호자. 산호초가 성벽이고, 성벽이 숨 쉰다.",
  a10:"심해에서 올라온 상어. 빛이 없는 곳에서 이빨만 빛난다.",
  a11:"지평선이 일어서는 해일. 막으려는 방벽이 장난감이 된다.",
  a12:"물 위에 비친 자신을 찌르면, 진짜가 다친다. 거울은 공평하다.",
  a13:"파도를 망토로 두른 기사. 말이 없어도 물길이 길이 된다.",
  a14:"허파에 물을 채우는 저주. 발은 땅에 있어도 숨은 바다에 있다.",
  a15:"해구에서 일어난 거인. 한 손이 배를 집어 든다.",
  a16:"빗방울이 사람으로 모인 정령. 맑은 날에는 약하고, 장마에는 왕이다.",
  a17:"연못을 집으로 아는 거북. 등딱지가 방패고, 방패가 섬이다.",
  a18:"물을 오래 바라본 자의 지혜. 물결 하나에 전장의 흐름이 보인다.",
  a19:"얼어붙은 강이 방패가 된 수호자. 녹을 때까지는 뚫리지 않는다.",
  a20:"조수를 읽는 술사. 밀물과 썰물을 한 손에 쥐고 전장을 흔든다.",
  a21:"의형제의 맹세를 강물에 새긴 장군. 청룡언월도가 물을 가르면 적의 기세가 썰물처럼 빠진다. 강이 제방을 지키듯, 관우는 전장의 한가운데를 지킨다.",
  l1:"햇살을 날개에 묻힌 나방. 어두운 곳에 앉으면 그곳이 잠시 낮이 된다.",
  l2:"뿔에 아침을 인 사슴. 숲이 길을 열고, 짐승들이 고개를 숙인다.",
  l3:"손에서 터지는 작은 태양. 그림자가 숨을 곳이 없어진다.",
  l4:"창끝에 정오를 단 창병. 찌르는 방향이 곧 동쪽이다.",
  l5:"상처 위에 내려앉는 빛. 피가 멈추고, 이름이 다시 또렷해진다.",
  l7:"흰 갑옷에 태양을 새긴 기사. 방패가 빛이면, 칼은 그 빛의 가장자리이다.",
  l8:"빛으로 짠 방패를 세운 자. 앞을 가리면 화살이 길을 잃고 무릎을 꿇는다.",
  l9:"죄의 무게를 재는 빛. 저울이 기울면 적이 먼저 쓰러진다.",
  l10:"날개로 아군을 가리는 천사. 그림자가 덮인 자는 한 번 더 일어선다.",
  l11:"갈기에 아침이 걸린 사자. 포효가 골짜기를 금빛으로 물들인다.",
  l12:"어둠을 씻어 내는 빛. 남은 것은 이름과 뼈다.",
  l15:"대리석과 태양이 한 몸이 된 골렘. 금이 간 자리에 빛이 맥동한다.",
  l17:"흰 털에 금빛 문양을 새긴 늑대. 눈 위를 달려도 발자국이 빛으로 남는다.",
  l18:"짧게 스치는 축복. 숨이 한 칸 더 길어진다.",
  l21:"정오의 태양을 시위에 매는 노궁수. 갑옷은 얇아도 화살 한 대가 갑옷을 무시하고 들어간다. 빛은 숨기지 않는다.",
  d1:"달 없는 밤의 박쥐. 날개 소리가 들리면 이미 목덜미에 있다.",
  d2:"저주를 먹고 커진 쥐. 빨간 눈이 곡식보다 심장을 먼저 찾는다.",
  d3:"빛 없이 날아가는 화살. 맞은 자리에 구멍이 아니라 그늘이 남는다.",
  d6:"무덤에서 일어난 해골 병사. 명령은 잊었고, 베는 법만 기억한다.",
  d8:"이름이 지워지는 말. 저주가 끝나면 적에게 내일의 몫이 없다.",
  d11:"정글 밤의 흑표범. 얼룩이 없어서 달빛도 이 짐승 위에서는 길을 잃는다.",
  d13:"성스러운 서약을 거꾸로 읽은 기사. 갑옷은 남고 빛은 빠져나갔다.",
  d14:"적의 숨결을 빨아 자기 맥으로 넣는 주문. 한쪽이 옅어지면 다른 쪽이 진해진다.",
  d18:"이름이 파멸인 밤. 하늘이 닫히고, 남은 것은 발소리뿐이다.",
  d19:"영혼을 촛불처럼 켜 두는 리치. 지팡이의 해골이 웃으면 전장에 겨울이 온다.",
  d21:"방천화극을 든 채 맹세를 갈아탄 무신. 창과 갑옷은 최상이나 마음은 얇다. 암흑은 힘을 빌려주고 충성은 빌려주지 않는다."
};
