const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});try{
const p=await b.newPage({viewport:{width:1600,height:900}});await p.goto(process.env.GAME_BASE||'http://127.0.0.1:8765');const rows=await p.evaluate(ids=>ids.map(id=>CARD_MAP[id]),["ls3", "ei3", "ei4", "ei5", "ei6", "fi1", "fi3", "fi5", "ni1", "ni2", "ni5", "ni6", "ai2", "ai3", "ai4", "ai5", "ai6", "li5", "li6", "di2", "di3", "di4", "di5", "di6", "ds2", "ls4", "es8", "fs7", "ds4", "ds7", "di7", "li7", "ei7", "ni7", "ai7", "fi7", "ns9", "fs9", "ls9", "ds9", "e30", "e31", "e32", "e33", "f30", "f31", "f32", "f33", "n30", "n31", "n32", "n33", "a30", "a31", "a32", "a33", "l30", "l31", "l32", "l33", "d30", "d31", "d32", "d33"]);fs.mkdirSync('description-qa/consistency',{recursive:true});
for(const c of rows){await p.evaluate(async id=>{const c=CARD_MAP[id];selectedHero=TRIBES.find(t=>t.id===c.tribe);ui.searchQuery=c.name;showBuilder();await openCardLore(id)},c.id);const effect=p.locator('#loreSkills .lore-skill').filter({has:p.locator('b',{hasText:'카드 효과'})});if(c.text){assert.equal(await effect.count(),1,c.id);assert.equal(await effect.locator('span').innerText(),c.text,c.id);}await p.click('#btnLoreClose');}
const overflow=[];
for(const [w,h] of [[1600,900],[844,390]]){await p.setViewportSize({width:w,height:h});for(const id of ['di7','ds4','ai7','fi7','e33','d32']){await p.evaluate(async id=>{const c=CARD_MAP[id];selectedHero=TRIBES.find(t=>t.id===c.tribe);ui.searchQuery=c.name;showBuilder();await openCardLore(id)},id);await p.screenshot({path:`description-qa/consistency/detail-${id}-${w}.png`});await p.click('#btnLoreClose');await p.evaluate(id=>showPoolTip(document.querySelector(`#cardPool .pool-item[data-id="${id}"]`),id),id);await p.locator('#poolTip').focus();const box=await p.locator('#poolTip').boundingBox();if(box.y+box.height>h)overflow.push({id,w,h,box});await p.screenshot({path:`description-qa/consistency/hover-${id}-${w}.png`});await p.evaluate(()=>hidePoolTip());}}
assert.deepEqual(overflow,[],'full explanations fit viewport with scrolling');
await p.evaluate(()=>showPoolTip(document.querySelector('#cardPool .pool-item[data-id="d32"]'),'d32'));
const tip=p.locator('#poolTip');await tip.focus();const box=await tip.boundingBox();await p.mouse.move(box.x+20,box.y+20);await p.waitForTimeout(200);await p.mouse.wheel(0,800);await p.waitForTimeout(150);assert.equal(await tip.isVisible(),true);assert.ok(await tip.evaluate(e=>e.scrollTop>0),'long hover text can be scrolled without disappearing');
await p.mouse.move(0,0);await p.waitForTimeout(200);assert.equal(await tip.isVisible(),true,'focused tooltip survives pointer exit');await p.keyboard.press('Escape');assert.equal(await tip.isVisible(),false);assert.equal(await tip.getAttribute('aria-hidden'),'true');assert.equal(await p.locator('#cardPool .pool-item[data-id="d32"]').evaluate(e=>e===document.activeElement),true,'Escape restores anchor focus');
console.log(JSON.stringify({checked:rows.length,overflow,scroll:'passed'}));fs.writeFileSync('description-qa/consistency/evidence.json',JSON.stringify({checked:rows.length,overflow},null,2));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
