const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('../test-support/combat-fx-fixture');
const flush=()=>new Promise(r=>setImmediate(r));
function setup(){const f=fixture(),pending=[],signals=[],disposed=[];f.ctx.AbortController=AbortController;f.ctx.CombatMedia={prepare:(kind,signal)=>new Promise((resolve,reject)=>{signals.push(signal);pending.push({resolve:()=>resolve({providers:{attack:()=>f.provider('attack'),defend:()=>f.provider('defend')},dispose:()=>disposed.push(kind)}),reject});})};return {...f,pending,signals,disposed};}
function entries(f,times){return [0,1,2].map(i=>({kind:'attack',opts:{uid:String(i),damage:2,onImpact:()=>{times.push(f.ctx.performance.now());return 2;}}}));}
test('batch waits for every media pack then impacts on the same frame with one sound',async()=>{const f=setup(),times=[];const p=f.fx.playBatch(entries(f,times));f.pending[0].resolve();await flush();f.advance(250);assert.equal(times.length,0);f.pending[1].resolve();await flush();f.advance(100);assert.equal(times.length,0);f.pending[2].resolve();await flush();f.advance(16);assert.equal(times.length,3);assert.equal(new Set(times).size,1);assert.equal(f.events.filter(x=>x==='sound:attack').length,1);f.advance(900);await p;assert.equal(f.fx.pending(),0);assert.equal(f.disposed.length,3);});
test('clear during batch preparation settles without impacts and disposes late media',async()=>{const f=setup(),times=[];const p=f.fx.playBatch(entries(f,times));f.pending[0].resolve();await flush();f.fx.clear();assert.ok((await p).every(x=>x.cancelled));assert.equal(times.length,0);assert.ok(f.signals.every(x=>x.aborted));f.pending.slice(1).forEach(x=>x.resolve());await flush();assert.equal(f.disposed.length,3);assert.equal(f.fx.pending(),0);});
test('hidden preparation settles every impact once without late audio',async()=>{const f=setup(),times=[];const p=f.fx.playBatch(entries(f,times));f.ctx.document.hidden=true;f.listeners.visibilitychange();await p;assert.equal(times.length,3);f.pending.forEach(x=>x.resolve());await flush();f.advance(1000);assert.equal(times.length,3);assert.equal(f.events.filter(x=>typeof x==='string'&&x.startsWith('sound:')).length,0);assert.equal(f.fx.pending(),0);});
test('failed preparation does not reject the batch or hold other targets',async()=>{const f=setup(),times=[];const p=f.fx.playBatch(entries(f,times));f.pending[0].reject(Error('decoder unavailable'));f.pending.slice(1).forEach(x=>x.resolve());await flush();f.advance(1000);const results=await p;assert.equal(times.length,3);assert.ok(results.every(x=>!x.cancelled));assert.equal(f.fx.pending(),0);});
test('invalidated batch never starts and no attempted entries cannot impact',async()=>{const f=setup(),times=[];let valid=true;const items=entries(f,times);items.forEach(x=>x.opts.valid=()=>valid);const p=f.fx.playBatch(items);valid=false;f.pending.forEach(x=>x.resolve());await flush();assert.ok((await p).every(x=>x.cancelled));assert.equal(times.length,0);const q=f.fx.playBatch([{kind:'attack',opts:{attempted:false,onImpact:()=>times.push(1)}}]);await q;assert.equal(times.length,0);});
test('clear and hidden during playback settle children and stop the single owned sound',async()=>{for(const mode of ['clear','hidden']){const f=setup(),times=[];const p=f.fx.playBatch(entries(f,times));f.pending.forEach(x=>x.resolve());await flush();f.advance(16);assert.equal(times.length,3);if(mode==='clear')f.fx.clear();else{f.ctx.document.hidden=true;f.listeners.visibilitychange();}await p;assert.equal(times.length,3);assert.equal(f.fx.pending(),0);assert.equal(f.jobs.size,0);assert.equal(f.events.filter(x=>x==='sound:attack').length,1);assert.equal(f.events.filter(x=>x==='stop:attack').length,1);}});
test('failed pack and prepared packs still impact on one shared frame',async()=>{const f=setup(),times=[];const p=f.fx.playBatch(entries(f,times));f.pending[0].reject(Error('missing'));f.pending.slice(1).forEach(x=>x.resolve());await flush();assert.equal(times.length,0);f.advance(16);assert.equal(new Set(times).size,1);assert.equal(times.length,3);f.advance(900);await p;});
test('mixed shield and damage batch selects one attack sound; actual all-zero selects defense',async()=>{for(const actual of [2,0]){const f=setup(),items=entries(f,[]);items[0].kind='defend';items[0].opts.damage=0;items[0].opts.onImpact=()=>0;items[1].opts.onImpact=()=>actual;items[2].opts.onImpact=()=>0;const p=f.fx.playBatch(items);f.pending.forEach(x=>x.resolve());await flush();f.advance(1000);await p;assert.deepEqual(f.events.filter(x=>typeof x==='string'&&x.startsWith('sound:')),['sound:'+(actual?'attack':'defend')]);}});
test('a failed first pack cannot mute a later available sound provider',async()=>{const f=setup(),p=f.fx.playBatch(entries(f,[]));f.pending[0].reject(Error('missing first pack'));f.pending.slice(1).forEach(x=>x.resolve());await flush();f.advance(1000);await p;assert.deepEqual(f.events.filter(x=>typeof x==='string'&&x.startsWith('sound:')),['sound:attack']);});
