const test=require('node:test'),assert=require('node:assert/strict');
const {loadGame,setup,place,vm}=require('../test-support/harness');
function battle(a={},d={}){
 const g=loadGame(),{p1,p2}=setup(g),attacker=place(g,p1,'e1'),defender=place(g,p2,'e8');
 for(const m of [attacker,defender])Object.assign(m,{atkC:0,defC:0,hpC:0,atkSkill:1,ability:null,keywords:[],hp:10,maxHp:10,atk:3,def:0});
 Object.assign(attacker,a);Object.assign(defender,d);
 const calls=[],listeners=new Set();let generation=0;
 g.CombatFx={generation:()=>generation,onCancel:f=>{listeners.add(f);return()=>listeners.delete(f)},clear:()=>{generation++;for(const f of listeners)f()},snapshot:uid=>({uid}),play:async(kind,opts)=>{calls.push({kind,opts});if(opts.onImpact){opts.onImpact();opts.onImpact();}return {};}};
 return {g,p1,p2,attacker,defender,calls,attack:()=>g.doAttack(p1,attacker,{kind:'minion',owner:p2,minion:defender})};
}
test('impact is once-only; positive HP damage never plays defend',async()=>{const b=battle({}, {atk:0});await b.attack();assert.equal(b.defender.hp,7);assert.deepEqual(b.calls.map(x=>x.kind),['attack']);assert.equal(b.g.__s.busy,undefined);});
test('full block or shield plays defend with no damage pop',async()=>{for(const opts of [{def:9},{ability:'보호',keywords:['shield']}]){const b=battle({}, {...opts,atk:0});await b.attack();assert.equal(b.defender.hp,10);assert.equal(b.calls[0].kind,'defend');assert.equal(b.calls[0].opts.damage,0);}});
test('death uses pre-hit snapshot once despite repeated renders',async()=>{const b=battle({atk:20},{atk:0});await b.attack();const deaths=b.calls.filter(x=>x.kind==='death');assert.equal(deaths.length,1);assert.equal(deaths[0].opts.snapshots[0].uid,b.defender.uid);assert.equal(b.p2.board.length,0);});
test('rebirth can die again in the same consecutive attack',async()=>{const b=battle({atk:20,atkSkill:4},{atk:0,ability:'환생',keywords:['rebirth']});await b.attack();assert.equal(b.calls.filter(x=>x.kind==='death').length,2);});
test('async coin callback failure settles combat and releases owned lock',async()=>{const b=battle();vm.runInContext('render=function(){throw Error("render failure")}',b.g);await b.attack();assert.equal(b.g.__s.busy,undefined);});
test('clear while coin callback pending settles and stale callback cannot mutate a new game',async()=>{const b=battle();let callback;b.g.__capture=f=>callback=f;vm.runInContext('showCoinResult=(t,r,done)=>__capture(done)',b.g);const pending=b.attack();b.g.CombatFx.clear();await pending;const newer=setup(b.g);newer.p1.hp=27;b.g.__s.busy=true;await callback();assert.equal(newer.p1.hp,27);assert.equal(b.g.__s.busy,true);assert.equal(b.defender.hp,10);assert.equal(b.calls.length,0);});
test('zero-damage counter is a block effect rather than a hit',async()=>{const b=battle({def:10},{atk:1});await b.attack();assert.deepEqual(b.calls.map(x=>x.kind),['attack','defend']);assert.equal(b.attacker.hp,10);});

test('positive counter uses the same attack presentation as the initiating strike',async()=>{const b=battle();await b.attack();assert.deepEqual(b.calls.map(x=>x.kind),['attack','attack']);assert.equal(b.attacker.hp,7);});
test('no attack rights produces no combat presentation or legacy sound',async()=>{const b=battle({canAttack:false});let sound=0;b.g.Sfx={playSlash:()=>sound++,playParry:()=>sound++,playHeroHit:()=>sound++};await b.attack();assert.equal(b.calls.length,0);assert.equal(sound,0);assert.equal(b.defender.hp,10);});
test('hero strike suppresses legacy hero-hit sound while spell damage retains it',async()=>{const b=battle();b.p2.board=[];let sound=0;b.g.Sfx={playHeroHit:()=>sound++};await b.g.doAttack(b.p1,b.attacker,{kind:'hero',owner:b.p2});assert.equal(b.p2.hp,27);assert.equal(sound,0);b.g.dealHero(b.p2,1);assert.equal(sound,1);});
test('impact returns actual capped HP damage, including shield and critical kill',async()=>{for(const [a,d,want] of [[{atk:20},{atk:0,hp:4},4],[{atk:20},{atk:0,ability:'보호',keywords:['shield']},0],[{atk:2,atkSkill:5},{atk:0,hp:10},10]]){const b=battle(a,d);let result;b.g.CombatFx.play=async(kind,o)=>{b.calls.push({kind,opts:o});if(o.onImpact){result=o.onImpact();assert.equal(o.onImpact(),result);}return {};};await b.attack();assert.equal(result,want);}});
test('failed media rendering preserves damage, counter and attack ownership',async()=>{const b=battle();const f=require('../test-support/combat-fx-fixture').fixture();f.fx.setMedia({attack:()=>({draw(){throw Error('decoder failure')},startSound(){return()=>{}}})});b.g.CombatFx=f.fx;let done=false;const p=b.attack().then(()=>done=true);for(let i=0;i<12&&!done;i++){await new Promise(r=>setImmediate(r));f.advance(1000);}assert.equal(done,true);await p;assert.equal(b.defender.hp,7);assert.equal(b.attacker.hp,7);assert.equal(b.g.__s.busy,undefined);assert.equal(f.fx.pending(),0);});
test('cancelled AI combat cannot pass a replacement game turn',async()=>{const b=battle();b.p1.isAI=true;b.p1.soul=0;b.p1.deck=[];let settle,passes=0;let started=false;b.g.__auto=()=>{started=true;return new Promise(r=>settle=r)};b.g.__pass=()=>passes++;vm.runInContext('runAutoCombat=__auto;passTurn=__pass',b.g);b.g.aiTurn();for(let i=0;i<5&&!started;i++)await new Promise(r=>setImmediate(r));assert.equal(started,true);setup(b.g);settle(false);await new Promise(r=>setImmediate(r));assert.equal(passes,0);});
test('stale scheduled AI step cannot attack after game replacement',async()=>{const b=battle();b.p1.isAI=true;b.p1.soul=0;b.p1.deck=[];let attacks=0;b.g.__auto=async()=>{attacks++;return true};vm.runInContext('runAutoCombat=__auto;passTurn=()=>{}',b.g);b.g.aiTurn();setup(b.g);await new Promise(r=>setImmediate(r));assert.equal(attacks,0);});
test('combat death stays hidden until removal; spell death keeps its legacy class',async()=>{const b=battle({atk:20},{atk:0});assert.equal(typeof b.g.combatDeathClass,'function');const observed=[];b.g.__observe=()=>{if(b.defender.dying)observed.push(b.g.combatDeathClass(b.defender));};vm.runInContext('render=__observe',b.g);await b.attack();assert.ok(observed.length>0);assert.ok(observed.every(x=>x==='combat-death-hidden'));assert.equal(b.g.combatDeathClass(b.defender),'rip');});
test('leaving battle cancels waiting ownership before stale coin callback',async()=>{const b=battle();let callback;b.g.__capture=f=>callback=f;vm.runInContext('showCoinResult=(t,r,done)=>__capture(done);clearDrag=()=>{}',b.g);let done=false;const p=b.attack().then(()=>done=true);b.g.hideScreens();await new Promise(r=>setImmediate(r));assert.equal(done,true);await p;await callback();assert.equal(b.defender.hp,10);assert.equal(b.calls.length,0);});
test('both coin deaths share one presentation and duplicate cleanup does not replay them',async()=>{
 const b=battle();vm.runInContext('turnCoinRoll=()=>({n:1,heads:0,dAtk:0,dDef:0,dHp:-20,flips:[false]})',b.g);
 const waiting=[];b.g.CombatFx.play=(kind,opts)=>{b.calls.push({kind,opts});return new Promise(r=>waiting.push(r));};
 const pending=b.attack();for(let i=0;i<4;i++)await new Promise(r=>setImmediate(r));
 assert.equal(waiting.length,1);assert.ok(b.calls.every(c=>c.kind==='death'));waiting.forEach(r=>r({}));await pending;assert.equal(b.calls.length,1);
});
