const {chromium}=require(process.env.PLAYWRIGHT_MODULE),fs=require('fs'),assert=require('assert/strict');
const expected=require('../test-support/approved-description-wrap.json');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});const out=process.env.QA_OUTPUT||'wrap-browser-qa';fs.mkdirSync(out,{recursive:true});try{
const p=await b.newPage({viewport:{width:1600,height:900}});await p.goto(process.env.QA_BASE_URL||'http://127.0.0.1:8766');await p.evaluate(()=>document.fonts.ready);
const rows=await p.evaluate(async()=>{const fill=CanvasRenderingContext2D.prototype.fillText;let active=null;const rows=[];window.qaFaces={};CanvasRenderingContext2D.prototype.fillText=function(text,x,y,...rest){if(active&&this.canvas.width===768&&/45px/.test(this.font))active.lines.push({text,width:this.measureText(text).width,font:this.font});return fill.call(this,text,x,y,...rest)};try{for(const c of CARDS){active={id:c.id,name:c.name,token:!!c.token,lines:[]};qaFaces[c.id]=await composeCardFace(c);rows.push(active);active=null;}}finally{CanvasRenderingContext2D.prototype.fillText=fill;}return rows;});assert.equal(rows.filter(x=>!x.token).length,300);assert.ok(rows.every(x=>x.lines.length<=2));for(const r of rows){for(const l of r.lines){assert.ok(l.width<=476.16+1,r.id);assert.equal((l.text.match(/\(/g)||[]).length,(l.text.match(/\)/g)||[]).length,r.id+' balanced parentheses');if(r.lines.length===2)assert.ok(!/^(생성|파괴|처치|탈취|[가-힣])$/.test(l.text.trim()),r.id+' orphan');}if(expected[r.id])assert.deepEqual(r.lines.map(l=>l.text),expected[r.id].split('\n'),r.id);}
fs.writeFileSync(out+'/render-audit.json',JSON.stringify(rows,null,2));
for(const [w,h] of [[1600,900],[844,390]]){await p.setViewportSize({width:w,height:h});await p.evaluate(async()=>{selectedHero=TRIBES.find(t=>t.id==='earth');ui.searchQuery=CARD_MAP.es9.name;showBuilder();await openCardLore('es9');});assert.ok((await p.locator('#loreSkills').innerText()).includes('(4/0/9)'));await p.screenshot({path:out+`/es9-detail-${w}.png`});await p.click('#btnLoreClose');await p.evaluate(()=>showPoolTip(document.querySelector('#cardPool .pool-item[data-id="es9"]'),'es9'));assert.ok((await p.locator('#poolTip').innerText()).includes('(4/0/9)'));const rect=await p.locator('#poolTip').boundingBox();assert.ok(rect.y>=0&&rect.y+rect.height<=h+1);await p.screenshot({path:out+`/es9-tooltip-${w}.png`});await p.evaluate(()=>hidePoolTip());await p.evaluate(()=>{startGame(false);state.busy=false;state.over=false;state.turn=1;state.p1.isAI=false;state.p1.hand=[cloneCard('es9')];render();});await p.waitForFunction(()=>document.querySelector('#myHand img')?.classList.contains('face-ready'));await p.evaluate(()=>showPeek(document.querySelector('#myHand .card'),CARD_MAP.es9));assert.equal(await p.locator('#cardPeek img').getAttribute('src'),await p.locator('#myHand .card img').getAttribute('src'));await p.screenshot({path:out+`/es9-hand-peek-${w}.png`});await p.evaluate(()=>{document.getElementById('cardPeek').classList.remove('show');});}
const mechanics=await p.evaluate(()=>{startGame(false);state.busy=false;state.over=false;state.turn=1;const player=state.p1;player.board=[];applyFx(player,CARD_MAP.es9.spell,null);return player.board.map(m=>({id:m.id,atk:m.atk,def:m.def,hp:m.hp,maxHp:m.maxHp,cannotAttack:m.cannotAttack}));});assert.equal(mechanics.length,2);assert.ok(mechanics.every(m=>m.id==='e43'&&m.atk===4&&m.def===0&&m.hp===9&&m.maxHp===9&&m.cannotAttack));fs.writeFileSync(out+'/summons.json',JSON.stringify(mechanics,null,2));
const two=rows.filter(r=>r.lines.length===2);await p.setViewportSize({width:1600,height:780});for(let start=0;start<two.length;start+=16){await p.evaluate(async list=>{let el=document.getElementById('wrapQA');if(!el){el=document.createElement('div');el.id='wrapQA';el.style='position:fixed;inset:0;z-index:999999;background:#171018;display:grid;grid-template-columns:repeat(4,390px);align-content:start;gap:8px;padding:8px';document.body.append(el);}el.innerHTML='';for(const r of list){const card=document.createElement('div');card.style='background:#fff;color:#111;font:18px sans-serif';const label=document.createElement('div');label.textContent=r.id+' '+r.name;card.append(label);const c=document.createElement('canvas');c.width=768;c.height=300;c.style='width:390px;height:152px';const image=new Image();image.src=qaFaces[r.id];await image.decode();c.getContext('2d').drawImage(image,0,750,768,300,0,0,768,300);card.append(c);el.append(card);}},two.slice(start,start+16));await p.screenshot({path:out+`/two-line-sheet-${1+start/16}.png`});}
await p.evaluate(async()=>{document.getElementById('wrapQA').innerHTML='<img id="es9proof" style="height:750px" src="'+qaFaces.es9+'">';});await p.locator('#es9proof').screenshot({path:out+'/es9-face.png'});console.log(JSON.stringify({regular:300,total:rows.length,twoLines:two.length,corrected:Object.keys(expected).length,es9:rows.find(x=>x.id==='es9'),mechanics}));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
