const test=require('node:test');
const assert=require('node:assert/strict');
const {loadGame,setup,vm}=require('../test-support/harness');
function fixture(count=10){const g=loadGame(),{p1,p2}=setup(g);for(const p of [p1,p2]){p.hand=Array.from({length:count},()=>g.cloneCard('e1'));p.deck=['e1','e2','e3'];}return {g,p1,p2,state:vm.runInContext('state',g)};}
for(const who of ['p1','p2'])for(const size of [10,11])test(`${who} hand ${size}: one consumed card creates one burn presentation`,()=>{const f=fixture(size),p=f[who];f.g.draw(p);assert.equal(p.deck.length,2);assert.equal(p.hand.length,size);assert.equal(f.state._drawBurnQueue?.length,1);assert.equal(f.state._drawBurnQueue[0].id,'e3');assert.equal(f.state._drawBurnQueue[0].seat,who==='p1'?1:2);assert.equal(f.g.drawBurnPending(),true);});
test('9 + 3 draws: only the two overflow cards queue, in deck order',()=>{const f=fixture(9);f.g.draw(f.p1,3);assert.equal(f.p1.hand.length,10);assert.equal(f.p1._drewCount,1);assert.deepEqual(Array.from(f.state._drawBurnQueue||[],x=>x.id),['e2','e1']);});
test('fatigue and created cards do not fake deck draws',()=>{const f=fixture();f.p1.deck=[];f.g.draw(f.p1,2);assert.equal(f.p1.fatigue,2);assert.equal(f.p1.hp,27);f.g.addCardToHand(f.p1,'e1');assert.equal(f.state._drawBurnQueue?.length||0,0);});
test('sequential burn playback waits for each visual without calling unit death logic',async()=>{const f=fixture(),seen=[],release=[];f.g.playDrawBurnCard=(event)=>new Promise(r=>{seen.push(event.id);release.push(r);});f.g.resolveDeath=()=>assert.fail('must not resolve a unit death');f.g.draw(f.p1,2);const done=f.g.playDrawBurnSequence();await new Promise(setImmediate);assert.deepEqual(seen,['e3']);assert.equal(f.g.drawBurnPending(),true);release.shift()();await new Promise(setImmediate);assert.deepEqual(seen,['e3','e2']);release.shift()();await done;assert.equal(f.g.drawBurnPending(),false);assert.equal(f.p1.hand.length,10);});
test('new match abandons remaining burn events',async()=>{const f=fixture(),seen=[];let release;f.g.playDrawBurnCard=e=>new Promise(r=>{seen.push(e.id);release=r;});f.g.draw(f.p1,2);const done=f.g.playDrawBurnSequence();await new Promise(setImmediate);setup(f.g);release();await done;assert.deepEqual(seen,['e3']);assert.equal(f.g.drawBurnPending(),false);});
test('normal draw animation finishes before first overflow',async()=>{const f=fixture();f.p1._drawingAnim=true;const seen=[];f.g.playDrawBurnCard=async e=>seen.push(e.id);f.g.draw(f.p1);const done=f.g.playDrawBurnSequence();await new Promise(setImmediate);assert.equal(seen.length,0);f.p1._drawingAnim=false;await done;assert.deepEqual(seen,['e3']);});
test('public burn event carries only its card identity, stable seat and monotonic order',()=>{const f=fixture();f.g.draw(f.p2);f.g.draw(f.p1);const events=JSON.parse(JSON.stringify(f.state._drawBurnQueue));assert.deepEqual(events,[{seat:2,id:'e3',name:f.g.CARD_MAP?.e3?.name||vm.runInContext('CARD_MAP.e3.name',f.g),sequence:1,source:'deck'},{seat:1,id:'e3',name:vm.runInContext('CARD_MAP.e3.name',f.g),sequence:2,source:'deck'}]);});
test('opponent ordinary hand bookkeeping cannot block a public burn',async()=>{const f=fixture();f.p2._drewCount=2;f.g.playDrawBurnCard=async()=>{};f.g.draw(f.p2);await f.g.playDrawBurnSequence();assert.equal(f.g.drawBurnPending(),false);});
test('repeated render pump cannot duplicate a running burn',async()=>{const f=fixture();let seen=0,release;f.g.playDrawBurnCard=()=>new Promise(r=>{seen++;release=r;});f.g.draw(f.p1);const first=f.g.playDrawBurnSequence();await new Promise(setImmediate);await f.g.playDrawBurnSequence();assert.equal(seen,1);release();await first;assert.equal(f.g.drawBurnPending(),false);});
test('multi-draw applies fatigue only after the last real deck burn',()=>{const f=fixture();f.p1.deck=['e1'];f.g.draw(f.p1,3);assert.equal(f.state._drawBurnQueue.length,1);assert.equal(f.p1.deck.length,0);assert.equal(f.p1.fatigue,2);assert.equal(f.p1.hp,27);assert.equal(f.p1.hand.length,10);});
