const test=require('node:test'),assert=require('node:assert/strict');
const {loadGame,setup,place,vm}=require('../test-support/harness');
function fixture(){const g=loadGame(),{p1,p2}=setup(g);let timers=[],now=0;g.setTimeout=(fn)=>{timers.push(fn);return fn};g.clearTimeout=fn=>{timers=timers.filter(x=>x!==fn)};g.Date={now:()=>now};return {g,p1,p2,async tick(ms=50){now+=ms;const batch=timers;timers=[];batch.forEach(fn=>fn());for(let i=0;i<12;i++)await Promise.resolve()},pending:()=>g.__s.endTurnRequest};}
test('busy click is acknowledged immediately then resolves spell before exactly one turn end',async()=>{const f=fixture(),{g,p1,p2}=f;let release;g.SpellFx={play:()=>new Promise(r=>release=r)};const cast=g.runSpellCast(p1,{id:'test',spell:{type:'aoe_enemy',value:3}},null);const d=place(g,p2,'e1');d.hp=20;g.endTurn();g.endTurn();assert.ok(f.pending(),'busy click must create a queued request');assert.equal(g.__s.turn,1);release();await cast;await f.tick();assert.equal(d.hp,17);assert.equal(g.__s.turn,2);await f.tick();assert.equal(g.__s.turn,2);});
test('waits for all draw, overlay, combat and engine activity',async()=>{const f=fixture(),{g,p1}=f;let overlay=true,combat=1;g.SpellFx={overlayBusy:()=>overlay};g.CombatFx={pending:()=>combat,generation:()=>0};g.__s.busy=true;p1._drawingAnim=true;g.endTurn();assert.ok(f.pending());g.__s.busy=false;await f.tick();assert.equal(g.__s.turn,1);overlay=false;await f.tick();assert.equal(g.__s.turn,1);combat=0;await f.tick();assert.equal(g.__s.turn,1);p1._drawingAnim=false;await f.tick();assert.equal(g.__s.turn,2);});
for(const mode of ['restart','opponent','over','cancel'])test('queued request is invalidated by '+mode,async()=>{const f=fixture(),{g}=f;let generation=0;g.CombatFx={generation:()=>generation,pending:()=>0};g.__s.busy=true;g.endTurn();assert.ok(f.pending());if(mode==='restart')setup(g);if(mode==='opponent')g.__s.turn=2;if(mode==='over')g.__s.over=true;if(mode==='cancel')generation++;g.__s.busy=false;await f.tick();assert.equal(g.__s.turn,mode==='opponent'?2:1);assert.ok(!f.pending());});
test('stuck action cancels only the request, never unlocks engine or passes turn',async()=>{const f=fixture(),{g}=f;g.__s.busy=true;g.endTurn();assert.ok(f.pending());await f.tick(31000);assert.equal(g.__s.turn,1);assert.equal(g.__s.busy,true);assert.ok(!f.pending());assert.equal(g.__s.endTurnError,true);});
test('opponent and game over reject requests',()=>{for(const mode of ['opponent','over']){const f=fixture();if(mode==='opponent')f.g.__s.turn=2;else f.g.__s.over=true;f.g.endTurn();assert.ok(!f.pending());}});
test('accepted request prevents new card plays and soul draws while waiting',()=>{const f=fixture(),{g,p1}=f;const c=g.cloneCard('e1');p1.hand.push(c);g.__s.busy=true;g.endTurn();g.__s.busy=false;g.onHandClick(c);assert.equal(p1.hand.length,1);assert.equal(p1.board.length,0);assert.equal(g.canDropCard(c),false);assert.equal(g.canSoulDraw(p1),false);assert.equal(g.canReorderBoard(),false);});
test('opponent hidden hand notifications are not active animations',async()=>{const f=fixture();f.p2._drewCount=1;f.g.endTurn();await f.tick();assert.equal(f.g.__s.turn,2);});
test('a draw queued behind another animation is started before ending the turn',async()=>{const f=fixture(),{g,p1}=f;p1._drawingAnim=true;p1._drewCount=1;let starts=0;g.render=()=>{if(!p1._drawingAnim&&p1._drewCount){starts++;p1._drewCount=0;p1._drawingAnim=true}};g.endTurn();await f.tick();p1._drawingAnim=false;await f.tick();assert.equal(starts,1);assert.equal(g.__s.turn,1);p1._drawingAnim=false;await f.tick();assert.equal(g.__s.turn,2);});
