// Real browser UI/motion checks. Server data and match lifecycle are explicit
// fixtures; this suite does not claim that a production matchmaking API exists.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname,'..');
const out = path.resolve(process.env.LOBBY_QA_DIR || '../lobby-qa');
const mime = {'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.svg':'image/svg+xml','.mp3':'audio/mpeg','.mp4':'video/mp4','.json':'application/json'};
(async () => {
  fs.mkdirSync(out,{recursive:true});
  const browser = await chromium.launch({executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
  const context = await browser.newContext({viewport:{width:1672,height:941},hasTouch:true,recordVideo:{dir:path.join(out,'video'),size:{width:1280,height:720}}});
  await context.route('**/*', async route => {
    const u = new URL(route.request().url());
    if (u.hostname !== 'sanctuary.test') return route.abort();
    const file=path.resolve(root,'.'+decodeURIComponent(u.pathname === '/' ? '/index.html' : u.pathname));
    if (!file.startsWith(root+path.sep) || !fs.existsSync(file)) return route.fulfill({status:404,body:''});
    return route.fulfill({contentType:mime[path.extname(file)]||'application/octet-stream',body:fs.readFileSync(file)});
  });
  const page = await context.newPage(), errors=[];
  page.on('pageerror', e=>errors.push(e.message));
  await page.goto('https://sanctuary.test');
  await page.waitForFunction(()=>!!window.Lobby);
  const roomSource=process.env.ROOM_SESSION_SOURCE;
  if (!roomSource) throw new Error('Set ROOM_SESSION_SOURCE to the verified account-branch js/room-session.js');
  await page.addScriptTag({content:fs.readFileSync(roomSource,'utf8')});
  await page.evaluate(async () => {
    // Server fixture preserves real deck IDs/names and supplies rank data.
    const decks = TRIBES.map((t,i)=>({id:i+1,name:(i===0?'대지':t.name)+' 덱',tribe:t.id,cards:CARDS.filter(c=>c.tribe===t.id && c.type==='minion').slice(0,30).map(c=>c.id)}));
    const account = {id:17,displayName:'PLAYER',rank:{tier:'diamond',div:2,progress:35,next:{tier:'diamond',div:1}}};
    window.__qaAccount=account;
    FSNet.state.probed=true; FSNet.isLoggedIn=()=>true; FSNet.isOnline=()=>true; FSNet.account=()=>account; FSNet.listDecks=async()=>({ok:true,decks});
    FSNet.createRoom=async()=>{window.__qaRoom={code:'QA000001',status:'waiting',matchId:null};return {ok:true,room:window.__qaRoom};};
    FSNet.getRoom=async()=>window.__qaRoomError || {ok:true,room:window.__qaRoom};
    FSNet.cancelRoom=async()=>{if(window.__qaCancelError)return window.__qaCancelError;if(window.__qaHoldCancel)await new Promise(resolve=>{window.__qaCancelRelease=resolve;});window.__qaRoom.status='cancelled';return {ok:true,room:window.__qaRoom};};
    Lobby.open();await Lobby.refresh();window.__qaUnboundDisabled=document.getElementById('btnMatch').disabled;
    Lobby.bindRoomSession(FSRules.createRoomSession({net:FSNet,...Lobby.createRoomCallbacks({onMatch:id=>{window.__qaStarted=id;}})}));
    Lobby.open(); await Lobby.refresh();
  });
  await page.waitForTimeout(700);
  assert.equal(await page.evaluate(()=>window.__qaUnboundDisabled),true,'main without a room implementation cannot start a fake match');
  await page.screenshot({path:path.join(out,'lobby-desktop.png')});
  const comparisonBg=path.resolve(root,'../../references/parent-background.png');
  const comparisonSeal=path.resolve(root,'../../references/parent-seal.png');
  if (fs.existsSync(comparisonBg) && fs.existsSync(comparisonSeal)) {
    await page.evaluate(({bg,seal})=>{
      const style=document.createElement('style');style.id='qa-asset-comparison';
      style.textContent=`#lobby.screen.active{background-image:url('${bg}')}#lobby .seal-rotor{background:none}#lobby .seal-rotor::before{content:'';position:absolute;inset:0;background:url('${seal}') center/contain no-repeat;transform:rotate(-30deg)}`;
      document.head.append(style);
      document.querySelectorAll('.seal-element').forEach(el=>{el.style.setProperty('--ex',parseFloat(el.style.getPropertyValue('--ex'))*.862+'cqh');el.style.setProperty('--ey',parseFloat(el.style.getPropertyValue('--ey'))*.862+'cqh');});
    },{bg:'data:image/png;base64,'+fs.readFileSync(comparisonBg).toString('base64'),seal:'data:image/png;base64,'+fs.readFileSync(comparisonSeal).toString('base64')});
    await page.waitForTimeout(250);await page.screenshot({path:path.join(out,'parent-assets-comparison.png')});
    await page.evaluate(()=>{document.getElementById('qa-asset-comparison').remove();document.querySelectorAll('.seal-element').forEach(el=>{el.style.setProperty('--ex',parseFloat(el.style.getPropertyValue('--ex'))/.862+'cqh');el.style.setProperty('--ey',parseFloat(el.style.getPropertyValue('--ey'))/.862+'cqh');});});
  }
  assert.equal(await page.locator('.seal-element').count(),6);
  assert.equal(await page.locator('.lobby-deck[data-id]').count(),6);
  assert.deepEqual(await page.locator('.seal-element img').evaluateAll(els=>els.map(x=>x.getAttribute('src'))),['earth','fire','wind','water','dark','light'].map(x=>'assets/img/icons/'+x+'.png'));
  await page.locator('#lobbyUser .rank-trigger').hover();
  await page.locator('#lobbyRankPopover').waitFor({state:'visible'});
  await page.locator('#lobbyRankPopover').hover(); await page.waitForTimeout(250);
  assert.equal(await page.locator('#lobbyRankPopover').isVisible(),true,'popover survives pointer travel');
  await page.screenshot({path:path.join(out,'rank-popover.png')});
  await page.keyboard.press('Escape'); assert.equal(await page.locator('#lobbyRankPopover').isVisible(),false);
  await page.locator('#lobbyUser .rank-trigger').focus();
  assert.equal(await page.locator('#lobbyRankPopover').isVisible(),true,'keyboard focus opens rank');
  await page.keyboard.press('Escape');
  const center = await page.locator('.lobby-sel-icon').boundingBox();
  const button = await page.locator('#btnMatch').boundingBox();
  await page.click('#btnMatch');
  assert.equal(await page.locator('#btnMatch').isDisabled(),true);
  const transforms=[];
  for (const ms of [100,400,800,600]) {await page.waitForTimeout(ms);transforms.push(await page.locator('#lobbySealRotor').evaluate(e=>e.style.transform));}
  assert.equal(new Set(transforms).size,4,'rotor advances throughout acceleration');
  assert.deepEqual(await page.locator('.lobby-sel-icon').boundingBox(),center,'central icon stays fixed');
  assert.deepEqual(await page.locator('#btnMatch').boundingBox(),button,'button stays fixed');
  await page.screenshot({path:path.join(out,'matching.png')});
  await page.evaluate(()=>{window.__qaRoom.matchId='server-confirmed-qa-match';});
  await page.waitForFunction(()=>window.__qaStarted==='server-confirmed-qa-match');
  await page.waitForTimeout(650);
  const stopped=await page.locator('#lobbySealRotor').evaluate(e=>e.style.transform);
  await page.waitForTimeout(350);
  assert.equal(await page.locator('#lobbySealRotor').evaluate(e=>e.style.transform),stopped,'success stops with no jump');
  await page.evaluate(async()=>{Lobby.open();await Lobby.refresh();});
  await page.click('#btnMatch'); await page.waitForTimeout(350);
  await page.evaluate(()=>{window.__qaHoldCancel=true;});await page.click('#btnMatchCancel');
  assert.equal(await page.evaluate(()=>Lobby._state.matchState),'cancelling');
  assert.equal(await page.locator('#btnMatch').isDisabled(),true,'cancel stays pending until server acknowledgement');
  assert.equal(await page.locator('#btnLobbyEdit').isDisabled(),true);
  await page.evaluate(()=>{window.__qaHoldCancel=false;window.__qaCancelRelease();});
  await page.waitForFunction(()=>Lobby._state.matchState==='idle');
  await page.waitForTimeout(500); assert.equal(await page.locator('#lobbyWait').isVisible(),false);
  await page.click('#btnMatch');await page.evaluate(()=>{window.__qaCancelError={ok:false,error:'network'};});
  await page.click('#btnMatchCancel');await page.waitForFunction(()=>Lobby._state.matchState==='disconnected');
  assert.equal(await page.locator('#btnLobbyEdit').isDisabled(),true,'unconfirmed cancellation stays locked through disconnect');
  await page.evaluate(()=>Lobby.refresh());
  assert.equal(await page.locator('#btnLobbyDelete').isDisabled(),true,'deck-fetch reconnect is not room cancellation acknowledgement');
  await page.evaluate(()=>{window.__qaCancelError=null;});await page.waitForFunction(()=>Lobby._state.matchState==='idle');
  await page.click('#btnMatch');await page.evaluate(()=>{window.__qaCancelError={ok:false,error:'network'};});
  await page.click('#btnMatchCancel');await page.waitForFunction(()=>Lobby._state.matchState==='disconnected');
  await page.evaluate(()=>{window.__qaCancelError=null;});await page.waitForFunction(()=>Lobby._state.matchState==='idle');
  assert.equal(await page.locator('#btnMatch').isDisabled(),false,'server cancellation acknowledgement restores connection without manual refresh');
  await page.click('#btnMatch'); await page.evaluate(()=>{window.__qaRoomError={ok:false,error:'network'};});
  await page.waitForFunction(()=>Lobby._state.matchState==='disconnected');await page.evaluate(()=>Lobby.refresh());
  assert.equal(await page.locator('#btnLobbyEdit').isDisabled(),true,'pending room retains selected deck through independent deck-fetch reconnect');
  assert.equal(await page.locator('#btnMatch').isDisabled(),true);
  await page.evaluate(()=>{window.__qaRoomError=null;});await page.waitForFunction(()=>Lobby._state.matchState==='searching');
  await page.click('#btnMatchCancel');await page.waitForFunction(()=>Lobby._state.matchState==='idle');
  await page.click('#btnMatch'); await page.evaluate(()=>{window.__qaRoomError={ok:false,status:400,error:'deck_invalid'};});
  await page.waitForFunction(()=>Lobby._state.matchState==='error');
  await page.evaluate(()=>{window.__qaRoomError=null;});
  assert.equal(await page.locator('#lobbyWait').isVisible(),false);
  await page.evaluate(()=>window.dispatchEvent(new Event('offline')));
  assert.equal(await page.locator('#lobbyWait').isVisible(),false);
  assert.equal(await page.locator('#btnMatch').isDisabled(),true,'disconnect blocks another match until verified reconnect');
  await page.evaluate(()=>document.getElementById('btnMatch').click());
  assert.equal(await page.locator('#lobbyWait').isVisible(),false);
  await page.evaluate(()=>Lobby.refresh());
  await page.evaluate(()=>window.dispatchEvent(new Event('offline')));
  assert.equal(await page.locator('#btnMatch').isDisabled(),true,'a second disconnect also refreshes the disabled UI');
  await page.evaluate(()=>Lobby.refresh());
  await page.evaluate(()=>Lobby.setMatchState('idle'));
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.click('#btnMatch'); const reduced=await page.locator('#lobbySealRotor').evaluate(e=>e.style.transform);
  await page.waitForTimeout(250);assert.equal(await page.locator('#lobbySealRotor').evaluate(e=>e.style.transform),reduced);
  await page.click('#btnMatchCancel'); await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:1920,height:1080});await page.waitForTimeout(250);
  await page.screenshot({path:path.join(out,'lobby-1920.png')});
  await page.setViewportSize({width:3840,height:2160});
  // Test actual 4K layout independently of the game's existing max resolution preset.
  await page.evaluate(()=>{const a=document.getElementById('app');a.style.width='3840px';a.style.height='2160px';});
  await page.waitForTimeout(300); await page.screenshot({path:path.join(out,'lobby-4k.png')});
  await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(300);
  await page.screenshot({path:path.join(out,'lobby-mobile.png'),fullPage:true});
  await page.locator('#lobbyUser .rank-trigger').tap();
  assert.equal(await page.locator('#lobbyRankPopover').isVisible(),true);
  const pop=await page.locator('#lobbyRankPopover').boundingBox(); assert.ok(pop.x>=0 && pop.x+pop.width<=390,'mobile popup stays in viewport');
  await page.locator('.lobby-head h2').tap(); assert.equal(await page.locator('#lobbyRankPopover').isVisible(),false);
  await page.locator('#btnMatch').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(out,'lobby-mobile-actions.png')});
  await page.setViewportSize({width:844,height:390});await page.waitForTimeout(250);
  await page.screenshot({path:path.join(out,'lobby-mobile-landscape.png')});
  assert.ok((await page.locator('#btnLobbyBack').boundingBox()).height>=44,'small landscape touch target');
  await page.click('#btnLobbyBack');
  assert.equal(await page.locator('#title').evaluate(e=>e.classList.contains('active')),true);
  // Real localStorage CRUD, with more decks than the visible two-column grid.
  await page.setViewportSize({width:1672,height:941});
  await page.evaluate(async () => {
    FSNet.isLoggedIn=()=>false; FSNet.isOnline=()=>false; FSNet.account=()=>null;
    persistLocalDecks(Array.from({length:9},(_,i)=>({id:'local-qa-'+i,name:'보존 덱 '+i,tribe:TRIBES[i%6].id,cards:buildDeck(TRIBES[i%6].id).map(c=>typeof c==='string'?c:c.id)})));
    Lobby.open();await Lobby.refresh();
  });
  assert.equal(await page.locator('.lobby-deck[data-id]').count(),9);
  assert.equal(await page.locator('#btnMatch').isDisabled(),true,'offline matching disabled');
  assert.equal(await page.locator('#lobbyUser .rank-trigger').count(),0,'no fabricated rank for offline profile');
  const ninth=page.locator('.lobby-deck[data-id="local:local-qa-8"]');
  await ninth.scrollIntoViewIfNeeded();
  await ninth.evaluate(el=>el.addEventListener('click',()=>{window.__scrollBeforeClick=document.getElementById('lobbyDecks').scrollTop;},{capture:true,once:true}));
  await ninth.click();
  const scrollBefore=await page.evaluate(()=>window.__scrollBeforeClick);
  assert.ok(scrollBefore>0);
  assert.equal(await page.locator('#lobbyDecks').evaluate(e=>e.scrollTop),scrollBefore,'selection preserves scroll');
  await page.click('#btnLobbyRename');await page.fill('#fsPromptInput','변경된 덱');await page.click('#fsPromptOk');
  await page.waitForFunction(()=>loadLocalDecks().find(d=>d.id==='local-qa-8').name==='변경된 덱');
  await page.click('#btnLobbyEdit');await page.waitForSelector('#deckBuilder.active');
  assert.equal(await page.evaluate(()=>Lobby._state.edit.lid),'local-qa-8');
  await page.click('#btnBackMenu');await page.waitForSelector('#lobby.active');
  await page.click('#btnLobbyDelete');await page.click('#fsPromptOk');
  await page.waitForFunction(()=>loadLocalDecks().length===8);
  await page.locator('#lobbyAddDeck').click();await page.waitForSelector('#tribeSelect.active');
  await page.locator('.tsel-card[data-id="water"]').click();await page.waitForSelector('#deckBuilder.active');
  page.on('dialog',dialog=>dialog.accept());
  await page.evaluate(()=>{ window.__qaSave=Lobby.saveDraftLocal(buildDeck('water').map(c=>typeof c==='string'?c:c.id),'water',false); });
  await page.fill('#fsPromptInput','새 물 덱');await page.click('#fsPromptOk');
  await page.waitForFunction(()=>loadLocalDecks().some(d=>d.name==='새 물 덱'));
  await page.click('#btnBackMenu');await page.waitForSelector('#lobby.active');
  assert.equal(await page.locator('.lobby-deck[data-id]').count(),9);
  assert.equal(await page.evaluate(()=>loadLocalDecks().filter(d=>d.id.startsWith('local-qa-')).length),8,'unrelated user decks retained');
  await page.screenshot({path:path.join(out,'local-decks-crud.png')});
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({errors,transforms,center,button,pop,checks:'PASS'},null,2));
  await context.close(); await browser.close();
  console.log('PASS: sanctuary browser, motion, rank, 4K and mobile checks. Evidence: '+out);
})().catch(e=>{console.error(e);process.exit(1);});
