const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.join(__dirname,'..'),src=fs.readFileSync(path.join(root,'js/spell-fx.js'),'utf8');
function extract(ctx,name){const a=src.indexOf('function '+name+'(');assert.ok(a>=0);const b=src.indexOf('\n  }',a)+4;vm.runInContext((src.slice(a-6,a)==='async '?'async ':'')+src.slice(a,b),ctx);}
test('cleared card-out wait cannot hide the next showcase',async()=>{const timers=[],noop=()=>{},el=()=>({style:{opacity:''},dataset:{},classList:{add:noop,remove:noop},querySelector:()=>null});const stage=el(),face=el(),layer=el();const ctx={_legendaryEpoch:0,_hidden:{},Object,Promise,setTimeout:(f,ms)=>{timers.push({f,ms});return 1},document:{getElementById:id=>id==='fxCard'?face:stage},ensureLayer:()=>layer,spellKind:()=>'',elemOf:()=>'',lowSpec:()=>false,loadSpellMeta:async()=>({ownedTimeline:true}),isCanvasMeta:()=>true,isVideoSpellMeta:()=>true,preloadMetaFx:noop,ASSET_BASE:'',resolveFace:async()=>'',paintCard:noop,playAssetPack:async()=>true,cleanupFx:noop};vm.createContext(ctx);extract(ctx,'play');const p=ctx.play({id:'es2'},{});for(let i=0;i<30&&!timers.some(t=>t.ms===650);i++)await Promise.resolve();timers.find(t=>t.ms===650).f();for(let i=0;i<30&&!timers.some(t=>t.ms===220);i++)await Promise.resolve();ctx._legendaryEpoch=1;face.style.opacity='new';timers.find(t=>t.ms===220).f();await p;assert.equal(face.style.opacity,'new');});
test('cancelled asset playback cannot reset a newer card opacity',async()=>{let finish;const noop=()=>{},face={style:{opacity:''},classList:{add:noop}},label={style:{}};const ctx={waitSpellMeta:p=>p,_legendaryEpoch:0,loadSpellMeta:async()=>({id:'es2',ownedTimeline:true}),isCanvasMeta:()=>true,isVideoSpellMeta:()=>true,document:{getElementById:id=>id==='fxCard'?face:label},isSummonMeta:()=>false,isProjectileMeta:()=>false,playMetaFx:()=>new Promise(r=>finish=r),ASSET_BASE:'',Object,Promise};vm.createContext(ctx);extract(ctx,'playAssetPack');const p=ctx.playAssetPack({id:'es2'},{classList:{add:noop}},{},{fxEpoch:0});for(let i=0;i<5;i++)await Promise.resolve();ctx._legendaryEpoch=1;face.style.opacity='new';finish(true);await p;assert.equal(face.style.opacity,'new');});
test('never-settling selected media load settles immediately on clear cancellation',async()=>{const ctx={_legendaryPreloads:new Set(),setTimeout,clearTimeout,Promise};vm.createContext(ctx);extract(ctx,'waitSpellMeta');const p=ctx.waitSpellMeta(new Promise(()=>{}));assert.equal(ctx._legendaryPreloads.size,1);[...ctx._legendaryPreloads][0]();assert.equal(await p,null);assert.equal(ctx._legendaryPreloads.size,0);});
test('unit-target pack finds exactly the selected UID or no point, never an entire board',()=>{const ctx={document:{querySelector:sel=>sel==='.minion[data-uid="picked"]'?{getBoundingClientRect:()=>({left:10,top:20,width:215,height:323})}:null}};vm.createContext(ctx);extract(ctx,'targetUnitPoints');assert.equal(ctx.targetUnitPoints(null).length,0);assert.equal(ctx.targetUnitPoints({minion:{uid:'missing'}}).length,0);assert.deepEqual(JSON.parse(JSON.stringify(ctx.targetUnitPoints({minion:{uid:'picked'}}))),[{uid:'picked',x:117.5,y:181.5,width:215,height:323}]);});
test('failed selected preload returns to bounded outer fallback without legacy probes',async()=>{let probes=0;const noop=()=>{},el={style:{},classList:{add:noop}},ctx={waitSpellMeta:p=>p,_legendaryEpoch:0,loadSpellMeta:async()=>({id:'es2',ownedTimeline:true}),isCanvasMeta:()=>true,isVideoSpellMeta:()=>true,document:{getElementById:()=>el},isSummonMeta:()=>false,isProjectileMeta:()=>false,playMetaFx:async()=>false,ASSET_BASE:'',Object,Promise,assetUrl:(a,b)=>a+b,Sfx:{},resolveFxAnchor:()=>({}),probeUrl:async()=>{probes++;return false;},cssFallback:noop,elemOf:()=>'',spellKind:()=>'',setTimeout:f=>f()};vm.createContext(ctx);extract(ctx,'playAssetPack');assert.equal(await ctx.playAssetPack({id:'es2'},{classList:{add:noop}},{},{fxEpoch:0}),false);assert.equal(probes,0);});
test('selected HQ manifests reassemble the approved1440 videos without resizing or loss',()=>{for(const id of ['es1','es2']){const p=path.join(root,'assets/vfx/spells',id),m=JSON.parse(fs.readFileSync(path.join(p,'meta.json'))),V=m.video;assert.equal(m.playMode,'perUnitVideo');assert.equal(V.width,1440);assert.equal(V.height,1440);assert.equal(V.fps,30);assert.equal(V.visualFrames,36);assert.equal(m.visualDurationMs,1200);const data=Buffer.concat(V.parts.map(part=>{const b=fs.readFileSync(path.join(p,part.file));assert.equal(b.length,part.bytes);return b;}));assert.equal(data.length,V.bytes);assert.equal(crypto.createHash('sha256').update(data).digest('hex'),V.sha256);}});
