// Serve fantasy_arena/ at http://127.0.0.1:8765 before running this optional browser suite.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
(async () => {
  fs.mkdirSync('screenshots', {recursive:true});
  const browser = await chromium.launch({...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {channel:'chrome'}),headless:true});
  const page = await browser.newPage({viewport:{width:1600,height:900}});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765'); await page.waitForTimeout(700);
  assert.deepEqual(await page.locator('#titleMenu button').allTextContents(), ['온라인 로비','상점','설정','게임 종료']);
  await page.screenshot({path:'screenshots/title-desktop.png'});
  const button = page.locator('#btnLobby');
  const normal = await button.evaluate(el=>getComputedStyle(el,'::before').backgroundImage);
  await button.hover(); await page.waitForTimeout(200);
  assert.notEqual(await button.evaluate(el=>getComputedStyle(el,'::before').backgroundImage),normal);
  await page.screenshot({path:'screenshots/title-hover.png'});
  await page.mouse.move(0,0); await page.keyboard.press('Tab');
  await button.focus(); await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'btnShop');
  assert.equal(await page.locator('#btnShop').evaluate(el=>el.matches(':focus-visible')),true);
  await page.screenshot({path:'screenshots/title-keyboard.png'});
  await page.keyboard.press('Enter'); await page.waitForSelector('#shop.active');
  await page.click('#btnShopBack'); await page.waitForSelector('#title.active');
  await page.click('#btnSettings'); await page.waitForSelector('#settingsPop.show');
  await page.click('#btnSettingsClose'); assert.equal(await page.locator('#settingsPop').evaluate(el=>el.classList.contains('show')),false);
  await page.locator('#btnSettings').focus(); await page.keyboard.press('Enter');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'btnSettingsClose');
  await page.keyboard.press('Tab'); assert.equal(await page.evaluate(()=>document.activeElement.id),'btnSettingsHelp');
  await page.keyboard.press('Shift+Tab'); assert.equal(await page.evaluate(()=>document.activeElement.id),'btnSettingsClose');
  for (let i=0; i<16 && await page.evaluate(()=>document.activeElement.id) !== 'btnSettingsClose'; i++) await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'btnSettingsClose');
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#settingsPop').evaluate(el=>el.classList.contains('show')),false);
  assert.equal(await page.evaluate(()=>document.activeElement.id),'btnSettings');
  await page.keyboard.press('Enter'); await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'btnSettings');
  await page.keyboard.press('Enter'); await page.keyboard.press('Tab'); await page.keyboard.press('Enter');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'btnHelpClose');
  await page.keyboard.press('Tab'); assert.equal(await page.evaluate(()=>document.activeElement.id),'btnHelpClose');
  await page.keyboard.press('Escape'); assert.equal(await page.evaluate(()=>document.activeElement.id),'btnSettingsHelp');
  await page.keyboard.press('Escape'); assert.equal(await page.evaluate(()=>document.activeElement.id),'btnSettings');
  await page.click('#btnLobby'); await page.waitForSelector('#lobby.active');
  await page.click('#btnLobbyBack'); await page.waitForSelector('#title.active');
  // Do not actually close the automation-owned page; emulate a blocked normal browser tab.
  await page.evaluate(()=>{window.close=()=>{};});
  await page.click('#btnTitleQuit'); await page.waitForTimeout(250);
  assert.equal(await page.locator('#exitNotice').textContent(),'브라우저 탭을 닫아 종료해주세요.');
  assert.equal(page.url(),'http://127.0.0.1:8765/');
  await page.screenshot({path:'screenshots/title-exit-guidance.png'});
  await page.evaluate(()=>document.getElementById('exitNotice').textContent='');
  for(const [width,height] of [[1280,720],[844,390],[640,360],[568,320],[360,640]]) {
    await page.setViewportSize({width,height}); await page.waitForTimeout(300);
    const boxes = await page.locator('#titleMenu button').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};}));
    for(let i=0;i<boxes.length;i++) {const b=boxes[i];assert.ok(b.w>=44&&b.h>=44);assert.ok(b.x>=0&&b.x+b.w<=width);if(i)assert.ok(b.y>=boxes[i-1].y+boxes[i-1].h);if(width>height)assert.ok(b.y>=0&&b.y+b.h<=height);}
    await page.locator('#btnTitleQuit').scrollIntoViewIfNeeded();
    await page.screenshot({path:`screenshots/title-${width}x${height}.png`});
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await button.evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
  const touch = await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true});
  const tp = await touch.newPage(); await tp.goto('http://127.0.0.1:8765');
  await tp.waitForTimeout(700);
  assert.ok((await tp.locator('.title-brand').boundingBox()).y >= 0, 'mobile logo stays inside visual viewport');
  const rect = await tp.locator('#btnShop').boundingBox();
  const cdp = await touch.newCDPSession(tp);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect.x+rect.width/2,y:rect.y+rect.height/2}]});
  await tp.waitForTimeout(150);
  assert.notEqual(await tp.locator('#btnShop').evaluate(el=>getComputedStyle(el).transform),'none');
  await tp.screenshot({path:'screenshots/title-touch-pressed.png'});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
  assert.equal(await tp.locator('#btnShop').evaluate(el=>el.classList.contains('is-pressed')),false);
  await tp.locator('#btnShop').tap(); await tp.waitForSelector('#shop.active');
  await tp.locator('#btnShopBack').tap(); await tp.waitForSelector('#title.active');
  await tp.locator('#btnSettings').tap(); await tp.locator('#btnSettingsClose').tap();
  await tp.screenshot({path:'screenshots/title-touch.png'});
  assert.deepEqual(errors,[]);
  console.log('PASS: menu, hover, keyboard, shop/settings/lobby return, blocked exit, five viewports, reduced motion, touch.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
