const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const src=fs.readFileSync(path.join(__dirname,'../js/legendary-video.js'),'utf8');
function extract(ctx,name){const a=src.indexOf('function '+name+'(');assert.ok(a>=0,name+' must exist');const b=src.indexOf('\n  }',a)+4;vm.runInContext((src.slice(a-6,a)==='async '?'async ':'')+src.slice(a,b),ctx);}
function fixture(){const objects=[],revoked=[];const ctx={url:(base,file)=>base+file,Uint8Array,Blob,Error,Promise,Number,Array,crypto:crypto.webcrypto,URL:{createObjectURL:b=>{objects.push(b);return 'blob:test';},revokeObjectURL:u=>revoked.push(u)},fetch:async(url,{signal})=>({ok:true,arrayBuffer:async()=>Buffer.from(url.endsWith('a')?'abc':'def')})};vm.createContext(ctx);extract(ctx,'videoSource');return{ctx,objects,revoked};}
const V={parts:[{file:'a',bytes:3},{file:'b',bytes:3}],bytes:6,sha256:crypto.createHash('sha256').update('abcdef').digest('hex')};
test('selected video parts reassemble byte-exact and verify SHA before creating URL',async()=>{const f=fixture(),v=await f.ctx.videoSource('pack/',V,new AbortController().signal);assert.equal(v.src,'blob:test');assert.equal(v.owned,true);assert.equal(await f.objects[0].text(),'abcdef');});
test('legacy single-file video remains a direct URL with no assembly',async()=>{const f=fixture(),v=await f.ctx.videoSource('pack/',{file:'old.webm'},new AbortController().signal);assert.equal(v.src,'pack/old.webm');assert.equal(v.owned,false);assert.equal(f.objects.length,0);});
test('wrong length, ordering, hash and failed request never create a playable URL',async()=>{for(const kind of ['length','order','hash','http']){const f=fixture(),v=JSON.parse(JSON.stringify(V));if(kind==='length')v.parts[0].bytes=4;if(kind==='order')v.parts.reverse();if(kind==='hash')v.sha256='0'.repeat(64);if(kind==='http')f.ctx.fetch=async()=>({ok:false});await assert.rejects(f.ctx.videoSource('pack/',v,new AbortController().signal));assert.equal(f.objects.length,0);}});
test('cancelled assembled video cannot create a stale object URL',async()=>{const f=fixture(),c=new AbortController();let finish;f.ctx.fetch=async()=>({ok:true,arrayBuffer:()=>new Promise(r=>finish=r)});const p=f.ctx.videoSource('pack/',{parts:[{file:'a',bytes:3}],bytes:3,sha256:crypto.createHash('sha256').update('abc').digest('hex')},c.signal);for(let i=0;i<20&&!finish;i++)await Promise.resolve();c.abort();finish(Buffer.from('abc'));await assert.rejects(p);assert.equal(f.objects.length,0);});
test('owned URL disposal is idempotent',()=>{const f=fixture();extract(f.ctx,'dispose');const v={_ownedObjectUrl:'blob:test',pause(){},removeAttribute(){},load(){},remove(){}};f.ctx.dispose(v);f.ctx.dispose(v);assert.deepEqual(f.revoked,['blob:test']);});
const spellSrc=fs.readFileSync(path.join(__dirname,'../js/spell-fx.js'),'utf8');
function spellExtract(ctx,name){const a=spellSrc.indexOf('function '+name+'(');assert.ok(a>=0,name+' must exist');const b=spellSrc.indexOf('\n  }',a)+4;vm.runInContext((spellSrc.slice(a-6,a)==='async '?'async ':'')+spellSrc.slice(a,b),ctx);}
test('spell video dispatch shares one decoder and exact selected-unit geometry',async()=>{let got;const ctx={_legendaryEpoch:0,Math,targetUnitPoints:()=>[{uid:'picked',x:100,y:200,width:215,height:323}],aoeUnitPoints:()=>{throw Error('wrong whole-board target')},LegendaryVideoFx:{play:async(base,m,o)=>{got=o;return true;}}};vm.createContext(ctx);spellExtract(ctx,'playVideoSpell');const meta={targetMode:'unit',video:{'displayPx@1080p':[1440,1440],cardWidthScale:2.1,cardHeightScale:1.55}};assert.equal(await ctx.playVideoSpell(meta,'pack/',{target:{minion:{uid:'picked'}},fxEpoch:0}),true);assert.equal(got.anchors.length,1);assert.equal(got.anchors[0].uid,'picked');assert.ok(Math.abs(got.anchors[0].scale-500.65/1440)<1e-12);});
test('empty enemy target set stays empty and stale spell never launches decoder',async()=>{let starts=0,got;const ctx={_legendaryEpoch:1,Math,targetUnitPoints:()=>[],aoeUnitPoints:()=>[],LegendaryVideoFx:{play:async(b,m,o)=>{starts++;got=o;return true;}}};vm.createContext(ctx);spellExtract(ctx,'playVideoSpell');const m={targetMode:'aoe_enemy',video:{'displayPx@1080p':[1440,1440],cardWidthScale:1.65}};assert.equal(await ctx.playVideoSpell(m,'',{fxEpoch:0}),true);assert.equal(starts,0);await ctx.playVideoSpell(m,'',{fxEpoch:1});assert.equal(starts,1);assert.equal(got.anchors.length,0);});
test('the real shared dispatcher reaches selected video spell playback',async()=>{let started=0;const ctx={Promise,isVideoSpellMeta:m=>m.playMode==='perUnitVideo',playVideoSpell:async()=>{started++;return true;},isAnchoredMeta:()=>false,isDuelKeepMeta:()=>false,isSummonMeta:()=>false,isProjectileMeta:()=>false,isFlowMeta:()=>false,isOverlayMeta:()=>false};vm.createContext(ctx);spellExtract(ctx,'playMetaFx');assert.equal(await ctx.playMetaFx({}, {playMode:'perUnitVideo'},'pack/',{}),true);assert.equal(started,1);});
test('failed warmup aborts outstanding part fetches before dropping its job',async()=>{let signal;const ctx={AbortController,Map,Set,epoch:0,warmed:new Map(),jobs:new Set(),url:(b,f)=>b+f,ready:async(b,m,s)=>{signal=s;return null;},dispose(){}};vm.createContext(ctx);extract(ctx,'preload');assert.equal(await ctx.preload('pack/',{video:{sha256:'hash'}}),false);assert.equal(signal.aborted,true);assert.equal(ctx.jobs.size,0);});
