const test=require('node:test'),assert=require('node:assert/strict');
const {loadGame,setup,place,vm}=require('../test-support/harness');
function fixture(id='l12'){const g=loadGame(),{p1,p2}=setup(g),m=place(g,p1,id);return {g,p1,p2,m};}
function copy(f){f.g.applyFx(f.p1,{type:'copy_own'},{kind:'minion',owner:f.p1,minion:f.m});return f.p1.board[f.p1.board.indexOf(f.m)+1];}
function objects(value,set=new Set()){if(value&&typeof value==='object'&&!set.has(value)){set.add(value);Object.values(value).forEach(v=>objects(v,set));}return set;}
const items=vm.runInContext('CARDS.filter(c=>c.type==="item").map(c=>c.id)',loadGame());
for(const id of items)test(`mirror ${id}: equipment, effects and bonuses survive independently`,()=>{const f=fixture();f.g.equipItemOnUnit(f.p1,f.g.cloneCard(id),f.m);const c=copy(f);for(const key of ['atk','def','hp','maxHp','atkC','defC','hpC','ability','atkSkill','keywords','_itemFx','coinLuckBonus','_onKillDraw','itemWorn','_itemBonuses','text','_baseText'])assert.equal(JSON.stringify(c[key]),JSON.stringify(f.m[key]),key);assert.equal(c.equippedItem.id,id);assert.notEqual(c.equippedItem.uid,f.m.equippedItem.uid);assert.notEqual(c.uid,f.m.uid);const refs=objects(f.m);for(const obj of objects(c))assert.ok(!refs.has(obj),'no shared object');assert.equal(f.g.equipItemOnUnit(f.p1,f.g.cloneCard('fi1'),c),false);const original=JSON.stringify(f.m);f.g.unequipItem(c);assert.equal(JSON.stringify(f.m),original);assert.equal(f.g.equipItemOnUnit(f.p1,f.g.cloneCard('fi1'),c),true);});
test('mirror copies stacked buffs, acquired attack skill, death effects and coin state',()=>{const f=fixture(),t={kind:'minion',owner:f.p1,minion:f.m};f.g.applyFx(f.p1,{type:'buff',atk:3,def:3,hp:3,kws:['shield'],ability:'보호',addDeathrattle:{type:'draw',value:1},deathText:'파괴: 카드 1장 뽑기'},t);f.g.applyFx(f.p1,{type:'buff',addDeathrattle:{type:'draw',value:2}},t);f.g.applyFx(f.p1,{type:'buff_all',atkSkill:3},null);f.g.applyFx(f.p1,{type:'own_black_buff',atk:2,hp:2},t);f.m.atkC=-2;f.m.coinGold=false;f.m.coinBlack=true;const c=copy(f);for(const key of ['atk','def','hp','maxHp','atkSkill','ability','keywords','deathrattles','coinGold','coinBlack','text'])assert.equal(JSON.stringify(c[key]),JSON.stringify(f.m[key]),key);c.deathrattles[0].value=99;assert.equal(f.m.deathrattles[0].value,1);});
test('mirror clones base nested effects independently of original and card definition',()=>{const f=fixture('e29'),c=copy(f),base=vm.runInContext('CARD_MAP.e29',f.g);c.battlecry.count=99;assert.equal(f.m.battlecry.count,2);assert.equal(base.battlecry.count,2);});
test('mirror keeps existing damage, action and silence policy',()=>{const f=fixture('d27');f.g.silenceMinion(f.m,f.p1);Object.assign(f.m,{hp:1,maxHp:20,damaged:true,canAttack:false,attacksLeft:0,skipAttack:true,_sickTurn:1,_frozenTurn:1,_atkTurn:1});const c=copy(f);assert.equal(c.hp,1);assert.equal(c.maxHp,20);assert.equal(c.damaged,false);assert.equal(c.canAttack,true);assert.equal(c.attacksLeft,1);for(const k of ['silenced','skipAttack','_sickTurn','_frozenTurn','_atkTurn'])assert.equal(c[k],undefined,k);assert.equal(c.atkSkill,5);assert.equal(c.ability,null);assert.deepEqual([...c.keywords],[]);assert.equal(c.text,f.g.cloneCard('d27').text);});
test('mirror copied attack, kill, end-turn, death and coin equipment actually trigger',()=>{
 for(const id of ['fi7','ei7','li7','ai7','fi5']){const f=fixture();f.g.equipItemOnUnit(f.p1,f.g.cloneCard(id),f.m);const c=copy(f);if(id==='fi7'){f.g.applyItemAttackFx(f.p1,c);assert.equal(f.p1.hand[0].id,'fs3');}if(id==='ei7'){f.g.applyItemKillFx(f.p1,c,f.p2);assert.equal(f.p1.hand[0].tribe,'earth');}if(id==='li7'){f.g.unequipItem(f.m);f.g.applyItemEndTurnFx(f.p1);assert.equal(f.p1.hand.length,1);}if(id==='ai7'){f.g.destroyMinion(f.p1,c,{fromSpell:true});assert.equal(f.p1.hand.length,3);assert.ok(f.p1.board.includes(f.m));}if(id==='fi5'){c.atkC=3;f.g.Math=Object.create(Math);f.g.Math.random=()=>.4;assert.equal(f.g.rollSharedCoins(c).heads,0);}}
});
test('mirror normal cast consumes four soul and preserves equipped copy; full board adds nothing',async()=>{const f=fixture();f.g.equipItemOnUnit(f.p1,f.g.cloneCard('fi7'),f.m);const spell=f.g.cloneCard('as2');f.p1.hand=[spell];f.g.playCard(f.p1,spell,{kind:'minion',owner:f.p1,minion:f.m});for(let i=0;i<10;i++)await new Promise(setImmediate);assert.equal(f.p1.soul,6);assert.equal(f.p1.hand.length,0);assert.equal(f.p1.board[1].equippedItem.id,'fi7');while(f.p1.board.length<5)place(f.g,f.p1,'l12');copy(f);assert.equal(f.p1.board.length,5);});
test('mirror concise face text and detailed rules share detail and tooltip paths',()=>{const g=loadGame(),c=g.cloneCard('as2');assert.equal(c.text,'아군 하나를 그대로 복사');assert.match(c.effectDetails,/아이템/);assert.match(c.effectDetails,/버프/);assert.ok(g.buildLoreSkillsHtml(c).includes(c.effectDetails));assert.ok(g.collectAbilityTips(c).some(t=>t.desc===c.effectDetails));});
test('mirror added deathrattles trigger on copy without consuming source effects',()=>{const f=fixture();f.g.applyFx(f.p1,{type:'buff',addDeathrattle:{type:'draw',value:2},deathText:'파괴: 카드 2장 뽑기'},{kind:'minion',owner:f.p1,minion:f.m});const c=copy(f);f.g.destroyMinion(f.p1,c,{fromSpell:true});assert.equal(f.p1.hand.length,2);assert.equal(f.m.deathrattles[0].value,2);assert.ok(f.p1.board.includes(f.m));});
test('mirror protection can be consumed independently on original and copy',()=>{const f=fixture();f.g.equipItemOnUnit(f.p1,f.g.cloneCard('li6'),f.m);const c=copy(f),hp=c.hp;f.g.damageMinion(f.p1,c,1,{});assert.equal(c.hp,hp);assert.ok(f.m.keywords.includes('shield'));f.g.damageMinion(f.p1,c,1,{});assert.equal(c.hp,hp-1);f.g.damageMinion(f.p1,f.m,1,{});assert.equal(f.m.hp,hp);});
test('mirror acquired consecutive attacks still trigger copied attack item on each hit',async()=>{const f=fixture();f.g.equipItemOnUnit(f.p1,f.g.cloneCard('fi7'),f.m);f.g.applyFx(f.p1,{type:'grant_extra'},{kind:'minion',owner:f.p1,minion:f.m});const c=copy(f);c.atkC=c.defC=c.hpC=0;c.atk=1;await f.g.doAttack(f.p1,c,{kind:'hero',owner:f.p2},false);assert.deepEqual(f.p1.hand.map(x=>x.id),['fs3','fs3']);});
test('mirror includes buffs and equipment newly granted after silence without changing erased-base reset',()=>{const f=fixture('d27');f.g.silenceMinion(f.m,f.p1);f.g.equipItemOnUnit(f.p1,f.g.cloneCard('fi3'),f.m);f.g.applyFx(f.p1,{type:'buff',addDeathrattle:{type:'draw',value:1},deathText:'파괴: 카드 1장 뽑기'},{kind:'minion',owner:f.p1,minion:f.m});const c=copy(f);assert.equal(c.atkSkill,4);assert.equal(c.deathrattles[0].value,1);assert.match(c.text,/파괴/);assert.ok(!c.text.includes('침묵'));assert.equal(c.silenced,undefined);assert.equal(c.ability,null);assert.equal(c.equippedItem.id,'fi3');c.deathrattles[0].value=99;assert.equal(f.m.deathrattles[0].value,1);});
test('mirror retains a hand-applied soul cost buff on the summoned instance',()=>{const f=fixture('e29');f.p1.hand=[f.m];f.g.applyFx(f.p1,{type:'hand_cost',delta:-2,filter:'minion'},null);const c=copy(f);assert.equal(c.cost,f.m.cost);});
